#
#	Makefile -- Tools directory Makefile. 
#
#	Copyright (c) Mbedthis Software LLC, 2003-2007. All Rights Reserved.
#

BUILD_CROSS	:= 0
PRE_DIRS	:= bootstrap

include make.dep

## Local variables:
## tab-width: 4
## End:
## vim: sw=4 ts=4
