#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOPRESEED}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Loading preseed file"

# live-initramfs script

if [ -e /preseed.cfg ]
then
	chroot /root debconf-set-selections < /preseed.cfg
fi

if [ -f "/root/${LOCATION}" ]
then
	chroot /root debconf-set-selections < "/root/${LOCATION}"
fi

if [ -n "${PRESEEDS}" ]
then
	for preseed in ${PRESEEDS}
	do
		question="${preseed%%=*}"
		value="${preseed#*=}"

		live-preseed /root "${question}" "${value}"
	done
fi

reply="$(echo "GET preseed/early_command" | chroot /root debconf-communicate -fnoninteractive live-initramfs)"

if [ "${reply#0 }" != "${reply}" ]
then
	reply="${reply#0 }"
	sh -c "${reply}"
fi

# Clear out debconf database backup files to save memory.
rm -f /root/var/cache/debconf/*.dat-old

log_end_msg

exit 0
