INCLUDES=-I. -I../ -I../../../ -I../../../linux -I../../../../guilib

SRCS=DVDFactorySubtitle.cpp DVDSubtitleLineCollection.cpp DVDSubtitleParserSubrip.cpp DVDSubtitleStream.cpp

LIB=dvdinputstream.a

include ../../../../Makefile.include
-include Makefile.depend
