static char* ObjectTypesNameTable[32] = {
	"NULL",
	"AAC Main",
	"AAC LC",
	"AAC SSR",
	"AAC LTP",
	"Reserved",
	"AAC Scalable",
	"TwinVQ",
	"CELP",
	"HVXC",
	"Reserved",
	"Reserved",
	"TTSI",
	"Main synthetic",
	"Wavetable synthesis",
	"General MIDI",
	"Algorithmic Synthesis and Audio FX",
	/* MPEG-4 Version 2 */
	"ER AAC LC",
	"(Reserved)",
	"ER AAC LTP",
	"ER AAC scalable",
	"ER TwinVQ",
	"ER BSAC",
	"ER AAC LD",
	"ER CELP",
	"ER HVXC",
	"ER HILN",
	"ER Parametric",
	"(Reserved)",
	"(Reserved)",
	"(Reserved)",
	"(Reserved)"
};