# Project: devcpp
# Makefile created by Dev-C++ 4.9.9.1

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = \
  obj/main.o \
  obj/test_2func.o \
  obj/test_array.o \
  obj/test_arrayobject.o \
  obj/test_circularimport.o \
  obj/test_condition.o \
  obj/test_configaccess.o \
  obj/test_constproperty.o \
  obj/test_constructor.o \
  obj/test_constructor2.o \
  obj/test_conversion.o \
  obj/test_dict.o \
  obj/test_discard.o \
  obj/test_exception.o \
  obj/test_exceptionmemory.o \
  obj/test_float.o \
  obj/test_funcoverload.o \
  obj/test_import.o \
  obj/test_multiassign.o \
  obj/test_nested.o \
  obj/test_nevervisited.o \
  obj/test_notinitialized.o \
  obj/test_object.o \
  obj/test_object2.o \
  obj/test_object3.o \
  obj/test_optimize.o \
  obj/test_pointer.o \
  obj/test_return_with_cdecl_objfirst.o \
  obj/test_saveload.o \
  obj/test_stdvector.o \
  obj/test_suspend.o \
  obj/test_vector3.o \
  obj/test_vector3_2.o \
  obj/test2modules.o \
  obj/testbstr.o \
  obj/testbstr2.o \
  obj/testcdecl_class.o \
  obj/testcdecl_class_a.o \
  obj/testcdecl_class_c.o \
  obj/testcdecl_class_d.o \
  obj/testcreateengine.o \
  obj/testenumglobvar.o \
  obj/testexecute.o \
  obj/testexecute1arg.o \
  obj/testexecute2args.o \
  obj/testexecute32args.o \
  obj/testexecute32mixedargs.o \
  obj/testexecute4args.o \
  obj/testexecute4argsf.o \
  obj/testexecutemixedargs.o \
  obj/testexecutescript.o \
  obj/testexecutestring.o \
  obj/testexecutethis32mixedargs.o \
  obj/testglobalvar.o \
  obj/testint64.o \
  obj/testlongtoken.o \
  obj/testmoduleref.o \
  obj/testmultipleinheritance.o \
  obj/testnegateoperator.o \
  obj/testnotcomplexstdcall.o \
  obj/testnotcomplexthiscall.o \
  obj/testoutput.o \
  obj/testreturn.o \
  obj/testreturnd.o \
  obj/testreturnf.o \
  obj/teststack.o \
  obj/teststdcall4args.o \
  obj/teststdstring.o \
  obj/testswitch.o \
  obj/testtempvar.o \
  obj/testvirtualinheritance.o \
  obj/testvirtualmethod.o \
  obj/utils.o \
  obj/bstr.o \
  obj/test_argref.o \
  obj/test_objhandle.o \
  obj/test_arrayhandle.o \
  obj/test_objhandle2.o \
  obj/test_refargument.o \
  obj/test_objzerosize.o \
  obj/test_import2.o \
  obj/test_debug.o \
  obj/test_generic.o \
  obj/test_custommem.o \
  obj/test_stack2.o \
  obj/test_constobject.o \
  obj/test_scriptstring.o \
  obj/scriptstring.o \
  obj/stdstring.o \
  obj/test_scriptstruct.o \
  obj/test_autohandle.o \
  obj/test_any.o \
  obj/test_structintf.o \
  obj/test_arrayintf.o \
  obj/test_stream.o \
  obj/test_dynamicconfig.o \
  obj/test_config.o 
LINKOBJ  = obj/*.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"../../../../angelscript/lib" ../../../../angelscript/lib/AngelScript.a  -g3 
INCS =  -I"C:/Dev-Cpp/include"  -I"../../../../angelscript/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++/3.3.1"  -I"C:/Dev-Cpp/include/c++/3.3.1/mingw32"  -I"C:/Dev-Cpp/include/c++/3.3.1/backward"  -I"C:/Dev-Cpp/lib/gcc-lib/mingw32/3.3.1/include"  -I"C:/Dev-Cpp/include"  -I"../../../../angelscript/include" 
BIN  = ../../bin/devcpp.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3

.PHONY: all all-before all-after clean clean-custom

all: all-before ../../bin/devcpp.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "..\..\bin\devcpp.exe" $(LIBS)

obj/main.o: ../../source/main.cpp
	$(CPP) -c ../../source/main.cpp -o obj/main.o $(CXXFLAGS)

obj/test_2func.o: ../../source/test_2func.cpp
	$(CPP) -c ../../source/test_2func.cpp -o obj/test_2func.o $(CXXFLAGS)

obj/test_array.o: ../../source/test_array.cpp
	$(CPP) -c ../../source/test_array.cpp -o obj/test_array.o $(CXXFLAGS)

obj/test_arrayobject.o: ../../source/test_arrayobject.cpp
	$(CPP) -c ../../source/test_arrayobject.cpp -o obj/test_arrayobject.o $(CXXFLAGS)

obj/test_circularimport.o: ../../source/test_circularimport.cpp
	$(CPP) -c ../../source/test_circularimport.cpp -o obj/test_circularimport.o $(CXXFLAGS)

obj/test_condition.o: ../../source/test_condition.cpp
	$(CPP) -c ../../source/test_condition.cpp -o obj/test_condition.o $(CXXFLAGS)

obj/test_configaccess.o: ../../source/test_configaccess.cpp
	$(CPP) -c ../../source/test_configaccess.cpp -o obj/test_configaccess.o $(CXXFLAGS)

obj/test_constproperty.o: ../../source/test_constproperty.cpp
	$(CPP) -c ../../source/test_constproperty.cpp -o obj/test_constproperty.o $(CXXFLAGS)

obj/test_constructor.o: ../../source/test_constructor.cpp
	$(CPP) -c ../../source/test_constructor.cpp -o obj/test_constructor.o $(CXXFLAGS)

obj/test_constructor2.o: ../../source/test_constructor2.cpp
	$(CPP) -c ../../source/test_constructor2.cpp -o obj/test_constructor2.o $(CXXFLAGS)

obj/test_conversion.o: ../../source/test_conversion.cpp
	$(CPP) -c ../../source/test_conversion.cpp -o obj/test_conversion.o $(CXXFLAGS)

obj/test_dict.o: ../../source/test_dict.cpp
	$(CPP) -c ../../source/test_dict.cpp -o obj/test_dict.o $(CXXFLAGS)

obj/test_discard.o: ../../source/test_discard.cpp
	$(CPP) -c ../../source/test_discard.cpp -o obj/test_discard.o $(CXXFLAGS)

obj/test_exception.o: ../../source/test_exception.cpp
	$(CPP) -c ../../source/test_exception.cpp -o obj/test_exception.o $(CXXFLAGS)

obj/test_exceptionmemory.o: ../../source/test_exceptionmemory.cpp
	$(CPP) -c ../../source/test_exceptionmemory.cpp -o obj/test_exceptionmemory.o $(CXXFLAGS)

obj/test_float.o: ../../source/test_float.cpp
	$(CPP) -c ../../source/test_float.cpp -o obj/test_float.o $(CXXFLAGS)

obj/test_funcoverload.o: ../../source/test_funcoverload.cpp
	$(CPP) -c ../../source/test_funcoverload.cpp -o obj/test_funcoverload.o $(CXXFLAGS)

obj/test_import.o: ../../source/test_import.cpp
	$(CPP) -c ../../source/test_import.cpp -o obj/test_import.o $(CXXFLAGS)

obj/test_multiassign.o: ../../source/test_multiassign.cpp
	$(CPP) -c ../../source/test_multiassign.cpp -o obj/test_multiassign.o $(CXXFLAGS)

obj/test_nested.o: ../../source/test_nested.cpp
	$(CPP) -c ../../source/test_nested.cpp -o obj/test_nested.o $(CXXFLAGS)

obj/test_nevervisited.o: ../../source/test_nevervisited.cpp
	$(CPP) -c ../../source/test_nevervisited.cpp -o obj/test_nevervisited.o $(CXXFLAGS)

obj/test_notinitialized.o: ../../source/test_notinitialized.cpp
	$(CPP) -c ../../source/test_notinitialized.cpp -o obj/test_notinitialized.o $(CXXFLAGS)

obj/test_object.o: ../../source/test_object.cpp
	$(CPP) -c ../../source/test_object.cpp -o obj/test_object.o $(CXXFLAGS)

obj/test_object2.o: ../../source/test_object2.cpp
	$(CPP) -c ../../source/test_object2.cpp -o obj/test_object2.o $(CXXFLAGS)

obj/test_object3.o: ../../source/test_object3.cpp
	$(CPP) -c ../../source/test_object3.cpp -o obj/test_object3.o $(CXXFLAGS)

obj/test_optimize.o: ../../source/test_optimize.cpp
	$(CPP) -c ../../source/test_optimize.cpp -o obj/test_optimize.o $(CXXFLAGS)

obj/test_pointer.o: ../../source/test_pointer.cpp
	$(CPP) -c ../../source/test_pointer.cpp -o obj/test_pointer.o $(CXXFLAGS)

obj/test_return_with_cdecl_objfirst.o: ../../source/test_return_with_cdecl_objfirst.cpp
	$(CPP) -c ../../source/test_return_with_cdecl_objfirst.cpp -o obj/test_return_with_cdecl_objfirst.o $(CXXFLAGS)

obj/test_saveload.o: ../../source/test_saveload.cpp
	$(CPP) -c ../../source/test_saveload.cpp -o obj/test_saveload.o $(CXXFLAGS)

obj/test_stdvector.o: ../../source/test_stdvector.cpp
	$(CPP) -c ../../source/test_stdvector.cpp -o obj/test_stdvector.o $(CXXFLAGS)

obj/test_suspend.o: ../../source/test_suspend.cpp
	$(CPP) -c ../../source/test_suspend.cpp -o obj/test_suspend.o $(CXXFLAGS)

obj/test_vector3.o: ../../source/test_vector3.cpp
	$(CPP) -c ../../source/test_vector3.cpp -o obj/test_vector3.o $(CXXFLAGS)

obj/test_vector3_2.o: ../../source/test_vector3_2.cpp
	$(CPP) -c ../../source/test_vector3_2.cpp -o obj/test_vector3_2.o $(CXXFLAGS)

obj/test2modules.o: ../../source/test2modules.cpp
	$(CPP) -c ../../source/test2modules.cpp -o obj/test2modules.o $(CXXFLAGS)

obj/testbstr.o: ../../source/testbstr.cpp
	$(CPP) -c ../../source/testbstr.cpp -o obj/testbstr.o $(CXXFLAGS)

obj/testbstr2.o: ../../source/testbstr2.cpp
	$(CPP) -c ../../source/testbstr2.cpp -o obj/testbstr2.o $(CXXFLAGS)

obj/testcdecl_class.o: ../../source/testcdecl_class.cpp
	$(CPP) -c ../../source/testcdecl_class.cpp -o obj/testcdecl_class.o $(CXXFLAGS)

obj/testcdecl_class_a.o: ../../source/testcdecl_class_a.cpp
	$(CPP) -c ../../source/testcdecl_class_a.cpp -o obj/testcdecl_class_a.o $(CXXFLAGS)

obj/testcdecl_class_c.o: ../../source/testcdecl_class_c.cpp
	$(CPP) -c ../../source/testcdecl_class_c.cpp -o obj/testcdecl_class_c.o $(CXXFLAGS)

obj/testcdecl_class_d.o: ../../source/testcdecl_class_d.cpp
	$(CPP) -c ../../source/testcdecl_class_d.cpp -o obj/testcdecl_class_d.o $(CXXFLAGS)

obj/testcreateengine.o: ../../source/testcreateengine.cpp
	$(CPP) -c ../../source/testcreateengine.cpp -o obj/testcreateengine.o $(CXXFLAGS)

obj/testenumglobvar.o: ../../source/testenumglobvar.cpp
	$(CPP) -c ../../source/testenumglobvar.cpp -o obj/testenumglobvar.o $(CXXFLAGS)

obj/testexecute.o: ../../source/testexecute.cpp
	$(CPP) -c ../../source/testexecute.cpp -o obj/testexecute.o $(CXXFLAGS)

obj/testexecute1arg.o: ../../source/testexecute1arg.cpp
	$(CPP) -c ../../source/testexecute1arg.cpp -o obj/testexecute1arg.o $(CXXFLAGS)

obj/testexecute2args.o: ../../source/testexecute2args.cpp
	$(CPP) -c ../../source/testexecute2args.cpp -o obj/testexecute2args.o $(CXXFLAGS)

obj/testexecute32args.o: ../../source/testexecute32args.cpp
	$(CPP) -c ../../source/testexecute32args.cpp -o obj/testexecute32args.o $(CXXFLAGS)

obj/testexecute32mixedargs.o: ../../source/testexecute32mixedargs.cpp
	$(CPP) -c ../../source/testexecute32mixedargs.cpp -o obj/testexecute32mixedargs.o $(CXXFLAGS)

obj/testexecute4args.o: ../../source/testexecute4args.cpp
	$(CPP) -c ../../source/testexecute4args.cpp -o obj/testexecute4args.o $(CXXFLAGS)

obj/testexecute4argsf.o: ../../source/testexecute4argsf.cpp
	$(CPP) -c ../../source/testexecute4argsf.cpp -o obj/testexecute4argsf.o $(CXXFLAGS)

obj/testexecutemixedargs.o: ../../source/testexecutemixedargs.cpp
	$(CPP) -c ../../source/testexecutemixedargs.cpp -o obj/testexecutemixedargs.o $(CXXFLAGS)

obj/testexecutescript.o: ../../source/testexecutescript.cpp
	$(CPP) -c ../../source/testexecutescript.cpp -o obj/testexecutescript.o $(CXXFLAGS)

obj/testexecutestring.o: ../../source/testexecutestring.cpp
	$(CPP) -c ../../source/testexecutestring.cpp -o obj/testexecutestring.o $(CXXFLAGS)

obj/testexecutethis32mixedargs.o: ../../source/testexecutethis32mixedargs.cpp
	$(CPP) -c ../../source/testexecutethis32mixedargs.cpp -o obj/testexecutethis32mixedargs.o $(CXXFLAGS)

obj/testglobalvar.o: ../../source/testglobalvar.cpp
	$(CPP) -c ../../source/testglobalvar.cpp -o obj/testglobalvar.o $(CXXFLAGS)

obj/testint64.o: ../../source/testint64.cpp
	$(CPP) -c ../../source/testint64.cpp -o obj/testint64.o $(CXXFLAGS)

obj/testlongtoken.o: ../../source/testlongtoken.cpp
	$(CPP) -c ../../source/testlongtoken.cpp -o obj/testlongtoken.o $(CXXFLAGS)

obj/testmoduleref.o: ../../source/testmoduleref.cpp
	$(CPP) -c ../../source/testmoduleref.cpp -o obj/testmoduleref.o $(CXXFLAGS)

obj/testmultipleinheritance.o: ../../source/testmultipleinheritance.cpp
	$(CPP) -c ../../source/testmultipleinheritance.cpp -o obj/testmultipleinheritance.o $(CXXFLAGS)

obj/testnegateoperator.o: ../../source/testnegateoperator.cpp
	$(CPP) -c ../../source/testnegateoperator.cpp -o obj/testnegateoperator.o $(CXXFLAGS)

obj/testnotcomplexstdcall.o: ../../source/testnotcomplexstdcall.cpp
	$(CPP) -c ../../source/testnotcomplexstdcall.cpp -o obj/testnotcomplexstdcall.o $(CXXFLAGS)

obj/testnotcomplexthiscall.o: ../../source/testnotcomplexthiscall.cpp
	$(CPP) -c ../../source/testnotcomplexthiscall.cpp -o obj/testnotcomplexthiscall.o $(CXXFLAGS)

obj/testoutput.o: ../../source/testoutput.cpp
	$(CPP) -c ../../source/testoutput.cpp -o obj/testoutput.o $(CXXFLAGS)

obj/testreturn.o: ../../source/testreturn.cpp
	$(CPP) -c ../../source/testreturn.cpp -o obj/testreturn.o $(CXXFLAGS)

obj/testreturnd.o: ../../source/testreturnd.cpp
	$(CPP) -c ../../source/testreturnd.cpp -o obj/testreturnd.o $(CXXFLAGS)

obj/testreturnf.o: ../../source/testreturnf.cpp
	$(CPP) -c ../../source/testreturnf.cpp -o obj/testreturnf.o $(CXXFLAGS)

obj/teststack.o: ../../source/teststack.cpp
	$(CPP) -c ../../source/teststack.cpp -o obj/teststack.o $(CXXFLAGS)

obj/teststdcall4args.o: ../../source/teststdcall4args.cpp
	$(CPP) -c ../../source/teststdcall4args.cpp -o obj/teststdcall4args.o $(CXXFLAGS)

obj/teststdstring.o: ../../source/teststdstring.cpp
	$(CPP) -c ../../source/teststdstring.cpp -o obj/teststdstring.o $(CXXFLAGS)

obj/testswitch.o: ../../source/testswitch.cpp
	$(CPP) -c ../../source/testswitch.cpp -o obj/testswitch.o $(CXXFLAGS)

obj/testtempvar.o: ../../source/testtempvar.cpp
	$(CPP) -c ../../source/testtempvar.cpp -o obj/testtempvar.o $(CXXFLAGS)

obj/testvirtualinheritance.o: ../../source/testvirtualinheritance.cpp
	$(CPP) -c ../../source/testvirtualinheritance.cpp -o obj/testvirtualinheritance.o $(CXXFLAGS)

obj/testvirtualmethod.o: ../../source/testvirtualmethod.cpp
	$(CPP) -c ../../source/testvirtualmethod.cpp -o obj/testvirtualmethod.o $(CXXFLAGS)

obj/utils.o: ../../source/utils.cpp
	$(CPP) -c ../../source/utils.cpp -o obj/utils.o $(CXXFLAGS)

obj/bstr.o: ../../source/bstr.cpp
	$(CPP) -c ../../source/bstr.cpp -o obj/bstr.o $(CXXFLAGS)

obj/test_argref.o: ../../source/test_argref.cpp
	$(CPP) -c ../../source/test_argref.cpp -o obj/test_argref.o $(CXXFLAGS)

obj/test_objhandle.o: ../../source/test_objhandle.cpp
	$(CPP) -c ../../source/test_objhandle.cpp -o obj/test_objhandle.o $(CXXFLAGS)

obj/test_arrayhandle.o: ../../source/test_arrayhandle.cpp
	$(CPP) -c ../../source/test_arrayhandle.cpp -o obj/test_arrayhandle.o $(CXXFLAGS)

obj/test_objhandle2.o: ../../source/test_objhandle2.cpp
	$(CPP) -c ../../source/test_objhandle2.cpp -o obj/test_objhandle2.o $(CXXFLAGS)

obj/test_refargument.o: ../../source/test_refargument.cpp
	$(CPP) -c ../../source/test_refargument.cpp -o obj/test_refargument.o $(CXXFLAGS)

obj/test_objzerosize.o: ../../source/test_objzerosize.cpp
	$(CPP) -c ../../source/test_objzerosize.cpp -o obj/test_objzerosize.o $(CXXFLAGS)

obj/test_import2.o: ../../source/test_import2.cpp
	$(CPP) -c ../../source/test_import2.cpp -o obj/test_import2.o $(CXXFLAGS)

obj/test_debug.o: ../../source/test_debug.cpp
	$(CPP) -c ../../source/test_debug.cpp -o obj/test_debug.o $(CXXFLAGS)

obj/test_generic.o: ../../source/test_generic.cpp
	$(CPP) -c ../../source/test_generic.cpp -o obj/test_generic.o $(CXXFLAGS)

obj/test_custommem.o: ../../source/test_custommem.cpp
	$(CPP) -c ../../source/test_custommem.cpp -o obj/test_custommem.o $(CXXFLAGS)

obj/test_stack2.o: ../../source/test_stack2.cpp
	$(CPP) -c ../../source/test_stack2.cpp -o obj/test_stack2.o $(CXXFLAGS)

obj/test_constobject.o: ../../source/test_constobject.cpp
	$(CPP) -c ../../source/test_constobject.cpp -o obj/test_constobject.o $(CXXFLAGS)

obj/test_scriptstring.o: ../../source/test_scriptstring.cpp
	$(CPP) -c ../../source/test_scriptstring.cpp -o obj/test_scriptstring.o $(CXXFLAGS)

obj/scriptstring.o: ../../../../add_on/scriptstring/scriptstring.cpp
	$(CPP) -c ../../../../add_on/scriptstring/scriptstring.cpp -o obj/scriptstring.o $(CXXFLAGS)

obj/stdstring.o: ../../source/stdstring.cpp
	$(CPP) -c ../../source/stdstring.cpp -o obj/stdstring.o $(CXXFLAGS)

obj/test_scriptstruct.o: ../../source/test_scriptstruct.cpp
	$(CPP) -c ../../source/test_scriptstruct.cpp -o obj/test_scriptstruct.o $(CXXFLAGS)

obj/test_autohandle.o: ../../source/test_autohandle.cpp
	$(CPP) -c ../../source/test_autohandle.cpp -o obj/test_autohandle.o $(CXXFLAGS)

obj/test_any.o: ../../source/test_any.cpp
	$(CPP) -c ../../source/test_any.cpp -o obj/test_any.o $(CXXFLAGS)

obj/test_structintf.o: ../../source/test_structintf.cpp
	$(CPP) -c ../../source/test_structintf.cpp -o obj/test_structintf.o $(CXXFLAGS)

obj/test_arrayintf.o: ../../source/test_arrayintf.cpp
	$(CPP) -c ../../source/test_arrayintf.cpp -o obj/test_arrayintf.o $(CXXFLAGS)

obj/test_stream.o: ../../source/test_stream.cpp
	$(CPP) -c ../../source/test_stream.cpp -o obj/test_stream.o $(CXXFLAGS)

obj/test_dynamicconfig.o: ../../source/test_dynamicconfig.cpp
	$(CPP) -c ../../source/test_dynamicconfig.cpp -o obj/test_dynamicconfig.o $(CXXFLAGS)

obj/test_config.o: ../../source/test_config.cpp
	$(CPP) -c ../../source/test_config.cpp -o obj/test_config.o $(CXXFLAGS)
