.\"     Title: live-snapshot
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 06/29/2009
.\"    Manual: 
.\"    Source: 
.\"
.TH "LIVE\-SNAPSHOT" "1" "06/29/2009" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
live-snapshot \- a simple script to ease persistence usage
.SH "SYNOPSIS"
live\-snapshot [\-c|\-\-cow \fBDIRECTORY\fRs] [\-d|\-\-device \fBDEVICE\fR] [\-e|\-\-exclude\-list \fBFILE\fR] [\-o|\-\-output \fBFILE\fR] [\-t|\-\-type \fBTYPE\fR]
.sp
live\-snapshot [\-r|\-\-resync\-string \fBSTRING\fR]
.sp
live\-snapshot [\-h|\-\-help]
.sp
live\-snapshot [\-u|\-\-usage]
.sp
live\-snapshot [\-v|\-\-version]
.sp
.SH "DESCRIPTION"
live\-snapshot is a script which can be used to build the right types of persistent image files supported by live\-initramfs(7)\&. It is also used on exit by the live\-initramfs init script to resync the boot\-found snapshots devices\&.
.sp
.SH "OPTIONS"
.PP
\-c, \-\-cow \fBDIRECTORY\fR
.RS 4
specifies the input directory to be cloned in the image file\&. Its default value "/live/cow" should be right for most uses\&. However it could be handy to specify "/home" and type ext2 for the type to prepare an image file suited to be directly mounted by live\-initramfs as home\&.
.RE
.PP
\-d, \-\-device \fBDEVICE\fR
.RS 4
sets the device where the media which the snapshot/persistence file/partition will be put\&. If it is not specified, a tmpfs will be used and linked to the user\'s desktop to move it where it is needed\&. If the device has no filesystem, an ext2 fs will be automatically created and labelled according to the values specified after the "\-\-output" value or with a sane default\&.
.RE
.PP
\-e, \-\-exclude\-list \fBFILE\fR
.RS 4
a file containing a list of filenames/paths that should not be saved\&. This exclude list will be remebered on the target snapshot media for reuse\&.
.RE
.PP
\-o, \-\-output \fBFILE\fR
.RS 4
the filename/label used for the output file/partition\&. If left blank, live\-snapshot will search for a proper file on the device or use the whole partition\&.
.RE
.PP
\-r, \-\-resync\-string \fBSTRING\fR
.RS 4
internally used on resyncs\&.
.RE
.PP
\-f, \-\-refresh
.RS 4
try to do the same operation that should be done at reboot or halt, resyncing boot\-time auto discovered snapshots\&. Useful to prevent a crash or surge power\-off\&.
.RE
.PP
\-t, \-\-type \fBTYPE\fR
.RS 4
Type could be one of "cpio", "squashfs", "ext2", "ext3", "ext4", or "jffs2"\&.
.RE
.PP
\-h, \-\-help
.RS 4
display help and exit
.RE
.PP
\-u, \-\-usage
.RS 4
show usage and exit
.RE
.PP
\-v, \-\-version
.RS 4
output version information and exit
.RE
.SH "FILES"
.sp
.RS 4
.nf
/etc/live\-snapshot\&.list
.fi
.RE
This optional file, if present changes the behaviour of live\-snapshot, only files and directories listed there are included (integrally) in the snapshot\&. It works only for cpio and whole partition targets\&.
.sp
.sp
.RS 4
.nf
/etc/live\-snapshot\&.exclude_list
.fi
.RE
This optional file, if present will filter the files that will be saved by live\-snapshot removing (as in "grep \-F \-v") all filenames that will be matched by strings listed in it\&. It works for cpio, whole partition and squashfs snapshot types only; it is pretty useful for filtering temporary files and disk caches\&.
.sp
.SH "SEE ALSO"
live\-initramfs(8)
.sp
This program is a part of live\-initramfs\&.
.sp
.SH "BUGS"
Report bugs against live\-initramfs \fIhttp://packages\&.qa\&.debian\&.org/live\-initramfs\fR\&.
.sp
.SH "HOMEPAGE"
More information about the Debian Live project can be found at \fIhttp://debian\-live\&.alioth\&.debian\&.org/\fR and \fIhttp://wiki\&.debian\&.org/DebianLive/\fR\&.
.sp
.SH "AUTHORS"
live\-initramfs is maintained by Daniel Baumann <daniel@debian\&.org> for the Debian project\&. live\-initramfs is a fork of \fIcasper\fR\&[1]\&. casper was originally written by Tollef Fog Heen <tfheen@canonical\&.com> and Matt Zimmerman <mdz@canonical\&.com>\&.
.sp
.SH "NOTES"
.IP " 1." 4
casper
.RS 4
\%http://packages.ubuntu.com/casper/
.RE
