#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libreplaygain_synthesis
INCLUDES = -I./include -I$(topdir)/include -I$(topdir)/include/share

SRCS_C = \
	replaygain_synthesis.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
