INCLUDES=-I. -I../../ -I../../../../ -I../../../../linux -I../../../../../guilib

SRCS=DVDVideoCodecFFmpeg.cpp DVDVideoCodecLibMpeg2.cpp DVDVideoPPFFmpeg.cpp

LIB=dvdcodecs_video.a

include ../../../../../Makefile.include
-include Makefile.depend
