#!/bin/sh

set -e

autoreconf -vif
autoreconf -vif lib/cpluff
autoreconf -vif xbmc/lib/libass
autoreconf -vif xbmc/cores/dvdplayer/Codecs/libbdnav
[ -d xbmc/cores/dvdplayer/Codecs/libdvd/libdvdcss ] && \
  autoreconf -vif xbmc/cores/dvdplayer/Codecs/libdvd/libdvdcss
autoreconf -vif xbmc/cores/dvdplayer/Codecs/libdvd/libdvdread
autoreconf -vif xbmc/cores/dvdplayer/Codecs/libdvd/libdvdnav

echo "Please (re)run configure..."

