SRCS=PVRChannel.cpp \
     PVRChannelGroup.cpp \
     PVRChannelGroupInternal.cpp \
     PVRChannelGroups.cpp \
     PVRChannelGroupsContainer.cpp

LIB=pvrchannels.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
