INCLUDES=-I. -I../../../ -I../../../linux -I../../../../guilib

SRCS=DVDFactoryInputStream.cpp DVDInputStream.cpp DVDInputStreamFile.cpp DVDInputStreamHttp.cpp DVDInputStreamMemory.cpp DVDInputStreamNavigator.cpp DVDStateSerializer.cpp DVDInputStreamFFmpeg.cpp DVDInputStreamMyth.cpp

LIB=dvdinputstream.a

include ../../../../Makefile.include
-include Makefile.depend
