SRCS=ButtonTranslator.cpp \
     InertialScrollingHandler.cpp \
     KeyboardLayout.cpp \
     KeyboardLayoutConfiguration.cpp \
     KeyboardStat.cpp \
     MouseStat.cpp \
     SDLJoystick.cpp \
     XBMC_keytable.cpp \
     
LIB=input.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
