/*
    SDL - Simple DirectMedia Layer
    Copyright (C) 1997-2009 Sam Lantinga

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

    Sam Lantinga
    slouken@libsdl.org
*/

#ifndef XBMC_vkeys_h
#define XBMC_vkeys_h

// The XBMC_vkey identifies a key that is mapped to an action or function.
// The keysym.sym generated by SDL_KEYDOWN is mapped to a vkey and the vkey
// is used to lookup an action in the global mapping table.
// The values are based on the Windows virtual key codes.

typedef enum {
  XBMCVK_LBUTTON        = 0x01,
  XBMCVK_RBUTTON        = 0x02,
  XBMCVK_CANCEL         = 0x03,
  XBMCVK_MBUTTON        = 0x04,
  XBMCVK_XBUTTON1       = 0x05,
  XBMCVK_XBUTTON2       = 0x06,
  XBMCVK_BACK           = 0x08,
  XBMCVK_TAB            = 0x09,
  XBMCVK_CLEAR          = 0x0C,
  XBMCVK_RETURN         = 0x0D,
  XBMCVK_SHIFT          = 0x10,
  XBMCVK_CONTROL        = 0x11,
  XBMCVK_MENU           = 0x12,
  XBMCVK_PAUSE          = 0x13,
  XBMCVK_CAPITAL        = 0x14,
  XBMCVK_KANA           = 0x15,
  XBMCVK_HANGUL         = 0x15,
  XBMCVK_JUNJA          = 0x17,
  XBMCVK_FINAL          = 0x18,
  XBMCVK_HANJA          = 0x19,
  XBMCVK_KANJI          = 0x19,
  XBMCVK_ESCAPE         = 0x1B,
  XBMCVK_CONVERT        = 0x1C,
  XBMCVK_NONCONVERT     = 0x1D,
  XBMCVK_ACCEPT         = 0x1E,
  XBMCVK_MODECHANGE     = 0x1F,
  XBMCVK_SPACE          = 0x20,
  XBMCVK_PRIOR          = 0x21,
  XBMCVK_NEXT           = 0x22,
  XBMCVK_END            = 0x23,
  XBMCVK_HOME           = 0x24,
  XBMCVK_LEFT           = 0x25,
  XBMCVK_UP             = 0x26,
  XBMCVK_RIGHT          = 0x27,
  XBMCVK_DOWN           = 0x28,
  XBMCVK_SELECT         = 0x29,
  XBMCVK_PRINT          = 0x2A,
  XBMCVK_EXECUTE        = 0x2B,
  XBMCVK_SNAPSHOT       = 0x2C,
  XBMCVK_INSERT         = 0x2D,
  XBMCVK_DELETE         = 0x2E,
  XBMCVK_HELP           = 0x2F,
  // XBMCVK_0 - XBMCVK_9 are the same as ASCII '0' - '9'
  // XBMCVK_A - XBMCVK_Z are the same as ASCII 'A' - 'Z'
  XBMCVK_LWIN           = 0x5B,
  XBMCVK_RWIN           = 0x5C,
  XBMCVK_APPS           = 0x5D,
  XBMCVK_SLEEP          = 0x5F,
  XBMCVK_NUMPAD0        = 0x60,
  XBMCVK_NUMPAD1        = 0x61,
  XBMCVK_NUMPAD2        = 0x62,
  XBMCVK_NUMPAD3        = 0x63,
  XBMCVK_NUMPAD4        = 0x64,
  XBMCVK_NUMPAD5        = 0x65,
  XBMCVK_NUMPAD6        = 0x66,
  XBMCVK_NUMPAD7        = 0x67,
  XBMCVK_NUMPAD8        = 0x68,
  XBMCVK_NUMPAD9        = 0x69,
  XBMCVK_MULTIPLY       = 0x6A,
  XBMCVK_ADD            = 0x6B,
  XBMCVK_SEPARATOR      = 0x6C,
  XBMCVK_SUBTRACT       = 0x6D,
  XBMCVK_DECIMAL        = 0x6E,
  XBMCVK_DIVIDE         = 0x6F,
  XBMCVK_F1             = 0x70,
  XBMCVK_F2             = 0x71,
  XBMCVK_F3             = 0x72,
  XBMCVK_F4             = 0x73,
  XBMCVK_F5             = 0x74,
  XBMCVK_F6             = 0x75,
  XBMCVK_F7             = 0x76,
  XBMCVK_F8             = 0x77,
  XBMCVK_F9             = 0x78,
  XBMCVK_F10            = 0x79,
  XBMCVK_F11            = 0x7A,
  XBMCVK_F12            = 0x7B,
  XBMCVK_F13            = 0x7C,
  XBMCVK_F14            = 0x7D,
  XBMCVK_F15            = 0x7E,
  XBMCVK_F16            = 0x7F,
  XBMCVK_F17            = 0x80,
  XBMCVK_F18            = 0x81,
  XBMCVK_F19            = 0x82,
  XBMCVK_F20            = 0x83,
  XBMCVK_F21            = 0x84,
  XBMCVK_F22            = 0x85,
  XBMCVK_F23            = 0x86,
  XBMCVK_F24            = 0x87,
  XBMCVK_NUMLOCK        = 0x90,
  XBMCVK_SCROLL         = 0x91,
  XBMCVK_OEM_NEC_EQUAL  = 0x92,   // '=' key on numpad
  XBMCVK_OEM_FJ_JISHO   = 0x92,   // 'Dictionary' key
  XBMCVK_OEM_FJ_MASSHOU = 0x93,   // 'Unregister word' key
  XBMCVK_OEM_FJ_TOUROKU = 0x94,   // 'Register word' key
  XBMCVK_OEM_FJ_LOYA    = 0x95,   // 'Left OYAYUBI' key
  XBMCVK_OEM_FJ_ROYA    = 0x96,   // 'Right OYAYUBI' key
// * XBMCVK_L* & XBMCVK_R* - left and right Alt, Ctrl and Shift virtual keys.
  XBMCVK_LSHIFT         = 0xA0,
  XBMCVK_RSHIFT         = 0xA1,
  XBMCVK_LCONTROL       = 0xA2,
  XBMCVK_RCONTROL       = 0xA3,
  XBMCVK_LMENU          = 0xA4,
  XBMCVK_RMENU          = 0xA5,
  XBMCVK_BROWSER_BACK        = 0xA6,
  XBMCVK_BROWSER_FORWARD     = 0xA7,
  XBMCVK_BROWSER_REFRESH     = 0xA8,
  XBMCVK_BROWSER_STOP        = 0xA9,
  XBMCVK_BROWSER_SEARCH      = 0xAA,
  XBMCVK_BROWSER_FAVORITES   = 0xAB,
  XBMCVK_BROWSER_HOME        = 0xAC,
  XBMCVK_VOLUME_MUTE         = 0xAD,
  XBMCVK_VOLUME_DOWN         = 0xAE,
  XBMCVK_VOLUME_UP           = 0xAF,
  XBMCVK_MEDIA_NEXT_TRACK    = 0xB0,
  XBMCVK_MEDIA_PREV_TRACK    = 0xB1,
  XBMCVK_MEDIA_STOP          = 0xB2,
  XBMCVK_MEDIA_PLAY_PAUSE    = 0xB3,
  XBMCVK_LAUNCH_MAIL         = 0xB4,
  XBMCVK_LAUNCH_MEDIA_SELECT = 0xB5,
  XBMCVK_LAUNCH_APP1         = 0xB6,
  XBMCVK_LAUNCH_APP2         = 0xB7,
  XBMCVK_OEM_1          = 0xBA,   // ';:' for US
  XBMCVK_OEM_PLUS       = 0xBB,   // '+' any country
  XBMCVK_OEM_COMMA      = 0xBC,   // ',' any country
  XBMCVK_OEM_MINUS      = 0xBD,   // '-' any country
  XBMCVK_OEM_PERIOD     = 0xBE,   // '.' any country
  XBMCVK_OEM_2          = 0xBF,   // '/?' for US
  XBMCVK_OEM_3          = 0xC0,   // '`~' for US
  XBMCVK_OEM_4          = 0xDB,  //  '[{' for US
  XBMCVK_OEM_5          = 0xDC,  //  '\|' for US
  XBMCVK_OEM_6          = 0xDD,  //  ']}' for US
  XBMCVK_OEM_7          = 0xDE,  //  ''"' for US
  XBMCVK_OEM_8          = 0xDF,
  XBMCVK_OEM_AX         = 0xE1,  //  'AX' key on Japanese AX kbd
  XBMCVK_OEM_102        = 0xE2,  //  "<>" or "\|" on RT 102-key kbd.
  XBMCVK_ICO_HELP       = 0xE3,  //  Help key on ICO
  XBMCVK_ICO_00         = 0xE4,  //  00 key on ICO
  XBMCVK_PROCESSKEY     = 0xE5,
  XBMCVK_ICO_CLEAR      = 0xE6,
  XBMCVK_PACKET         = 0xE7,
  XBMCVK_OEM_RESET      = 0xE9,
  XBMCVK_OEM_JUMP       = 0xEA,
  XBMCVK_OEM_PA1        = 0xEB,
  XBMCVK_OEM_PA2        = 0xEC,
  XBMCVK_OEM_PA3        = 0xED,
  XBMCVK_OEM_WSCTRL     = 0xEE,
  XBMCVK_OEM_CUSEL      = 0xEF,
  XBMCVK_OEM_ATTN       = 0xF0,
  XBMCVK_OEM_FINISH     = 0xF1,
  XBMCVK_OEM_COPY       = 0xF2,
  XBMCVK_OEM_AUTO       = 0xF3,
  XBMCVK_OEM_ENLW       = 0xF4,
  XBMCVK_OEM_BACKTAB    = 0xF5,
  XBMCVK_ATTN           = 0xF6,
  XBMCVK_CRSEL          = 0xF7,
  XBMCVK_EXSEL          = 0xF8,
  XBMCVK_EREOF          = 0xF9,
  XBMCVK_PLAY           = 0xFA,
  XBMCVK_ZOOM           = 0xFB,
  XBMCVK_NONAME         = 0xFC,
  XBMCVK_PA1            = 0xFD,
  XBMCVK_OEM_CLEAR      = 0xFE,
} XBMCVKey;

// These should be in winuser.h. Not sure why they have been defined here
#ifndef VK_0
#define VK_0	'0'
#define VK_1	'1'
#define VK_2	'2'
#define VK_3	'3'
#define VK_4	'4'
#define VK_5	'5'
#define VK_6	'6'
#define VK_7	'7'
#define VK_8	'8'
#define VK_9	'9'
#define VK_A	'A'
#define VK_B	'B'
#define VK_C	'C'
#define VK_D	'D'
#define VK_E	'E'
#define VK_F	'F'
#define VK_G	'G'
#define VK_H	'H'
#define VK_I	'I'
#define VK_J	'J'
#define VK_K	'K'
#define VK_L	'L'
#define VK_M	'M'
#define VK_N	'N'
#define VK_O	'O'
#define VK_P	'P'
#define VK_Q	'Q'
#define VK_R	'R'
#define VK_S	'S'
#define VK_T	'T'
#define VK_U	'U'
#define VK_V	'V'
#define VK_W	'W'
#define VK_X	'X'
#define VK_Y	'Y'
#define VK_Z	'Z'
#endif /* VK_0 */

/* These keys haven't been defined, but were experimentally determined */
#ifndef VK_SEMICOLON
#define VK_SEMICOLON	0xBA
#define VK_EQUALS	0xBB
#define VK_COMMA	0xBC
#define VK_MINUS	0xBD
#define VK_PERIOD	0xBE
#define VK_SLASH	0xBF
#define VK_GRAVE	0xC0
#define VK_LBRACKET	0xDB
#define VK_BACKSLASH	0xDC
#define VK_RBRACKET	0xDD
#define VK_APOSTROPHE	0xDE
#define VK_BACKTICK	0xDF
#define VK_OEM_102	0xE2
#endif

#endif // XBMC_vkeys_h
