INCLUDES=-I. -I/usr/include/SDL -I..
CFLAGS+=-DHAS_SDL

SRCS=ConvUtils.cpp XEventUtils.cpp XFileUtils.cpp XHandle.cpp XSyncUtils.cpp XTimeUtils.cpp

LIB=linux.a

include ../../Makefile.include

-include Makefile.depend
