INCLUDES=-I. -I.. -I../../ -I../../linux -I../../../guilib
SRCS=LinuxRenderer.cpp RenderManager.cpp LinuxRendererATI.cpp LinuxRendererGL.cpp
DIRS=VideoShaders

LIB=VideoRenderer.a

include ../../../Makefile.include
-include Makefile.depend
