SRCS=RetroPlayer.cpp \
     RetroPlayerAudio.cpp \
     RetroPlayerBuffer.cpp \
     RetroPlayerDialogs.cpp \
     RetroPlayerInput.cpp \
     RetroPlayerVideo.cpp

LIB=retroplayer.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
