AR = ar
ARFLAGS = rus
RM = rm -f

CXX=g++
CC=gcc

DEFINES := -D_LINUX 
OBJS := daap.o debug.o dmap_generics.o global.o httpClient.o ioloop.o libXDAAP.o threadpool.o Authentication/hasher.o Authentication/md5.o

.c.o:
	rm -f ${<:.c=.o}
	$(CC) -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 -c $(CFLAGS) $(DEFINES) $(INCLUDES) $< -o ${<:.c=.o}

libxdaap-osx.a: $(OBJS)
	$(AR) $(ARFLAGS) libxdaap-osx.a $(OBJS)

all: libxdaap-osx.a

clean:
	$(RM) $(OBJS) libxdaap-osx.a
