/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "MINGW32_NT-5.1 MLCLAP3 1.0.10(0.46/3/2) 2004-03-15 07:17 i686 unknown"
#define BUILD_ENV_DATE "Sun Jul 30 23:52:59 WEDT 2006"
#define BUILD_ENV_SRCDIR "/c/Sandbox/Xbox/XBMC/docs/libsamba/libsamba_new/source"
#define BUILD_ENV_BUILDDIR "/c/Sandbox/Xbox/XBMC/docs/libsamba/libsamba_new/source"
#define BUILD_ENV_USER "Joakim"
#define BUILD_ENV_HOST "MLCLAP3"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
