# French messages for international release of SWAT.
# Copyright (C) 2001 François Le Lay <fanch@tuxfamily.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2003-10-06 05:30+0900\n"
"PO-Revision-Date: 2000-02-08 14:45+0100\n"
"Last-Translator: François Le Lay <fanch@tuxfamily.org>\n"
"Language-Team: (Samba Team) <samba-technical@samba.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: \n"

#: ../web/swat.c:117
#, c-format
msgid "ERROR: Can't open %s"
msgstr ""

#: ../web/swat.c:200
msgid "Help"
msgstr "Aide"

#: ../web/swat.c:206 ../web/swat.c:220 ../web/swat.c:235 ../web/swat.c:243 ../web/swat.c:252 ../web/swat.c:261 ../web/swat.c:267 ../web/swat.c:273 ../web/swat.c:286
msgid "Set Default"
msgstr "Définir par défaut"

#: ../web/swat.c:408
#, c-format
msgid "failed to open %s for writing"
msgstr ""

#: ../web/swat.c:431
#, c-format
msgid "Can't reload %s"
msgstr ""

#: ../web/swat.c:501
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Connecté en tant que <b>%s</b>"

#: ../web/swat.c:505
msgid "Home"
msgstr "Home"

#: ../web/swat.c:507
msgid "Globals"
msgstr "Paramètres Généraux"

#: ../web/swat.c:508
msgid "Shares"
msgstr "Partages"

#: ../web/swat.c:509
msgid "Printers"
msgstr "Imprimantes"

#: ../web/swat.c:510
msgid "Wizard"
msgstr ""

#: ../web/swat.c:513
msgid "Status"
msgstr "Statut"

#: ../web/swat.c:514
msgid "View Config"
msgstr "Voir Configuration"

#: ../web/swat.c:516
msgid "Password Management"
msgstr "Gestion des mots de passe"

#: ../web/swat.c:526
msgid "Current View Is"
msgstr "Configuration Actuelle"

#: ../web/swat.c:527 ../web/swat.c:530
msgid "Basic"
msgstr "Vue Basique"

#: ../web/swat.c:528 ../web/swat.c:531
msgid "Advanced"
msgstr "Vue Détaillée"

#: ../web/swat.c:529
msgid "Change View To"
msgstr "Modifier le mot de passe"

#: ../web/swat.c:554
msgid "Current Config"
msgstr "Configuration Actuelle"

#: ../web/swat.c:558
msgid "Normal View"
msgstr "Vue Normale"

#: ../web/swat.c:560
msgid "Full View"
msgstr "Vue Complète"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:579
msgid "Wizard Parameter Edit Page"
msgstr ""

#: ../web/swat.c:608
msgid "Note: smb.conf file has been read and rewritten"
msgstr ""

#. Here we go ...
#: ../web/swat.c:716
msgid "Samba Configuration Wizard"
msgstr ""

#: ../web/swat.c:720
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr ""

#: ../web/swat.c:721
msgid "The same will happen if you press the commit button."
msgstr ""

#: ../web/swat.c:724
msgid "Rewrite smb.conf file"
msgstr ""

#: ../web/swat.c:725
msgid "Commit"
msgstr "commentaire"

#: ../web/swat.c:726
msgid "Edit Parameter Values"
msgstr "Paramètres Imprimantes"

#: ../web/swat.c:732
msgid "Server Type"
msgstr ""

#: ../web/swat.c:733
msgid "Stand Alone"
msgstr ""

#: ../web/swat.c:734
msgid "Domain Member"
msgstr "master de domaine"

#: ../web/swat.c:735
msgid "Domain Controller"
msgstr "master de domaine"

#: ../web/swat.c:738
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr ""

#: ../web/swat.c:740
msgid "Configure WINS As"
msgstr ""

#: ../web/swat.c:741
msgid "Not Used"
msgstr "ne pas descendre"

#: ../web/swat.c:742
msgid "Server for client use"
msgstr ""

#: ../web/swat.c:743
msgid "Client of another WINS server"
msgstr ""

#: ../web/swat.c:745
msgid "Remote WINS Server"
msgstr ""

#: ../web/swat.c:756
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr ""

#: ../web/swat.c:757
msgid "Please Select desired WINS mode above."
msgstr ""

#: ../web/swat.c:759
msgid "Expose Home Directories"
msgstr ""

#: ../web/swat.c:774
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr ""

#: ../web/swat.c:787
msgid "Global Parameters"
msgstr "Variables Globales"

#: ../web/swat.c:815 ../web/swat.c:916 ../web/swat.c:1265
msgid "Commit Changes"
msgstr "Sauver les modifications"

#: ../web/swat.c:819 ../web/swat.c:919 ../web/swat.c:1267
msgid "Reset Values"
msgstr "Réinitialiser Valeurs"

#: ../web/swat.c:844
msgid "Share Parameters"
msgstr "Paramètres de partage"

#: ../web/swat.c:887
msgid "Choose Share"
msgstr "Choisir un partage"

#: ../web/swat.c:901
msgid "Delete Share"
msgstr "Supprimer un partage"

#: ../web/swat.c:908
msgid "Create Share"
msgstr "Créer un partage"

#: ../web/swat.c:944
msgid "password change in demo mode rejected"
msgstr "changement de mot de passe en mode démo rejeté"

#: ../web/swat.c:957
msgid "Can't setup password database vectors."
msgstr ""

#: ../web/swat.c:983
msgid " Must specify \"User Name\" "
msgstr "  Le champ \"Nom d'utilisateur\" doit être spécifié"

#: ../web/swat.c:999
msgid " Must specify \"Old Password\" "
msgstr " Le champ  \"Ancien mot de passe\" doît être spécifié"

#: ../web/swat.c:1005
msgid " Must specify \"Remote Machine\" "
msgstr "  Le champ \"Machine Distante\" doît être spécifié"

#: ../web/swat.c:1012
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr "Les champs \"Nouveau mot de passe\" et  \"Confirmation du nouveau mot de passe\" doivent être spécifiés \n"

#: ../web/swat.c:1018
msgid " Re-typed password didn't match new password "
msgstr " Echec de la confirmation du nouveau mot de passe"

#: ../web/swat.c:1048
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Le mot de passe de '%s' a été modifié. "

#: ../web/swat.c:1051
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Le mot de passe de '%s' n'a PAS été modifié. \n"

#: ../web/swat.c:1076
msgid "Server Password Management"
msgstr "Gestion des mots de passe serveur"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1085 ../web/swat.c:1132
msgid "User Name"
msgstr " Nom d'utilisateur : "

#: ../web/swat.c:1088 ../web/swat.c:1134
msgid "Old Password"
msgstr " Ancien mot de passe : "

#: ../web/swat.c:1091 ../web/swat.c:1136
msgid "New Password"
msgstr " Nouveau mot de passe : "

#: ../web/swat.c:1093 ../web/swat.c:1138
msgid "Re-type New Password"
msgstr " Confirmation du nouveau mot de passe : "

#: ../web/swat.c:1101 ../web/swat.c:1149
msgid "Change Password"
msgstr "Modifier le mot de passe"

#: ../web/swat.c:1104
msgid "Add New User"
msgstr "Nouvel Utilisateur"

#: ../web/swat.c:1106
msgid "Delete User"
msgstr "Supprimer Utilisateur"

#: ../web/swat.c:1108
msgid "Disable User"
msgstr "Désactiver Utilisateur"

#: ../web/swat.c:1110
msgid "Enable User"
msgstr "Activer Utilisateur"

#: ../web/swat.c:1123
msgid "Client/Server Password Management"
msgstr "Gestion des mots de passe Client/Serveur"

#: ../web/swat.c:1140
msgid "Remote Machine"
msgstr " Machine distante : "

#: ../web/swat.c:1179
msgid "Printer Parameters"
msgstr "Paramètres Imprimantes"

#: ../web/swat.c:1181
msgid "Important Note:"
msgstr "Note Importante:"

#: ../web/swat.c:1182
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Les Noms d'imprimantes marqués du signe [*] dans le menu déroulant Choisir Imprimante"

#: ../web/swat.c:1183
msgid "are autoloaded printers from "
msgstr "désignent des imprimantes automatiquement chargées depuis le "

#: ../web/swat.c:1184
msgid "Printcap Name"
msgstr "Nom Printcap"

#: ../web/swat.c:1185
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr "Essayer de supprimer ces imprimantes depuis SWAT n'aura aucun effet."

#: ../web/swat.c:1231
msgid "Choose Printer"
msgstr "Choisir Imprimante"

#: ../web/swat.c:1250
msgid "Delete Printer"
msgstr "Supprimer Imprimante"

#: ../web/swat.c:1257
msgid "Create Printer"
msgstr "Créer Imprimante"

#: ../web/statuspage.c:123
msgid "RDONLY     "
msgstr ""

#: ../web/statuspage.c:124
msgid "WRONLY     "
msgstr ""

#: ../web/statuspage.c:125
msgid "RDWR       "
msgstr ""

#: ../web/statuspage.c:309
msgid "Server Status"
msgstr "Statut du Serveur"

#: ../web/statuspage.c:314
msgid "Auto Refresh"
msgstr "Rafraîchissement Automatique"

#: ../web/statuspage.c:315 ../web/statuspage.c:320
msgid "Refresh Interval: "
msgstr "Intervalle de rafraîchissement: "

#: ../web/statuspage.c:319
msgid "Stop Refreshing"
msgstr "Stopper Rafraîchissement"

#: ../web/statuspage.c:334
msgid "version:"
msgstr "version:"

#: ../web/statuspage.c:337
msgid "smbd:"
msgstr ""

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "running"
msgstr "actif"

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "not running"
msgstr "non actif"

#: ../web/statuspage.c:341
msgid "Stop smbd"
msgstr "Stopper smbd"

#: ../web/statuspage.c:343
msgid "Start smbd"
msgstr "Lancer smbd"

#: ../web/statuspage.c:345
msgid "Restart smbd"
msgstr "Relancer smbd"

#: ../web/statuspage.c:350
msgid "nmbd:"
msgstr ""

#: ../web/statuspage.c:354
msgid "Stop nmbd"
msgstr "Stopper nmbd"

#: ../web/statuspage.c:356
msgid "Start nmbd"
msgstr "Lancer nmbd"

#: ../web/statuspage.c:358
msgid "Restart nmbd"
msgstr "Relancer nmbd"

#: ../web/statuspage.c:364
msgid "winbindd:"
msgstr ""

#: ../web/statuspage.c:368
msgid "Stop winbindd"
msgstr "Stopper nmbd"

#: ../web/statuspage.c:370
msgid "Start winbindd"
msgstr "Lancer nmbd"

#: ../web/statuspage.c:372
msgid "Restart winbindd"
msgstr "Relancer nmbd"

#. stop, restart all
#: ../web/statuspage.c:381
msgid "Stop All"
msgstr ""

#: ../web/statuspage.c:382
msgid "Restart All"
msgstr "Relancer nmbd"

#. start all
#: ../web/statuspage.c:386
msgid "Start All"
msgstr "Lancer nmbd"

#: ../web/statuspage.c:393
msgid "Active Connections"
msgstr "Connections Actives"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "PID"
msgstr ""

#: ../web/statuspage.c:395 ../web/statuspage.c:408
msgid "Client"
msgstr ""

#: ../web/statuspage.c:395
msgid "IP address"
msgstr "adresse IP"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "Date"
msgstr "Date"

#: ../web/statuspage.c:397
msgid "Kill"
msgstr "Terminer"

#: ../web/statuspage.c:405
msgid "Active Shares"
msgstr "Partages Actifs"

#: ../web/statuspage.c:408
msgid "Share"
msgstr "Partager"

#: ../web/statuspage.c:408
msgid "User"
msgstr "Utilisateur"

#: ../web/statuspage.c:408
msgid "Group"
msgstr "Groupe"

#: ../web/statuspage.c:414
msgid "Open Files"
msgstr "Fichiers Ouverts"

#: ../web/statuspage.c:416
msgid "Sharing"
msgstr ""

#: ../web/statuspage.c:416
msgid "R/W"
msgstr ""

#: ../web/statuspage.c:416
msgid "Oplock"
msgstr ""

#: ../web/statuspage.c:416
msgid "File"
msgstr "Fichier"

#: ../web/statuspage.c:425
msgid "Show Client in col 1"
msgstr ""

#: ../web/statuspage.c:426
msgid "Show PID in col 1"
msgstr ""

#: ../param/loadparm.c:755
msgid "Base Options"
msgstr "Options de base"

#: ../param/loadparm.c:775
msgid "Security Options"
msgstr "Options de Sécurité"

#: ../param/loadparm.c:859
msgid "Logging Options"
msgstr "Options de Logging"

#: ../param/loadparm.c:874
msgid "Protocol Options"
msgstr "Options de Protocole"

#: ../param/loadparm.c:911
msgid "Tuning Options"
msgstr "Options de réglage"

#: ../param/loadparm.c:940
msgid "Printing Options"
msgstr "Options d'impression"

#: ../param/loadparm.c:970
msgid "Filename Handling"
msgstr "Gestion des noms de fichier"

#: ../param/loadparm.c:996
msgid "Domain Options"
msgstr "Options de Domaine"

#: ../param/loadparm.c:1000
msgid "Logon Options"
msgstr "Options de Logon"

#: ../param/loadparm.c:1019
msgid "Browse Options"
msgstr "Options de Navigation"

#: ../param/loadparm.c:1033
msgid "WINS Options"
msgstr "Options WINS"

#: ../param/loadparm.c:1043
msgid "Locking Options"
msgstr "Options de Verrouillage"

#: ../param/loadparm.c:1061
msgid "Ldap Options"
msgstr "Options Ldap"

#: ../param/loadparm.c:1078
msgid "Miscellaneous Options"
msgstr "Options Diverses"

#: ../param/loadparm.c:1138
msgid "VFS module options"
msgstr "Options VFS"

#: ../param/loadparm.c:1148
msgid "Winbind options"
msgstr "Options Winbind"
