# Turkish messages for international release of SWAT.
# Copyright (C) 2001 Deniz Akkus Kanca <deniz@arayan.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2003-10-06 05:30+0900\n"
"PO-Revision-Date: 2001-09-20 22:51EEST\n"
"Last-Translator: Deniz Akkus Kanca <deniz@arayan.com>\n"
"Language-Team: Turkish <gnu-tr-u12a@lists.sourceforge.net>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 0.9.1\n"

#: ../web/swat.c:117
#, c-format
msgid "ERROR: Can't open %s"
msgstr ""

#: ../web/swat.c:200
msgid "Help"
msgstr "Yardım"

#: ../web/swat.c:206 ../web/swat.c:220 ../web/swat.c:235 ../web/swat.c:243 ../web/swat.c:252 ../web/swat.c:261 ../web/swat.c:267 ../web/swat.c:273 ../web/swat.c:286
msgid "Set Default"
msgstr "Öntanımlıya Ayarla"

#: ../web/swat.c:408
#, c-format
msgid "failed to open %s for writing"
msgstr ""

#: ../web/swat.c:431
#, c-format
msgid "Can't reload %s"
msgstr ""

#: ../web/swat.c:501
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "<b>%s</b> kimliği ile oturum açılmış"

#: ../web/swat.c:505
msgid "Home"
msgstr "Ev"

#: ../web/swat.c:507
msgid "Globals"
msgstr "Evrenseller"

#: ../web/swat.c:508
msgid "Shares"
msgstr "Paylaşımlar"

#: ../web/swat.c:509
msgid "Printers"
msgstr "Yazıcılar"

#: ../web/swat.c:510
msgid "Wizard"
msgstr ""

#: ../web/swat.c:513
msgid "Status"
msgstr "Durum"

#: ../web/swat.c:514
msgid "View Config"
msgstr "Ayarlara Gözat"

#: ../web/swat.c:516
msgid "Password Management"
msgstr "Şifre Yönetimi"

#: ../web/swat.c:526
msgid "Current View Is"
msgstr "Şimdiki Ayarlar"

#: ../web/swat.c:527 ../web/swat.c:530
msgid "Basic"
msgstr "Temel Görünüm"

#: ../web/swat.c:528 ../web/swat.c:531
msgid "Advanced"
msgstr "Gelişmiş Görünüm"

#: ../web/swat.c:529
msgid "Change View To"
msgstr "Şifre Değiştir"

#: ../web/swat.c:554
msgid "Current Config"
msgstr "Şimdiki Ayarlar"

#: ../web/swat.c:558
msgid "Normal View"
msgstr "Normal Görünüm"

#: ../web/swat.c:560
msgid "Full View"
msgstr "Tam Görünüm"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:579
msgid "Wizard Parameter Edit Page"
msgstr ""

#: ../web/swat.c:608
msgid "Note: smb.conf file has been read and rewritten"
msgstr ""

#. Here we go ...
#: ../web/swat.c:716
msgid "Samba Configuration Wizard"
msgstr ""

#: ../web/swat.c:720
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr ""

#: ../web/swat.c:721
msgid "The same will happen if you press the commit button."
msgstr ""

#: ../web/swat.c:724
msgid "Rewrite smb.conf file"
msgstr ""

#: ../web/swat.c:725
msgid "Commit"
msgstr "açıklama"

#: ../web/swat.c:726
msgid "Edit Parameter Values"
msgstr "Yazıcı Bilgileri"

#: ../web/swat.c:732
msgid "Server Type"
msgstr ""

#: ../web/swat.c:733
msgid "Stand Alone"
msgstr "Nmbd'yi çalıştır"

#: ../web/swat.c:734
msgid "Domain Member"
msgstr "alan sunucusu"

#: ../web/swat.c:735
msgid "Domain Controller"
msgstr "alan sunucusu"

#: ../web/swat.c:738
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr ""

#: ../web/swat.c:740
msgid "Configure WINS As"
msgstr ""

#: ../web/swat.c:741
msgid "Not Used"
msgstr "dont descend"

#: ../web/swat.c:742
msgid "Server for client use"
msgstr ""

#: ../web/swat.c:743
msgid "Client of another WINS server"
msgstr ""

#: ../web/swat.c:745
msgid "Remote WINS Server"
msgstr ""

#: ../web/swat.c:756
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr ""

#: ../web/swat.c:757
msgid "Please Select desired WINS mode above."
msgstr ""

#: ../web/swat.c:759
msgid "Expose Home Directories"
msgstr ""

#: ../web/swat.c:774
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr ""

#: ../web/swat.c:787
msgid "Global Parameters"
msgstr "Genel Değişkenler"

#: ../web/swat.c:815 ../web/swat.c:916 ../web/swat.c:1265
msgid "Commit Changes"
msgstr "Değişiklikleri Kaydet"

#: ../web/swat.c:819 ../web/swat.c:919 ../web/swat.c:1267
msgid "Reset Values"
msgstr "Değerleri İlk Haline Getir"

#: ../web/swat.c:844
msgid "Share Parameters"
msgstr "Paylaşım Parametreleri"

#: ../web/swat.c:887
msgid "Choose Share"
msgstr "Paylaşım Seçin"

#: ../web/swat.c:901
msgid "Delete Share"
msgstr "Paylaşım Kaldır"

#: ../web/swat.c:908
msgid "Create Share"
msgstr "Paylaşım Oluştur"

#: ../web/swat.c:944
msgid "password change in demo mode rejected"
msgstr "demo kipinde şifre değişikliği kabul edilmedi\n"

#: ../web/swat.c:957
msgid "Can't setup password database vectors."
msgstr ""

#: ../web/swat.c:983
msgid " Must specify \"User Name\" "
msgstr " \"Kullanıcı Adı\" belirtilmeli \n"

#: ../web/swat.c:999
msgid " Must specify \"Old Password\" "
msgstr " \"Eski Şifre\" belirtilmeli \n"

#: ../web/swat.c:1005
msgid " Must specify \"Remote Machine\" "
msgstr " \"Uzak Makina\" belirtilmeli \n"

#: ../web/swat.c:1012
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr " \"Yeni ve Tekrar Girilmiş Şifreler\" belirtilmeli \n"

#: ../web/swat.c:1018
msgid " Re-typed password didn't match new password "
msgstr " Tekrar girilen şifre yeni şifre ile eşleşmedi\n"

#: ../web/swat.c:1048
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " '%s' için şifre değiştirildi."

#: ../web/swat.c:1051
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " '%s' için şifre DEĞİŞTİRİLMEDİ."

#: ../web/swat.c:1076
msgid "Server Password Management"
msgstr "Sunucu Şifre Yönetimi"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1085 ../web/swat.c:1132
msgid "User Name"
msgstr " Kullanıcı Adı"

#: ../web/swat.c:1088 ../web/swat.c:1134
msgid "Old Password"
msgstr " Eski Şifre"

#: ../web/swat.c:1091 ../web/swat.c:1136
msgid "New Password"
msgstr " Yeni Şifre"

#: ../web/swat.c:1093 ../web/swat.c:1138
msgid "Re-type New Password"
msgstr " Yeni Şifre Tekrarı"

#: ../web/swat.c:1101 ../web/swat.c:1149
msgid "Change Password"
msgstr "Şifre Değiştir"

#: ../web/swat.c:1104
msgid "Add New User"
msgstr "Kull. Ekle"

#: ../web/swat.c:1106
msgid "Delete User"
msgstr "Kull. Sil"

#: ../web/swat.c:1108
msgid "Disable User"
msgstr "Kull. Etkisizleştir"

#: ../web/swat.c:1110
msgid "Enable User"
msgstr "Kull. Etkinleştir"

#: ../web/swat.c:1123
msgid "Client/Server Password Management"
msgstr "İstemci/Sunucu Şifre Yönetimi"

#: ../web/swat.c:1140
msgid "Remote Machine"
msgstr " Uzak Makina"

#: ../web/swat.c:1179
msgid "Printer Parameters"
msgstr "Yazıcı Bilgileri"

#: ../web/swat.c:1181
msgid "Important Note:"
msgstr "Önemli Not:"

#: ../web/swat.c:1182
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Yazıcı Seç kutusunda [*] ile işaretlenmiş yazıcı isimleri "

#: ../web/swat.c:1183
msgid "are autoloaded printers from "
msgstr "otomatik yüklenen yazıcılar "

#: ../web/swat.c:1184
msgid "Printcap Name"
msgstr "Printcap Adı"

#: ../web/swat.c:1185
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr "Bu yazıcıları SWAT'dan silmek etkisiz olacaktır.\n"

#: ../web/swat.c:1231
msgid "Choose Printer"
msgstr "Yazıcı Seç"

#: ../web/swat.c:1250
msgid "Delete Printer"
msgstr "Yazıcı Sil"

#: ../web/swat.c:1257
msgid "Create Printer"
msgstr "Yazıcı Oluştur"

#: ../web/statuspage.c:123
msgid "RDONLY     "
msgstr "SALTOKUNUR    "

#: ../web/statuspage.c:124
msgid "WRONLY     "
msgstr "SALTYAZILIR    "

#: ../web/statuspage.c:125
msgid "RDWR       "
msgstr "O/Y        "

#: ../web/statuspage.c:309
msgid "Server Status"
msgstr "Sunucu Durumu"

#: ../web/statuspage.c:314
msgid "Auto Refresh"
msgstr "Oto Tazele"

#: ../web/statuspage.c:315 ../web/statuspage.c:320
msgid "Refresh Interval: "
msgstr "Tazeleme Aralığı: "

#: ../web/statuspage.c:319
msgid "Stop Refreshing"
msgstr "Tazelemeyi Durdur"

#: ../web/statuspage.c:334
msgid "version:"
msgstr "sürüm:"

#: ../web/statuspage.c:337
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "running"
msgstr "çalışıyor"

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "not running"
msgstr "çalışmıyor"

#: ../web/statuspage.c:341
msgid "Stop smbd"
msgstr "Smbd'yi durdur"

#: ../web/statuspage.c:343
msgid "Start smbd"
msgstr "Smbd'yi çalıştır"

#: ../web/statuspage.c:345
msgid "Restart smbd"
msgstr "Smbd'yi yeniden çalıştır"

#: ../web/statuspage.c:350
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:354
msgid "Stop nmbd"
msgstr "Nmbd'yi durdur"

#: ../web/statuspage.c:356
msgid "Start nmbd"
msgstr "Nmbd'yi çalıştır"

#: ../web/statuspage.c:358
msgid "Restart nmbd"
msgstr "Nmbd'yi yeniden çalıştır"

#: ../web/statuspage.c:364
msgid "winbindd:"
msgstr "winbind uid"

#: ../web/statuspage.c:368
msgid "Stop winbindd"
msgstr "Nmbd'yi durdur"

#: ../web/statuspage.c:370
msgid "Start winbindd"
msgstr "Nmbd'yi çalıştır"

#: ../web/statuspage.c:372
msgid "Restart winbindd"
msgstr "Nmbd'yi yeniden çalıştır"

#. stop, restart all
#: ../web/statuspage.c:381
msgid "Stop All"
msgstr ""

#: ../web/statuspage.c:382
msgid "Restart All"
msgstr "Nmbd'yi yeniden çalıştır"

#. start all
#: ../web/statuspage.c:386
msgid "Start All"
msgstr "Nmbd'yi çalıştır"

#: ../web/statuspage.c:393
msgid "Active Connections"
msgstr "Aktif Bağlantılar"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:395 ../web/statuspage.c:408
msgid "Client"
msgstr "İstemci"

#: ../web/statuspage.c:395
msgid "IP address"
msgstr "IP numarası"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "Date"
msgstr "Tarih"

#: ../web/statuspage.c:397
msgid "Kill"
msgstr "Kapat"

#: ../web/statuspage.c:405
msgid "Active Shares"
msgstr "Aktif Paylaşımlar"

#: ../web/statuspage.c:408
msgid "Share"
msgstr "Paylaşım"

#: ../web/statuspage.c:408
msgid "User"
msgstr "Kullanıcı"

#: ../web/statuspage.c:408
msgid "Group"
msgstr "Grup"

#: ../web/statuspage.c:414
msgid "Open Files"
msgstr "Açık Dosyalar"

#: ../web/statuspage.c:416
msgid "Sharing"
msgstr "Paylaşılıyor"

#: ../web/statuspage.c:416
msgid "R/W"
msgstr "O/Y"

#: ../web/statuspage.c:416
msgid "Oplock"
msgstr "Oplock"

#: ../web/statuspage.c:416
msgid "File"
msgstr "Dosya"

#: ../web/statuspage.c:425
msgid "Show Client in col 1"
msgstr ""

#: ../web/statuspage.c:426
msgid "Show PID in col 1"
msgstr ""

#: ../param/loadparm.c:755
msgid "Base Options"
msgstr "Temel Seçenekler"

#: ../param/loadparm.c:775
msgid "Security Options"
msgstr "Güvenlik Seçenekleri"

#: ../param/loadparm.c:859
msgid "Logging Options"
msgstr "Günlük Kaydı Seçenekleri"

#: ../param/loadparm.c:874
msgid "Protocol Options"
msgstr "Protokol Seçenekleri"

#: ../param/loadparm.c:911
msgid "Tuning Options"
msgstr "Ayar Seçenekleri"

#: ../param/loadparm.c:940
msgid "Printing Options"
msgstr "Yazdırma Seçenekleri"

#: ../param/loadparm.c:970
msgid "Filename Handling"
msgstr "Dosyaadı İşlenmesi"

#: ../param/loadparm.c:996
msgid "Domain Options"
msgstr "Alan Seçenekleri"

#: ../param/loadparm.c:1000
msgid "Logon Options"
msgstr "Sistem Giriş Seçenekleri"

#: ../param/loadparm.c:1019
msgid "Browse Options"
msgstr "Gözatma Seçenekleri"

#: ../param/loadparm.c:1033
msgid "WINS Options"
msgstr "WINS Seçenekleri"

#: ../param/loadparm.c:1043
msgid "Locking Options"
msgstr "Kilitleme Seçenekleri"

#: ../param/loadparm.c:1061
msgid "Ldap Options"
msgstr "Ldap Seçenekleri"

#: ../param/loadparm.c:1078
msgid "Miscellaneous Options"
msgstr "Diğer Seçenekler"

#: ../param/loadparm.c:1138
msgid "VFS module options"
msgstr "VFS Seçenekleri"

#: ../param/loadparm.c:1148
msgid "Winbind options"
msgstr "Winbind seçenekleri"
