.TH extract_a52 "1" "extract_a52"
.SH NAME
extract_a52 \- extract ATSC A/52 audio from a MPEG stream.
.SH SYNOPSIS
.B extract_a52
[\fI-h\fR] [\fI-s [track]\fR] [\fI-t pid\fR] [\fIfile\fR]
.SH DESCRIPTION
`extract_a52' extracts ATSC A/52 audio from a MPEG stream.
Input is from stdin if no file is given.
.TP
\fB\-h\fR
display help
.TP
\fB\-s track\fR
set track number (0-7 or 0x80-0x87)
.TP
\fB\-t pid\fR
use transport stream demultiplexer, pid 0x10-0x1ffe
.SH AUTHORS
Michel Lespinasse <walken@zoy.org>
.br
Aaron Holtzman <aholtzma@ess.engr.uvic.ca>
.br
And many others on the net.
.SH "REPORTING BUGS"
Report bugs to <liba52-devel@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2000-2002 Michel Lespinasse
.br
Copyright \(co 1999-2000 Aaron Holtzman
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR a52dec "(1)"
