INCLUDES=-I. -I../../ -I../../../ffmpeg -I../../../../ -I../../../../linux -I../../../../../guilib

SRCS=	DVDVideoCodecFFmpeg.cpp \
	DVDVideoCodecLibMpeg2.cpp \
	DVDVideoPPFFmpeg.cpp \
        DVDVideoCodecFFmpegVDPAU.cpp

LIB=Video.a

include ../../Makefile.include

