INCLUDES=-I. -I../ -I../../../ -I../.. -I../../ffmpeg -I../../../linux -I../../../../guilib

SRCS=	DVDCodecUtils.cpp \
	DVDFactoryCodec.cpp \

LIB=	DVDCodecs.a

LIBS=	Audio/Audio.a \
	Video/Video.a \
	Overlay/Overlay.a \

DIRS=   Audio \
	Video \
	Overlay \

include ../Makefile.include

