SRCS=AudioLibrary.cpp \
     AVPlayerOperations.cpp \
     AVPlaylistOperations.cpp \
     FileItemHandler.cpp \
     FileOperations.cpp \
     JSONRPC.cpp \
     JSONServiceDescription.cpp \
     PicturePlayerOperations.cpp \
     PlayerOperations.cpp \
     PlaylistOperations.cpp \
     SystemOperations.cpp \
     InputOperations.cpp \
     VideoLibrary.cpp \
     XBMCOperations.cpp \

LIB=json-rpc.a

include ../../../Makefile.include

