SRCS=ApplicationOperations.cpp \
     AudioLibrary.cpp \
     FileItemHandler.cpp \
     FileOperations.cpp \
     GUIOperations.cpp \
     InputOperations.cpp \
     JSONRPC.cpp \
     JSONServiceDescription.cpp \
     PlayerOperations.cpp \
     PlaylistOperations.cpp \
     SystemOperations.cpp \
     VideoLibrary.cpp \
     XBMCOperations.cpp \
     PVROperations.cpp \

LIB=json-rpc.a

include ../../../Makefile.include

