#pragma once
/*
 *      Copyright (C) 2005-2010 Team XBMC
 *      http://www.xbmc.org
 *
 *  This Program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *
 *  This Program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with XBMC; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */

namespace JSONRPC
{
  const char* const JSON_SERVICE_DESCRIPTION = 
  "{"
    "\"id\": \"http://www.xbmc.org/jsonrpc.jsd\","
    "\"version\": 3,"
    "\"description\": \"JSON RPC API of XBMC\","

    "\"JSONRPC.Introspect\": {"
        "\"type\": \"method\","
        "\"description\": \"Enumerates all actions and descriptions\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": ["
            "{ \"name\": \"getdescriptions\", \"type\": \"boolean\", \"default\": true },"
            "{ \"name\": \"getmetadata\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"filterbytransport\", \"type\": \"boolean\", \"default\": true }"
        "],"
        "\"returns\": \"object\""
    "},"
    "\"JSONRPC.Version\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve the jsonrpc protocol version\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"JSONRPC.Permission\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve the clients permissions\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"ReadData\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ControlPlayback\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ControlAnnounce\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ControlPower\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"Logging\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ScanLibrary\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"JSONRPC.Ping\": {"
        "\"type\": \"method\","
        "\"description\": \"Ping responder\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"JSONRPC.GetAnnouncementFlags\": {"
        "\"type\": \"method\","
        "\"description\": \"Get announcement flags\","
        "\"transport\": \"Announcing\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Announcement.Flags\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"Playback\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"GUI\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"System\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"Library\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"Other\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"JSONRPC.SetAnnouncementFlags\": {"
        "\"type\": \"method\","
        "\"description\": \"Change the announcement flags\","
        "\"transport\": \"Announcing\","
        "\"permission\": \"ControlAnnounce\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"Playback\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"GUI\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"System\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"Library\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"Other\", \"type\": \"boolean\", \"default\": false }"
        "],"
        "\"returns\": { \"$ref\": \"Announcement.Flags\" }"
    "},"
    "\"JSONRPC.Announce\": {"
        "\"type\": \"method\","
        "\"description\": \"Announce to other connected clients\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": ["
            "{ \"name\": \"sender\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"message\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"data\", \"type\": \"any\", \"default\": null }"
        "],"
        "\"returns\": \"any\""
    "},"
    "\"Player.GetActivePlayers\": {"
        "\"type\": \"method\","
        "\"description\": \"Returns all active players\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"video\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"audio\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"picture\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.State\": {"
        "\"type\": \"method\","
        "\"description\": \"Returns playback state of the audio player (if it is active)\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Player.State.Extended\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"partymode\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.PlayPause\": {"
        "\"type\": \"method\","
        "\"description\": \"Pauses or unpause playback and returns the new state\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Player.State\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.Stop\": {"
        "\"type\": \"method\","
        "\"description\": \"Stops playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to previous item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to next item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.BigSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.BigSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SmallSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SmallSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.Rewind\": {"
        "\"type\": \"method\","
        "\"description\": \"Rewind current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.Forward\": {"
        "\"type\": \"method\","
        "\"description\": \"Forward current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.GetTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieves the current and total time of the currently playing file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Player.TimeValues\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"time\": { \"type\": \"object\", \"id\": \"Player.Time\", \"required\": true, \"description\": \"\","
                    "\"properties\": {"
                        "\"hours\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 23 },"
                        "\"minutes\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 59 },"
                        "\"seconds\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 59 },"
                        "\"milliseconds\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 999 }"
                    "}"
                "},"
                "\"total\": { \"$ref\": \"Player.Time\", \"required\": true, \"description\": \"\" },"
                "\"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.GetPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve current playback progress in percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": \"number\""
    "},"
    "\"AudioPlayer.SeekTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific time\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"value\", \"id\": \"Player.SeekTime\", \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"description\": \"Time to seek to in seconds\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SeekPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"value\", \"id\": \"Player.SeekPercentage\", \"type\": \"number\", \"required\": true, \"minimum\": 0.0, \"maximum\": 100.0, \"description\": \"Percentage value to seek to\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.State\": {"
        "\"type\": \"method\","
        "\"description\": \"Returns playback state of the video player (if it is active)\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": { \"$ref\": \"Player.State.Extended\" }"
    "},"
    "\"VideoPlayer.PlayPause\": {"
        "\"type\": \"method\","
        "\"description\": \"Pauses or unpause playback and returns the new state\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": { \"$ref\": \"Player.State\" }"
    "},"
    "\"VideoPlayer.Stop\": {"
        "\"type\": \"method\","
        "\"description\": \"Stops playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to previous item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to next item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.BigSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.BigSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SmallSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SmallSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.Rewind\": {"
        "\"type\": \"method\","
        "\"description\": \"Rewind current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.Forward\": {"
        "\"type\": \"method\","
        "\"description\": \"Forward current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.GetTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieves the current and total time of the currently playing file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": { \"$ref\": \"Player.TimeValues\" }"
    "},"
    "\"VideoPlayer.GetPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve current playback progress in percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": \"number\""
    "},"
    "\"VideoPlayer.SeekTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific time\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"value\", \"$ref\": \"Player.SeekTime\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SeekPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"value\", \"$ref\": \"Player.SeekPercentage\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.PlayPause\": {"
        "\"type\": \"method\","
        "\"description\": \"Pauses or unpause slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.Stop\": {"
        "\"type\": \"method\","
        "\"description\": \"Stops slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to previous picture in the slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to next picture in the slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveLeft\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport left otherwise skip previous\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveRight\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport right otherwise skip next\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveDown\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport down\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveUp\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport up\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.ZoomOut\": {"
        "\"type\": \"method\","
        "\"description\": \"Zoom out once\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.ZoomIn\": {"
        "\"type\": \"method\","
        "\"description\": \"Zoom in once\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.Zoom\": {"
        "\"type\": \"method\","
        "\"description\": \"Zooms current picture\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"value\", \"type\": \"integer\", \"required\": true, \"minimum\": 1, \"maximum\": 10, \"description\": \"Zoom level\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.Rotate\": {"
        "\"type\": \"method\","
        "\"description\": \"Rotates current picture\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"

    "\"System.Shutdown\": {"
        "\"type\": \"method\","
        "\"description\": \"Shuts the system running XBMC down\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Suspend\": {"
        "\"type\": \"method\","
        "\"description\": \"Suspends the system running XBMC\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Hibernate\": {"
        "\"type\": \"method\","
        "\"description\": \"Puts the system running XBMC into hibernate mode\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Reboot\": {"
        "\"type\": \"method\","
        "\"description\": \"Reboots the system running XBMC\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.GetInfoLabels\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve info labels about the system\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": ["
            "{ \"name\": \"labels\", \"type\": \"array\", \"required\": true, \"items\": { \"type\": \"string\" }, \"minItems\": 1, \"description\": \"See http://wiki.xbmc.org/index.php?title=InfoLabels for a list of possible info labels\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"description\": \"List of key-value pairs of the retrieved info labels\""
        "}"
    "},"
    "\"System.GetInfoBooleans\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve info booleans about the system\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": ["
            "{ \"name\": \"booleans\", \"type\": \"array\", \"required\": true, \"items\": { \"type\": \"string\" }, \"minItems\": 1, \"description\": \"\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"description\": \"List of key-value pairs of the retrieved info booleans\""
        "}"
    "},"
    "\"XBMC.GetVolume\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve the current volume\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"statechanging\": false,"
        "\"params\": [],"
        "\"returns\": \"integer\""
    "},"
    "\"XBMC.SetVolume\": {"
        "\"type\": \"method\","
        "\"description\": \"Set the current volume\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"value\", \"type\": \"integer\", \"minimum\": 0, \"maximum\": 100, \"required\": true }"
        "],"
        "\"returns\": \"integer\""
    "},"
    "\"XBMC.ToggleMute\": {"
        "\"type\": \"method\","
        "\"description\": \"Toggle mute/unmute\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": { \"type\": \"integer\", \"description\": \"New volume\" }"
    "},"
    "\"XBMC.Play\": {"
        "\"type\": \"method\","
        "\"description\": \"Starts playback of the given file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"file\", \"type\": \"string\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.StartSlideshow\": {"
        "\"type\": \"method\","
        "\"description\": \"Starts slideshow with the images from the given directory\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"directory\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"random\", \"type\": \"boolean\", \"default\": true },"
            "{ \"name\": \"recursive\", \"type\": \"boolean\", \"default\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.Log\": {"
        "\"type\": \"method\","
        "\"description\": \"Logs a line in the xbmc.log\","
        "\"transport\": \"Response\","
        "\"permission\": \"Logging\","
        "\"statechanging\": true,"
        "\"params\": ["
            "{ \"name\": \"message\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"level\", \"type\": \"string\", \"default\": \"debug\", \"enum\": [ \"debug\", \"info\", \"notice\", \"warning\", \"error\", \" severe\", \"fatal\", \"none\" ] }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.Quit\": {"
        "\"type\": \"method\","
        "\"description\": \"Quit XBMC\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"statechanging\": true,"
        "\"params\": [],"
        "\"returns\": \"string\""
    "}"
  "}";

  const char* const JSON_NOTIFICATION_DESCRIPTION =
  "{"

  "}";
}
