#pragma once
/*
 *      Copyright (C) 2005-2010 Team XBMC
 *      http://www.xbmc.org
 *
 *  This Program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *
 *  This Program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with XBMC; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */

namespace JSONRPC
{
  const char* const JSON_SERVICE_DESCRIPTION = 
  "{"
    "\"id\": \"http://www.xbmc.org/jsonrpc.jsd\","
    "\"version\": 3,"
    "\"description\": \"JSON RPC API of XBMC\","

    "\"JSONRPC.Introspect\": {"
        "\"type\": \"method\","
        "\"description\": \"Enumerates all actions and descriptions\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"getdescriptions\", \"type\": \"boolean\", \"default\": true },"
            "{ \"name\": \"getmetadata\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"filterbytransport\", \"type\": \"boolean\", \"default\": true }"
        "],"
        "\"returns\": \"object\""
    "},"
    "\"JSONRPC.Version\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve the jsonrpc protocol version\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"JSONRPC.Permission\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve the clients permissions\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"ReadData\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ControlPlayback\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ControlNotify\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ControlPower\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"Logging\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"ScanLibrary\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"JSONRPC.Ping\": {"
        "\"type\": \"method\","
        "\"description\": \"Ping responder\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"JSONRPC.GetNotificationFlags\": {"
        "\"type\": \"method\","
        "\"description\": \"Get notification flags\","
        "\"transport\": \"Announcing\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Notification.Flags\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"Player\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"GUI\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"System\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"VideoLibrary\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"AudioLibrary\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"Other\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"JSONRPC.SetNotificationFlags\": {"
        "\"type\": \"method\","
        "\"description\": \"Change the notification flags\","
        "\"transport\": \"Announcing\","
        "\"permission\": \"ControlNotify\","
        "\"params\": ["
            "{ \"name\": \"Playback\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"GUI\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"System\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"Library\", \"type\": \"boolean\", \"default\": false },"
            "{ \"name\": \"Other\", \"type\": \"boolean\", \"default\": false }"
        "],"
        "\"returns\": { \"$ref\": \"Notification.Flags\" }"
    "},"
    "\"JSONRPC.NotifyAll\": {"
        "\"type\": \"method\","
        "\"description\": \"Notify all other connected clients\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"sender\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"message\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"data\", \"type\": \"any\", \"default\": null }"
        "],"
        "\"returns\": \"any\""
    "},"
    "\"Player.GetActivePlayers\": {"
        "\"type\": \"method\","
        "\"description\": \"Returns all active players\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"video\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"audio\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"picture\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.State\": {"
        "\"type\": \"method\","
        "\"description\": \"Returns playback state of the audio player (if it is active)\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Player.State.Extended\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"partymode\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.PlayPause\": {"
        "\"type\": \"method\","
        "\"description\": \"Pauses or unpause playback and returns the new state\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Player.State\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.Stop\": {"
        "\"type\": \"method\","
        "\"description\": \"Stops playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to previous item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to next item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.BigSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.BigSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SmallSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SmallSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.Rewind\": {"
        "\"type\": \"method\","
        "\"description\": \"Rewind current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.Forward\": {"
        "\"type\": \"method\","
        "\"description\": \"Forward current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.GetTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieves the current and total time of the currently playing file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": {"
            "\"id\": \"Player.TimeValues\","
            "\"type\": \"object\","
            "\"properties\": {"
                "\"time\": { \"type\": \"object\", \"id\": \"Global.Time\", \"required\": true, \"description\": \"\","
                    "\"properties\": {"
                        "\"hours\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 23 },"
                        "\"minutes\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 59 },"
                        "\"seconds\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 59 },"
                        "\"milliseconds\": { \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"maximum\": 999 }"
                    "}"
                "},"
                "\"total\": { \"$ref\": \"Global.Time\", \"required\": true, \"description\": \"\" },"
                "\"playing\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" },"
                "\"paused\": { \"type\": \"boolean\", \"required\": true, \"description\": \"\" }"
            "}"
        "}"
    "},"
    "\"AudioPlayer.GetPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve current playback progress in percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": \"number\""
    "},"
    "\"AudioPlayer.SeekTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific time\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"value\", \"id\": \"Player.SeekTime\", \"type\": \"integer\", \"required\": true, \"minimum\": 0, \"description\": \"Time to seek to in seconds\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlayer.SeekPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"value\", \"id\": \"Player.SeekPercentage\", \"type\": \"number\", \"required\": true, \"minimum\": 0.0, \"maximum\": 100.0, \"description\": \"Percentage value to seek to\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.State\": {"
        "\"type\": \"method\","
        "\"description\": \"Returns playback state of the video player (if it is active)\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": { \"$ref\": \"Player.State.Extended\" }"
    "},"
    "\"VideoPlayer.PlayPause\": {"
        "\"type\": \"method\","
        "\"description\": \"Pauses or unpause playback and returns the new state\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": { \"$ref\": \"Player.State\" }"
    "},"
    "\"VideoPlayer.Stop\": {"
        "\"type\": \"method\","
        "\"description\": \"Stops playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to previous item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to next item on the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.BigSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.BigSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SmallSkipBackward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SmallSkipForward\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.Rewind\": {"
        "\"type\": \"method\","
        "\"description\": \"Rewind current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.Forward\": {"
        "\"type\": \"method\","
        "\"description\": \"Forward current playback\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.GetTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieves the current and total time of the currently playing file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": { \"$ref\": \"Player.TimeValues\" }"
    "},"
    "\"VideoPlayer.GetPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve current playback progress in percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": \"number\""
    "},"
    "\"VideoPlayer.SeekTime\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific time\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"value\", \"$ref\": \"Player.SeekTime\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlayer.SeekPercentage\": {"
        "\"type\": \"method\","
        "\"description\": \"Seek to a specific percentage\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"value\", \"$ref\": \"Player.SeekPercentage\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.PlayPause\": {"
        "\"type\": \"method\","
        "\"description\": \"Pauses or unpause slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.Stop\": {"
        "\"type\": \"method\","
        "\"description\": \"Stops slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to previous picture in the slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skips to next picture in the slideshow\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveLeft\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport left otherwise skip previous\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveRight\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport right otherwise skip next\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveDown\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport down\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.MoveUp\": {"
        "\"type\": \"method\","
        "\"description\": \"If picture is zoomed move viewport up\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.ZoomOut\": {"
        "\"type\": \"method\","
        "\"description\": \"Zoom out once\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.ZoomIn\": {"
        "\"type\": \"method\","
        "\"description\": \"Zoom in once\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.Zoom\": {"
        "\"type\": \"method\","
        "\"description\": \"Zooms current picture\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"value\", \"type\": \"integer\", \"required\": true, \"minimum\": 1, \"maximum\": 10, \"description\": \"Zoom level\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"PicturePlayer.Rotate\": {"
        "\"type\": \"method\","
        "\"description\": \"Rotates current picture\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.Create\": {"
        "\"type\": \"method\","
        "\"description\": \"Creates a virtual playlist from a given one from a file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"type\": \"object\", \"id\": \"Playlist.Id\", \"required\": true,"
                "\"properties\": {"
                    "\"id\": { \"type\": \"string\", \"description\": \"Identification of a virtual playlist\" },"
                    "\"file\": { \"type\": \"string\", \"description\": \"File from which to load a playlist\" }"
                "}"
            "}"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"playlistid\": { \"type\": \"string\", \"required\": true }"
            "}"
        "}"
    "},"
    "\"Playlist.Destroy\": {"
        "\"type\": \"method\","
        "\"description\": \"Destroys a virtual playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"playlistid\", \"type\": \"string\", \"required\": true, \"description\": \"Identification of the playlist\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.GetItems\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve items in the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"List.Fields.All\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"title\", \"artist\", \"albumartist\", \"genre\", \"year\", \"rating\","
                              "\"album\", \"track\", \"duration\", \"comment\", \"lyrics\", \"musicbrainztrackid\","
                              "\"musicbrainzartistid\", \"musicbrainzalbumid\", \"musicbrainzalbumartistid\","
                              "\"playcount\", \"fanart\", \"director\", \"trailer\", \"tagline\", \"plot\","
                              "\"plotoutline\", \"originaltitle\", \"lastplayed\", \"writer\", \"studio\","
                              "\"mpaa\", \"cast\", \"country\", \"imdbnumber\", \"premiered\", \"productioncode\","
                              "\"runtime\", \"set\", \"showlink\", \"streamDetails\", \"top250\", \"votes\","
                              "\"writingcredits\", \"firstaired\", \"season\", \"episode\", \"showtitle\","
                              "\"thumbnail\", \"file\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"name\": { \"type\": \"string\", \"description\": \"Name of the playlist (if available)\" },"
                "\"items\": { \"type\": \"array\", \"required\": true, \"id\": \"List.Items.All\","
                    "\"items\": { \"type\": \"object\","
                        "\"properties\": {"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"id\": { \"$ref\": \"Library.Id\" },"
                            "\"type\": { \"type\": \"string\", \"enum\": [ \"unknown\", \"movie\", \"episode\", \"musicvideo\", \"song\" ] },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"artist\": { \"type\": \"string\" },"
                            "\"albumartist\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"rating\": { \"type\": \"number\" },"
                            "\"album\": { \"type\": \"string\" },"
                            "\"track\": { \"type\": \"integer\" },"
                            "\"duration\": { \"type\": \"integer\" },"
                            "\"comment\": { \"type\": \"string\" },"
                            "\"lyrics\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"musicbrainztrackid\": { \"type\": \"string\" },"
                            "\"musicbrainzartistid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumartistid\": { \"type\": \"string\" },"
                            "\"director\": { \"type\": \"string\" },"
                            "\"trailer\": { \"type\": \"string\" },"
                            "\"tagline\": { \"type\": \"string\" },"
                            "\"plot\": { \"type\": \"string\" },"
                            "\"plotoutline\": { \"type\": \"string\" },"
                            "\"originaltitle\": { \"type\": \"string\" },"
                            "\"lastplayed\": { \"type\": \"string\" },"
                            "\"writer\": { \"type\": \"string\" },"
                            "\"studio\": { \"type\": \"string\" },"
                            "\"mpaa\": { \"type\": \"string\" },"
                            "\"cast\": { \"$ref\": \"Video.Cast\" },"
                            "\"country\": { \"type\": \"string\" },"
                            "\"imdbnumber\": { \"type\": \"string\" },"
                            "\"premiered\": { \"type\": \"string\" },"
                            "\"productioncode\": { \"type\": \"string\" },"
                            "\"runtime\": { \"type\": \"string\" },"
                            "\"set\": { \"type\": \"string\" },"
                            "\"showlink\": { \"type\": \"string\" },"
                            "\"streamDetails\": { \"$ref\": \"Video.Streams\" },"
                            "\"top250\": { \"type\": \"integer\" },"
                            "\"votes\": { \"type\": \"string\" },"
                            "\"writingcredits\": { \"type\": \"string\" },"
                            "\"firstaired\": { \"type\": \"string\" },"
                            "\"season\": { \"type\": \"integer\" },"
                            "\"episode\": { \"type\": \"integer\" },"
                            "\"showtitle\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"Playlist.Add\": {"
        "\"type\": \"method\","
        "\"description\": \"Add items to the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true },"
            "{ \"name\": \"items\", \"$ref\": \"Playlist.Id\", \"required\": true, \"description\": \"Adds items from given virtual and/or file based playlist\" }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.Remove\": {"
        "\"type\": \"method\","
        "\"description\": \"Remove item from the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true },"
            "{ \"name\": \"item\", \"type\": [ \"integer\", \"string\" ], \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.Swap\": {"
        "\"type\": \"method\","
        "\"description\": \"Swap items in the playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true },"
            "{ \"name\": \"item1\", \"$ref\": \"Playlist.Item.Position\", \"required\": true },"
            "{ \"name\": \"item2\", \"$ref\": \"Playlist.Item.Position\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.Clear\": {"
        "\"type\": \"method\","
        "\"description\": \"Clear playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.Shuffle\": {"
        "\"type\": \"method\","
        "\"description\": \"Shuffle playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"Playlist.UnShuffle\": {"
        "\"type\": \"method\","
        "\"description\": \"Unshuffle playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"playlist\", \"$ref\": \"Playlist.Id\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.Play\": {"
        "\"type\": \"method\","
        "\"description\": \"Play current or a specific item\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"item\", \"id\": \"Playlist.Item.Position\", \"type\": \"integer\", \"minimum\": 0, \"default\": -1, \"description\": \"Position of the item\" }"
        "],"
        "\"returns\":  { \"type\": \"object\","
            "\"properties\": {"
                "\"success\": { \"type\": \"boolean\", \"required\": true }"
            "}"
        "}"
    "},"
    "\"VideoPlaylist.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skip current item and play previous item\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skip current item and play next item\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.GetItems\": {"
        "\"type\": \"method\","
        "\"description\": \"Get all items from playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"List.Fields.Video\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"title\", \"artist\", \"genre\", \"year\", \"rating\", \"album\", \"track\","
                              "\"playcount\", \"fanart\", \"director\", \"trailer\", \"tagline\", \"plot\","
                              "\"plotoutline\", \"originaltitle\", \"lastplayed\", \"writer\", \"studio\","
                              "\"mpaa\", \"country\", \"imdbnumber\", \"premiered\", \"productioncode\","
                              "\"runtime\", \"showlink\", \"streamDetails\", \"top250\", \"votes\","
                              "\"writingcredits\", \"firstaired\", \"season\", \"episode\", \"showtitle\","
                              "\"thumbnail\", \"file\", \"sorttitle\", \"episodeguide\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"state\": { \"type\": \"object\", \"id\": \"Playlist.State\","
                    "\"properties\": {"
                        "\"current\": { \"type\": \"integer\", \"required\": true },"
                        "\"playing\": { \"type\": \"boolean\", \"required\": true },"
                        "\"paused\": { \"type\": \"boolean\", \"required\": true }"
                    "}"
                "},"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"items\": { \"type\": \"array\", \"required\": true,"
                    "\"items\": { \"type\": \"object\","
                        "\"properties\": {"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"id\": { \"$ref\": \"Library.Id\" },"
                            "\"type\": { \"type\": \"string\", \"enum\": [ \"unknown\", \"movie\", \"episode\", \"musicvideo\" ] },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"artist\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"rating\": { \"type\": \"number\" },"
                            "\"album\": { \"type\": \"string\" },"
                            "\"track\": { \"type\": \"integer\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"director\": { \"type\": \"string\" },"
                            "\"trailer\": { \"type\": \"string\" },"
                            "\"tagline\": { \"type\": \"string\" },"
                            "\"plot\": { \"type\": \"string\" },"
                            "\"plotoutline\": { \"type\": \"string\" },"
                            "\"originaltitle\": { \"type\": \"string\" },"
                            "\"sorttitle\": { \"type\": \"string\" },"
                            "\"lastplayed\": { \"type\": \"string\" },"
                            "\"writer\": { \"type\": \"string\" },"
                            "\"studio\": { \"type\": \"string\" },"
                            "\"mpaa\": { \"type\": \"string\" },"
                            "\"country\": { \"type\": \"string\" },"
                            "\"imdbnumber\": { \"type\": \"string\" },"
                            "\"premiered\": { \"type\": \"string\" },"
                            "\"productioncode\": { \"type\": \"string\" },"
                            "\"runtime\": { \"type\": \"string\" },"
                            "\"showlink\": { \"type\": \"string\" },"
                            "\"streamDetails\": { \"$ref\": \"Video.Streams\" },"
                            "\"top250\": { \"type\": \"integer\" },"
                            "\"votes\": { \"type\": \"string\" },"
                            "\"writingcredits\": { \"type\": \"string\" },"
                            "\"firstaired\": { \"type\": \"string\" },"
                            "\"season\": { \"type\": \"integer\" },"
                            "\"episode\": { \"type\": \"integer\" },"
                            "\"episodeguide\": { \"type\": \"string\" },"
                            "\"showtitle\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoPlaylist.Add\": {"
        "\"type\": \"method\","
        "\"description\": \"Add item(s) to playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"item\", \"type\": \"object\", \"id\": \"Playlist.Video.Item\", \"required\": true,"
                "\"properties\": {"
                    "\"file\": { \"type\": \"string\" },"
                    "\"movieid\": { \"$ref\": \"Library.Id\" },"
                    "\"episodeid\": { \"$ref\": \"Library.Id\" },"
                    "\"musicvideoid\": { \"$ref\": \"Library.Id\" },"
                    "\"playlist\": { \"$ref\": \"Playlist.Id\" }"
                "}"
            "}"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.Insert\": {"
        "\"type\": \"method\","
        "\"description\": \"Insert item(s) into playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"index\", \"$ref\": \"Playlist.Item.Position\", \"required\": true },"
            "{ \"name\": \"item\", \"$ref\": \"Playlist.Video.Item\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.Remove\": {"
        "\"type\": \"method\","
        "\"description\": \"Remove item from playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"item\", \"$ref\": \"Playlist.Item.Position\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.Clear\": {"
        "\"type\": \"method\","
        "\"description\": \"Clear playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.Shuffle\": {"
        "\"type\": \"method\","
        "\"description\": \"Shuffle playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"VideoPlaylist.UnShuffle\": {"
        "\"type\": \"method\","
        "\"description\": \"Unshuffle playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.Play\": {"
        "\"type\": \"method\","
        "\"description\": \"Play current or a specific item\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"item\", \"$ref\": \"Playlist.Item.Position\" },"
            "{ \"name\": \"songid\", \"$ref\": \"Library.Id\", \"description\": \"Identification of a song from the audio library\" }"
        "],"
        "\"returns\":  { \"type\": \"object\","
            "\"properties\": {"
                "\"success\": { \"type\": \"boolean\", \"required\": true }"
            "}"
        "}"
    "},"
    "\"AudioPlaylist.SkipPrevious\": {"
        "\"type\": \"method\","
        "\"description\": \"Skip current item and play previous item\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.SkipNext\": {"
        "\"type\": \"method\","
        "\"description\": \"Skip current item and play next item\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.GetItems\": {"
        "\"type\": \"method\","
        "\"description\": \"Get all items from playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Song\" },"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"state\": { \"$ref\": \"Playlist.State\" },"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"items\": { \"type\": \"array\", \"required\": true,"
                    "\"items\": { \"type\": \"object\","
                        "\"properties\": {"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"id\": { \"$ref\": \"Library.Id\" },"
                            "\"type\": { \"type\": \"string\", \"enum\": [ \"unknown\", \"song\" ] },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"artist\": { \"type\": \"string\" },"
                            "\"albumartist\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"rating\": { \"type\": \"integer\" },"
                            "\"album\": { \"type\": \"string\" },"
                            "\"track\": { \"type\": \"integer\" },"
                            "\"duration\": { \"type\": \"integer\" },"
                            "\"comment\": { \"type\": \"string\" },"
                            "\"lyrics\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"musicbrainztrackid\": { \"type\": \"string\" },"
                            "\"musicbrainzartistid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumartistid\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"AudioPlaylist.Add\": {"
        "\"type\": \"method\","
        "\"description\": \"Add item(s) to playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"item\", \"type\": \"object\", \"id\": \"Playlist.Audio.Item\", \"required\": true,"
                "\"properties\": {"
                    "\"file\": { \"type\": \"string\" },"
                    "\"artistid\": { \"$ref\": \"Library.Id\" },"
                    "\"albumid\": { \"$ref\": \"Library.Id\" },"
                    "\"songid\": { \"$ref\": \"Library.Id\" },"
                    "\"genreid\": { \"$ref\": \"Library.Id\" },"
                    "\"playlist\": { \"$ref\": \"Playlist.Id\" }"
                "}"
            "}"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.Insert\": {"
        "\"type\": \"method\","
        "\"description\": \"Insert item(s) into playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"index\", \"$ref\": \"Playlist.Item.Position\", \"required\": true },"
            "{ \"name\": \"item\", \"$ref\": \"Playlist.Audio.Item\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.Remove\": {"
        "\"type\": \"method\","
        "\"description\": \"Remove item from playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"item\", \"$ref\": \"Playlist.Item.Position\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.Clear\": {"
        "\"type\": \"method\","
        "\"description\": \"Clear playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.Shuffle\": {"
        "\"type\": \"method\","
        "\"description\": \"Shuffle playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"AudioPlaylist.UnShuffle\": {"
        "\"type\": \"method\","
        "\"description\": \"Unshuffle playlist\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [ ],"
        "\"returns\": \"string\""
    "},"
    "\"Files.GetSources\": {"
        "\"type\": \"method\","
        "\"description\": \"Get the sources of the media windows\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"media\", \"id\": \"Files.Media\", \"type\": \"string\", \"required\": true, \"enum\": [ \"video\", \"music\", \"pictures\", \"files\", \"programs\" ] },"
            "{ \"name\": \"limits\", \"id\": \"List.Limits\", \"type\": \"object\", \"required\": false,"
                "\"properties\": {"
                    "\"start\": { \"type\": \"integer\", \"minimum\": 0, \"default\": 0 },"
                    "\"end\": { \"type\": \"integer\", \"minimum\": 0, \"default\": -1 }"
                "}"
            "},"
            "{ \"name\": \"sort\", \"id\": \"List.Sort\", \"type\": \"object\", \"required\": false,"
                "\"properties\": {"
                    "\"method\": { \"type\": \"string\", \"default\": \"none\","
                        "\"enum\": [ \"none\", \"label\", \"date\", \"size\", \"file\", \"drivetype\", \"track\", \"duration\", \"title\", \"artist\","
                                  "\"album\", \"genre\", \"year\", \"videorating\", \"programcount\", \"playlist\", \"episode\", \"videotitle\","
                                  "\"sorttitle\", \"productioncode\", \"songrating\", \"mpaarating\", \"videoruntime\", \"studio\", \"fullpath\","
                                  "\"lastplayed\", \"unsorted\", \"max\" ]"
                    "},"
                    "\"order\": { \"type\": \"string\", \"default\": \"ascending\", \"enum\": [ \"ascending\", \"descending\" ] },"
                    "\"ignorearticle\": { \"type\": \"boolean\", \"default\": false }"
                "}"
            "}"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"type\": \"object\", \"id\": \"List.LimitsReturned\", \"required\": true,"
                    "\"properties\": {"
                        "\"start\": { \"type\": \"integer\", \"minimum\": 0, \"required\": true },"
                        "\"end\": { \"type\": \"integer\", \"minimum\": 0, \"required\": true },"
                        "\"total\": { \"type\": \"integer\", \"minimum\": 0, \"required\": true }"
                    "}"
                "},"
                "\"shares\": { \"type\": \"array\", \"id\": \"Files.Items\","
                    "\"items\": {"
                        "\"type\": \"object\","
                        "\"properties\": {"
                            "\"file\": { \"type\": \"string\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"Files.Download\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"FileDownload\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"path\", \"type\": \"string\", \"required\": true }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"path\": { \"type\": \"string\", \"required\": true }"
            "}"
        "}"
    "},"
    "\"Files.GetDirectory\": {"
        "\"type\": \"method\","
        "\"description\": \"\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"directory\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"media\", \"$ref\": \"Files.Media\", \"default\": \"files\" },"
            "{ \"name\": \"fields\", \"$ref\": \"List.Fields.All\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"files\": { \"type\": \"array\", \"id\": \"Files.Items\","
                    "\"items\": { \"type\": \"object\","
                        "\"properties\": {"
                            "\"file\": { \"type\": \"string\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"filetype\": { \"type\": \"string\", \"enum\": [ \"file\", \"directory\" ], \"required\": true }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"AudioLibrary.GetArtists\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all artists\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"genreid\", \"id\": \"Library.Id\", \"type\": \"integer\", \"default\": -1, \"minimum\": 1 },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"instrument\", \"style\", \"mood\", \"born\", \"formed\","
                                 "\"description\", \"genre\", \"died\", \"disbanded\","
                                 "\"yearsactive\", \"musicbrainzartistid\", \"fanart\","
                                 "\"thumbnail\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"artists\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\","
                        "\"properties\": {"
                            "\"artistid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"artist\": { \"type\": \"string\", \"required\": true },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"instrument\": { \"type\": \"string\" },"
                            "\"style\": { \"type\": \"string\" },"
                            "\"mood\": { \"type\": \"string\" },"
                            "\"born\": { \"type\": \"string\" },"
                            "\"formed\": { \"type\": \"string\" },"
                            "\"description\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"died\": { \"type\": \"string\" },"
                            "\"disbanded\": { \"type\": \"string\" },"
                            "\"yearsactive\": { \"type\": \"string\" },"
                            "\"musicbrainzartistid\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"AudioLibrary.GetAlbums\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all albums from specified artist or genre\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"artistid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"genreid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.Album\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"title\", \"description\", \"artist\", \"genre\","
                                 "\"theme\", \"mood\", \"style\", \"type\", \"label\"," 
                                 "\"rating\", \"year\", \"musicbrainzalbumid\","
                                 "\"musicbrainzalbumartistid\", \"fanart\", \"thumbnail\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"albums\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Audio.AlbumDetails\","
                        "\"properties\": {"
                            "\"albumid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"description\": { \"type\": \"string\" },"
                            "\"artist\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"theme\": { \"type\": \"string\" },"
                            "\"mood\": { \"type\": \"string\" },"
                            "\"style\": { \"type\": \"string\" },"
                            "\"type\": { \"type\": \"string\" },"
                            "\"album_label\": { \"type\": \"string\" },"
                            "\"rating\": { \"type\": \"integer\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"musicbrainzalbumid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumartistid\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"AudioLibrary.GetAlbumDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific album\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"albumid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Album\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"albumdetails\": { \"$ref\": \"Audio.AlbumDetails\" }"
            "}"
        "}"
    "},"
    "\"AudioLibrary.GetSongs\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all songs from specified album, artist or genre\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"artistid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"albumid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"genreid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.Song\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"title\", \"artist\", \"albumartist\", \"genre\", \"year\","
                                "\"rating\", \"album\", \"track\", \"duration\", \"comment\","
                                "\"lyrics\", \"musicbrainztrackid\", \"musicbrainzartistid\","
                                "\"musicbrainzalbumid\", \"musicbrainzalbumartistid\","
                                "\"playcount\", \"fanart\", \"thumbnail\", \"file\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"songs\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Audio.SongDetails\","
                        "\"properties\": {"
                            "\"songid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"artist\": { \"type\": \"string\" },"
                            "\"albumartist\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"rating\": { \"type\": \"integer\" },"
                            "\"album\": { \"type\": \"string\" },"
                            "\"track\": { \"type\": \"integer\" },"
                            "\"duration\": { \"type\": \"integer\" },"
                            "\"comment\": { \"type\": \"string\" },"
                            "\"lyrics\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"musicbrainztrackid\": { \"type\": \"string\" },"
                            "\"musicbrainzartistid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumid\": { \"type\": \"string\" },"
                            "\"musicbrainzalbumartistid\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"AudioLibrary.GetSongDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific song\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"songid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Song\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"songdetails\": { \"$ref\": \"Audio.SongDetails\" }"
            "}"
        "}"
    "},"
    "\"AudioLibrary.GetGenres\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all genres\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"genres\": { \"type\": \"array\", \"id\": \"Library.Genres\","
                    "\"items\": { \"type\": \"object\","
                        "\"properties\": {"
                            "\"genreid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"genre\": { \"type\": \"string\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"thumbnail\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"AudioLibrary.ScanForContent\": {"
        "\"type\": \"method\","
        "\"description\": \"Scans the audio sources for new library items\","
        "\"transport\": \"Response\","
        "\"permission\": \"ScanLibrary\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"VideoLibrary.GetMovies\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all movies\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.Movie\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"description\": \"Requesting the cast, set and/or showlink field will result in increased response times\","
                    "\"enum\": [ \"title\", \"genre\", \"year\", \"rating\", \"director\", \"trailer\","
                                "\"tagline\", \"plot\", \"plotoutline\", \"originaltitle\", \"lastplayed\","
                                "\"playcount\", \"writer\", \"studio\", \"mpaa\", \"cast\", \"country\","
                                "\"imdbnumber\", \"premiered\", \"productioncode\", \"runtime\", \"set\","
                                "\"showlink\", \"streamDetails\", \"top250\", \"votes\", \"writingcredits\","
                                "\"fanart\", \"thumbnail\", \"file\", \"sorttitle\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"movies\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Library.Details.Movie\","
                        "\"properties\": {"
                            "\"movieid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"rating\": { \"type\": \"number\" },"
                            "\"director\": { \"type\": \"string\" },"
                            "\"trailer\": { \"type\": \"string\" },"
                            "\"tagline\": { \"type\": \"string\" },"
                            "\"plot\": { \"type\": \"string\" },"
                            "\"plotoutline\": { \"type\": \"string\" },"
                            "\"originaltitle\": { \"type\": \"string\" },"
                            "\"sorttitle\": { \"type\": \"string\" },"
                            "\"lastplayed\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"writer\": { \"type\": \"string\" },"
                            "\"studio\": { \"type\": \"string\" },"
                            "\"mpaa\": { \"type\": \"string\" },"
                            "\"cast\": { \"type\": \"array\", \"id\": \"Video.Cast\","
                                "\"items\": {"
                                    "\"name\": { \"type\": \"string\", \"required\": true },"
                                    "\"role\": { \"type\": \"string\", \"required\": true }"
                                "}"
                            "},"
                            "\"country\": { \"type\": \"string\" },"
                            "\"imdbnumber\": { \"type\": \"string\" },"
                            "\"premiered\": { \"type\": \"string\" },"
                            "\"productioncode\": { \"type\": \"string\" },"
                            "\"runtime\": { \"type\": \"string\" },"
                            "\"set\": { \"type\": \"string\" },"
                            "\"showlink\": { \"type\": \"string\" },"
                            "\"streamDetails\": { \"type\": \"object\", \"id\": \"Video.Streams\","
                                "\"properties\": {"
                                    "\"audio\": { \"type\": \"array\", \"minItems\": 1,"
                                        "\"items\": {"
                                            "\"properties\": {"
                                                "\"codec\": { \"type\": \"string\" },"
                                                "\"language\": { \"type\": \"string\" },"
                                                "\"channels\": { \"type\": \"integer\" }"
                                            "}"
                                        "}"
                                    "},"
                                    "\"video\": { \"type\": \"array\", \"minItems\": 1,"
                                        "\"items\": {"
                                            "\"properties\": {"
                                                "\"codec\": { \"type\": \"string\" },"
                                                "\"aspect\": { \"type\": \"number\" },"
                                                "\"width\": { \"type\": \"integer\" },"
                                                "\"height\": { \"type\": \"integer\" },"
                                                "\"duration\": { \"type\": \"integer\" }"
                                            "}"
                                        "}"
                                    "},"
                                    "\"subtitle\": { \"type\": \"array\", \"minItems\": 1,"
                                        "\"items\": {"
                                            "\"properties\": {"
                                                "\"language\": { \"type\": \"string\" }"
                                            "}"
                                        "}"
                                    "}"
                                "}"
                            "},"
                            "\"top250\": { \"type\": \"integer\" },"
                            "\"votes\": { \"type\": \"string\" },"
                            "\"writingcredits\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetMovieDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific movie\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"movieid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Movie\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"moviedetails\": { \"$ref\": \"Library.Details.Movie\" }"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetMovieSets\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all movie sets\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.MovieSet\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"title\", \"playcount\", \"fanart\", \"thumbnail\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"sets\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Library.Details.MovieSet\","
                        "\"properties\": {"
                            "\"setid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetMovieSetDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific movie set\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"setid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.MovieSet\" },"
            "{ \"name\": \"movies\", \"type\": \"object\","
                "\"properties\": {"
                    "\"fields\": { \"$ref\": \"Library.Fields.Movie\" },"
                    "\"limits\": { \"$ref\": \"List.Limits\" },"
                    "\"sort\": { \"$ref\": \"List.Sort\" }"
                "}"
            "}"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"setdetails\": { \"type\": \"object\", \"id\": \"Library.Details.MovieSet\","
                    "\"properties\": {"
                        "\"setid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                        "\"label\": { \"type\": \"string\", \"required\": true },"
                        "\"fanart\": { \"type\": \"string\" },"
                        "\"thumbnail\": { \"type\": \"string\" },"
                        "\"title\": { \"type\": \"string\" },"
                        "\"playcount\": { \"type\": \"integer\" },"
                        "\"movies\": { \"type\": \"array\","
                          "\"items\": { \"$ref\": \"Library.Details.Movie\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetTVShows\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all tv shows\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.TVShow\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"description\": \"Requesting the cast field will result in increased response times\","
                    "\"enum\": [ \"title\", \"genre\", \"year\", \"rating\", \"plot\","
                               "\"studio\", \"mpaa\", \"cast\", \"playcount\", \"episode\","
                               "\"imdbnumber\", \"premiered\", \"votes\", \"lastplayed\","
                               "\"fanart\", \"thumbnail\", \"file\", \"originaltitle\","
                               "\"sorttitle\", \"episodeguide\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"tvshows\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Library.Details.TVShow\","
                        "\"properties\": {"
                            "\"tvshowid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"rating\": { \"type\": \"number\" },"
                            "\"plot\": { \"type\": \"string\" },"
                            "\"originaltitle\": { \"type\": \"string\" },"
                            "\"sorttitle\": { \"type\": \"string\" },"
                            "\"studio\": { \"type\": \"string\" },"
                            "\"mpaa\": { \"type\": \"string\" },"
                            "\"cast\": { \"$ref\": \"Video.Cast\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"episode\": { \"type\": \"integer\" },"
                            "\"imdbnumber\": { \"type\": \"string\" },"
                            "\"premiered\": { \"type\": \"string\" },"
                            "\"votes\": { \"type\": \"string\" },"
                            "\"episodeguide\": { \"type\": \"string\" },"
                            "\"lastplayed\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetTVShowDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific tv show\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"tvshowid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.TVShow\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"tvshowdetails\": { \"$ref\": \"Library.Details.TVShow\" }"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetSeasons\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all tv seasons\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"tvshowid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.Season\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"season\", \"showtitle\", \"playcount\", \"episode\", \"fanart\", \"thumbnail\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"seasons\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Library.Details.Season\","
                        "\"properties\": {"
                            "\"season\": { \"type\": \"integer\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"showtitle\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"episode\": { \"type\": \"integer\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetEpisodes\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all tv show episodes\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"tvshowid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"season\", \"type\": \"Integer\", \"required\": true, \"minimum\": 0 },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.Episode\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"description\": \"Requesting the cast field will result in increased response times\","
                    "\"enum\": [ \"title\", \"plot\", \"votes\", \"rating\", \"writingcredits\","
                              "\"firstaired\", \"playcount\", \"runtime\", \"director\","
                              "\"productioncode\", \"season\", \"episode\", \"originaltitle\","
                              "\"showtitle\", \"cast\", \"streamDetails\", \"lastplayed\", \"fanart\","
                              "\"thumbnail\", \"file\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"episodes\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Library.Details.Episode\","
                        "\"properties\": {"
                            "\"episodeid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"plot\": { \"type\": \"string\" },"
                            "\"votes\": { \"type\": \"string\" },"
                            "\"rating\": { \"type\": \"number\" },"
                            "\"writingcredits\": { \"type\": \"string\" },"
                            "\"firstaired\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"runtime\": { \"type\": \"string\" },"
                            "\"director\": { \"type\": \"string\" },"
                            "\"productioncode\": { \"type\": \"string\" },"
                            "\"season\": { \"type\": \"integer\" },"
                            "\"episode\": { \"type\": \"integer\" },"
                            "\"originaltitle\": { \"type\": \"string\" },"
                            "\"showtitle\": { \"type\": \"string\" },"
                            "\"cast\": { \"$ref\": \"Video.Cast\" },"
                            "\"streamDetails\": { \"$ref\": \"Video.Streams\" },"
                            "\"lastplayed\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetEpisodeDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific tv show episode\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"episodeid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Episode\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"episodedetails\": { \"$ref\": \"Library.Details.Episode\" }"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetMusicVideos\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all music videos\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"artistid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"albumid\", \"$ref\": \"Library.Id\" },"
            "{ \"name\": \"fields\", \"type\": \"array\", \"id\": \"Library.Fields.MusicVideo\", \"uniqueItems\": true,"
                "\"items\": { \"type\": \"string\","
                    "\"enum\": [ \"title\", \"playcount\", \"runtime\", \"director\","
                                "\"studio\", \"year\", \"plot\", \"album\", \"artist\","
                                "\"genre\", \"track\", \"streamDetails\", \"lastplayed\","
                                "\"fanart\", \"thumbnail\", \"file\" ]"
                "}"
            "},"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"musicvideos\": { \"type\": \"array\","
                    "\"items\": { \"type\": \"object\", \"id\": \"Library.Details.MusicVideo\","
                        "\"properties\": {"
                            "\"musicvideoid\": { \"$ref\": \"Library.Id\", \"required\": true },"
                            "\"label\": { \"type\": \"string\", \"required\": true },"
                            "\"file\": { \"type\": \"string\" },"
                            "\"fanart\": { \"type\": \"string\" },"
                            "\"thumbnail\": { \"type\": \"string\" },"
                            "\"title\": { \"type\": \"string\" },"
                            "\"playcount\": { \"type\": \"integer\" },"
                            "\"runtime\": { \"type\": \"string\" },"
                            "\"director\": { \"type\": \"string\" },"
                            "\"studio\": { \"type\": \"string\" },"
                            "\"year\": { \"type\": \"integer\" },"
                            "\"plot\": { \"type\": \"string\" },"
                            "\"album\": { \"type\": \"string\" },"
                            "\"artist\": { \"type\": \"string\" },"
                            "\"genre\": { \"type\": \"string\" },"
                            "\"track\": { \"type\": \"integer\" },"
                            "\"streamDetails\": { \"$ref\": \"Video.Streams\" },"
                            "\"lastplayed\": { \"type\": \"string\" }"
                        "}"
                    "}"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetMusicVideoDetails\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve details about a specific music video\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"musicvideoid\", \"$ref\": \"Library.Id\", \"required\": true },"
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.MusicVideo\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"musicvideodetails\": { \"$ref\": \"Library.Details.MusicVideo\" }"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetRecentlyAddedMovies\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all recently added movies\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Movie\" },"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"movies\": { \"type\": \"array\","
                    "\"items\": { \"$ref\": \"Library.Details.Movie\" }"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetRecentlyAddedEpisodes\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all recently added tv episodes\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.Episode\" },"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"episodes\": { \"type\": \"array\","
                    "\"items\": { \"$ref\": \"Library.Details.Episode\" }"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.GetRecentlyAddedMusicVideos\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve all recently added music videos\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"fields\", \"$ref\": \"Library.Fields.MusicVideo\" },"
            "{ \"name\": \"limits\", \"$ref\": \"List.Limits\" },"
            "{ \"name\": \"sort\", \"$ref\": \"List.Sort\" }"
        "],"
        "\"returns\": { \"type\": \"object\","
            "\"properties\": {"
                "\"limits\": { \"$ref\": \"List.LimitsReturned\", \"required\": true },"
                "\"musicvideos\": { \"type\": \"array\","
                    "\"items\": { \"$ref\": \"Library.Details.MusicVideo\" }"
                "}"
            "}"
        "}"
    "},"
    "\"VideoLibrary.ScanForContent\": {"
        "\"type\": \"method\","
        "\"description\": \"Scans the video sources for new library items\","
        "\"transport\": \"Response\","
        "\"permission\": \"ScanLibrary\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Shutdown\": {"
        "\"type\": \"method\","
        "\"description\": \"Shuts the system running XBMC down\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Suspend\": {"
        "\"type\": \"method\","
        "\"description\": \"Suspends the system running XBMC\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Hibernate\": {"
        "\"type\": \"method\","
        "\"description\": \"Puts the system running XBMC into hibernate mode\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.Reboot\": {"
        "\"type\": \"method\","
        "\"description\": \"Reboots the system running XBMC\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"System.GetInfoLabels\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve info labels about the system\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"labels\", \"type\": \"array\", \"required\": true, \"items\": { \"type\": \"string\" }, \"minItems\": 1, \"description\": \"See http://wiki.xbmc.org/index.php?title=InfoLabels for a list of possible info labels\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"description\": \"List of key-value pairs of the retrieved info labels\""
        "}"
    "},"
    "\"System.GetInfoBooleans\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve info booleans about the system\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": ["
            "{ \"name\": \"booleans\", \"type\": \"array\", \"required\": true, \"items\": { \"type\": \"string\" }, \"minItems\": 1, \"description\": \"\" }"
        "],"
        "\"returns\": {"
            "\"type\": \"object\","
            "\"description\": \"List of key-value pairs of the retrieved info booleans\""
        "}"
    "},"
    "\"Input.Left\": {"
        "\"type\": \"method\","
        "\"description\": \"Navigate left in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Input.Right\": {"
        "\"type\": \"method\","
        "\"description\": \"Navigate right in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Input.Down\": {"
        "\"type\": \"method\","
        "\"description\": \"Navigate down in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Input.Up\": {"
        "\"type\": \"method\","
        "\"description\": \"Navigate up in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Input.Select\": {"
        "\"type\": \"method\","
        "\"description\": \"Select current item in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Input.Back\": {"
        "\"type\": \"method\","
        "\"description\": \"Goes back in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"Input.Home\": {"
        "\"type\": \"method\","
        "\"description\": \"Goes to home window in GUI\","
        "\"transport\": \"Response\","
        "\"permission\": \"Navigate\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.GetVolume\": {"
        "\"type\": \"method\","
        "\"description\": \"Retrieve the current volume\","
        "\"transport\": \"Response\","
        "\"permission\": \"ReadData\","
        "\"params\": [],"
        "\"returns\": \"integer\""
    "},"
    "\"XBMC.SetVolume\": {"
        "\"type\": \"method\","
        "\"description\": \"Set the current volume\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"value\", \"type\": \"integer\", \"minimum\": 0, \"maximum\": 100, \"required\": true }"
        "],"
        "\"returns\": \"integer\""
    "},"
    "\"XBMC.ToggleMute\": {"
        "\"type\": \"method\","
        "\"description\": \"Toggle mute/unmute\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": [],"
        "\"returns\": { \"type\": \"integer\", \"description\": \"New volume\" }"
    "},"
    "\"XBMC.Play\": {"
        "\"type\": \"method\","
        "\"description\": \"Starts playback of the given file\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"file\", \"type\": \"string\", \"required\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.StartSlideshow\": {"
        "\"type\": \"method\","
        "\"description\": \"Starts slideshow with the images from the given directory\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPlayback\","
        "\"params\": ["
            "{ \"name\": \"directory\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"random\", \"type\": \"boolean\", \"default\": true },"
            "{ \"name\": \"recursive\", \"type\": \"boolean\", \"default\": true }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.Log\": {"
        "\"type\": \"method\","
        "\"description\": \"Logs a line in the xbmc.log\","
        "\"transport\": \"Response\","
        "\"permission\": \"Logging\","
        "\"params\": ["
            "{ \"name\": \"message\", \"type\": \"string\", \"required\": true },"
            "{ \"name\": \"level\", \"type\": \"string\", \"default\": \"debug\", \"enum\": [ \"debug\", \"info\", \"notice\", \"warning\", \"error\", \" severe\", \"fatal\", \"none\" ] }"
        "],"
        "\"returns\": \"string\""
    "},"
    "\"XBMC.Quit\": {"
        "\"type\": \"method\","
        "\"description\": \"Quit XBMC\","
        "\"transport\": \"Response\","
        "\"permission\": \"ControlPower\","
        "\"params\": [],"
        "\"returns\": \"string\""
    "}"
  "}";

  const char* const JSON_NOTIFICATION_DESCRIPTION =
  "{"

  "}";
}
