set(PLATFORM_REQUIRED_DEPS D3DX11Effects Detours)
# Needed for date library on Windows
list(APPEND PLATFORM_REQUIRED_DEPS UnicodeCLDR)
set(APP_RENDER_SYSTEM dx11)
list(APPEND PLATFORM_DEFINES -DNTDDI_VERSION=NTDDI_WINBLUE -D_WIN32_WINNT=_WIN32_WINNT_WINBLUE)

set(${CORE_PLATFORM_NAME_LC}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
