#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUPDATENOTIFIER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Disabling update-notifier"

# live-initramfs script

# For GNOME, we divert away apt-check to avoid a regular 'apt-get update'
# equivalent in the live session. We want to run update-notifier for crash
# report handling.
chroot /root dpkg-divert --add --rename --quiet \
	/usr/lib/update-notifier/apt-check

if [ -e /root/usr/lib/update-notifier/apt-check ]
then
	ln -s /bin/true /root/usr/lib/update-notifier/apt-check
fi

# For KDE, adept_notifier's only useful function at the moment is an
# 'apt-get update' equivalent, so we disable it entirely.
rm -f /root/usr/share/autostart/adept_notifier_auto.desktop

log_end_msg
