#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if [ -n "${NOJOCKEY}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Disabling jockey driver check"

rm -f /root/etc/xdg/autostart/jockey*.desktop

log_end_msg
