%module KodiAPI_GUI

%{
#include "General.hpp"
#include "ControlButton.hpp"
#include "ControlEdit.hpp"
#include "ControlFadeLabel.hpp"
#include "ControlImage.hpp"
#include "ControlLabel.hpp"
#include "ControlProgress.hpp"
#include "ControlRadioButton.hpp"
#include "ControlRendering.hpp"
#include "ControlSettingsSlider.hpp"
#include "ControlSlider.hpp"
#include "ControlSpin.hpp"
#include "ControlTextBox.hpp"
#include "definitions_gui.hpp"
#include "DialogExtendedProgress.hpp"
#include "DialogFileBrowser.hpp"
#include "DialogKeyboard.hpp"
#include "DialogNumeric.hpp"
#include "DialogOK.hpp"
#include "DialogProgress.hpp"
#include "DialogSelect.hpp"
#include "DialogTextViewer.hpp"
#include "DialogYesNo.hpp"
#include "ListItem.hpp"
#include "Window.hpp"

using namespace V2:KodiAPI::GUI;
using namespace V2:KodiAPI;

%}

%include "General.hpp"
%include "ControlButton.hpp"
%include "ControlEdit.hpp"
%include "ControlFadeLabel.hpp"
%include "ControlImage.hpp"
%include "ControlLabel.hpp"
%include "ControlProgress.hpp"
%include "ControlRadioButton.hpp"
%include "ControlRendering.hpp"
%include "ControlSettingsSlider.hpp"
%include "ControlSlider.hpp"
%include "ControlSpin.hpp"
%include "ControlTextBox.hpp"
%include "definitions_gui.hpp"
%include "DialogExtendedProgress.hpp"
%include "DialogFileBrowser.hpp"
%include "DialogKeyboard.hpp"
%include "DialogNumeric.hpp"
%include "DialogOK.hpp"
%include "DialogProgress.hpp"
%include "DialogSelect.hpp"
%include "DialogTextViewer.hpp"
%include "DialogYesNo.hpp"
%include "ListItem.hpp"
%include "Window.hpp"
