INCLUDES=-I. -I../ -I../linux -I../../guilib

SRCS=cddb.cpp cdioSupport.cpp Directory.cpp DirectoryCache.cpp DirectoryHistory.cpp DirectoryTuxBox.cpp DllLibCurl.cpp FactoryDirectory.cpp FactoryFileDirectory.cpp File.cpp FileCurl.cpp FileFactory.cpp FileFileReader.cpp FileHD.cpp FileLastFM.cpp FileMusicDatabase.cpp FileRar.cpp FileShoutcast.cpp FileTuxBox.cpp FileZip.cpp FTPDirectory.cpp FTPParse.cpp HDDirectory.cpp HDHomeRun.cpp IDirectory.cpp IFile.cpp iso9660.cpp LastFMDirectory.cpp MultiPathDirectory.cpp MusicDatabaseDirectory.cpp MusicSearchDirectory.cpp PlaylistDirectory.cpp PlaylistFileDirectory.cpp RarDirectory.cpp RarManager.cpp ShoutcastDirectory.cpp ShoutcastRipFile.cpp SmartPlaylistDirectory.cpp StackDirectory.cpp VideoDatabaseDirectory.cpp VirtualDirectory.cpp VirtualPathDirectory.cpp ZipDirectory.cpp ZipManager.cpp

LIB=filesystem.a

include ../../Makefile.include
-include Makefile.depend
