#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libgrabbag
INCLUDES = -I$(topdir)/include

SRCS_C = \
	cuesheet.c \
	file.c \
	picture.c \
	replaygain.c \
	seektable.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
