INCLUDES+=-I/home/xbmc/progs/src/xbmc/xbmc/cores/VideoPlayer

SRCS  = ProcessInfo.cpp

LIB = Process.a

include /home/xbmc/progs/src/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
