INCLUDES=-I. -I.. -I../../guilib -I../linux -I../utils -I../FileSystem -I../lib/libportaudio

.SUFFIXES : .m .mm

SRCS = \
	SDLMain.mm \
	XBMCHelper.m \
	CocoaInterface.mm \
	CoreAudio.cpp \
	CoreAudioSoundManager.cpp \
	CocoaPowerSyscall.cpp \
	OSXGNUReplacements.c \
	ZeroconfOSX.mm \
	
LIB=osx.a

include ../../Makefile.include
