INCLUDES=-I. -I.. -I../../guilib -I../linux -I../utils -I../FileSystem -I../lib/libportaudio

SRCS = \
	XBMCMain.m \
	XBMCHelper.m \
	CocoaUtils.m \
	OSXGNUReplacements.c \
	getdelim.c CPortAudio.cpp
	
LIB=osx.a

include ../../Makefile.include
