#  test_libFLAC - Unit tester for libFLAC
#  Copyright (C) 2000,2001,2002,2003,2004,2005,2006,2007  Josh Coalson
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

#
# GNU makefile
#

topdir = ../..
libdir = $(topdir)/obj/$(BUILD)/lib

PROGRAM_NAME = test_libFLAC

INCLUDES = -I../libFLAC/include -I$(topdir)/include

ifeq ($(DARWIN_BUILD),yes)
EXPLICIT_LIBS = $(libdir)/libgrabbag.a $(libdir)/libreplaygain_analysis.a $(libdir)/libtest_libs_common.a $(libdir)/libFLAC.a $(OGG_LIB_DIR)/libogg.a -lm
else
LIBS = -lgrabbag -lreplaygain_analysis -ltest_libs_common -lFLAC -L$(OGG_LIB_DIR) -logg -lm
endif

SRCS_C = \
	bitwriter.c \
	decoders.c \
	encoders.c \
	format.c \
	main.c \
	metadata.c \
	metadata_manip.c \
	metadata_object.c

include $(topdir)/build/exe.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
