set(ARCH_DEFINES -D_LINUX -DTARGET_POSIX -DTARGET_FREEBSD)
set(SYSTEM_DEFINES -D__STDC_CONSTANT_MACROS -D_FILE_DEFINED
                   -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64)
set(PLATFORM_DIR linux)
set(SYSTEM_LDFLAGS -L/usr/local/lib)

if(ARCH STREQUAL x86_64)
  set(ARCH x86_64-freebsd)
elseif(ARCH MATCHES "i.86" OR ARCH STREQUAL "x86")
  set(ARCH x86-freebsd)
else()
  message(WARNING "unknown ARCH: ${ARCH}")
endif()
