#
#	Makefile for the AppWeb samples
#
#	Copyright (c) Mbedthis Software LLC, 2003-2007. All Rights Reserved.
#
#	This makefile is for use on development systems only and is not part of
#	the released product.
# 

include 	make.dep 

ifeq		($(BLD_FEATURE_SAMPLES),1)
PRE_DIRS	= C C++
endif

## Local variables:
## tab-width: 4
## End:
## vim: sw=4 ts=4
