#!/bin/sh
### BEGIN INIT INFO
# Provides:          xbmc
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop XBMC Live
# Description: XBMC Live is the XBMC media center software bundled with an
#              embedded operating-system, for that set-top-box felling.
### END INIT INFO

# Do NOT "set -e"

#/etc/init.d/xbmc

. /lib/lsb/init-functions

get_opt() {
	echo "$@" | cut -d "=" -f 2
}

CMDLINE=$(cat /proc/cmdline)

#Process command line options
XBMC_PARAMS=""
for i in ${CMDLINE}; do
	case "${i}" in
	xbmc\=*)
		XBMC_PARAMS=$(get_opt $i)
		;;
	boot\=*)
		SRCMEDIA=$(echo "$i" | cut -d "=" -f 2)
		;;
	esac
done

XBMC_BOOTTORAM="$( echo $XBMC_PARAMS | grep "boottoram" )"

if [ "$XBMC_BOOTTORAM" != "" ]; then
	eject /dev/scd0 &> /dev/null
	eject /dev/scd1 &> /dev/null
	eject /dev/scd2 &> /dev/null
fi

do_start()
{
	log_action_begin_msg "Configuring system and starting XBMC"
	INSTALL="$( echo $XBMC_PARAMS | grep "install" )"
	if [ "$INSTALL" != "" ]; then
		# if usplash is runing, make sure to stop it now, yes "start" kills it.
		if pidof usplash > /dev/null; then
			DO_NOT_SWITCH_VT=yes /etc/init.d/usplash start
		fi
		su -c "/usr/bin/installXBMC.py" -l 
	else
		# Generates valid xorg.conf for proprietary drivers if missing
		XBMC_NOGENXCONF="$( echo $XBMC_PARAMS | grep "nogenxconf" )"
		if [ ! -e /etc/X11/xorg.conf ] && [ "$XBMC_NOGENXCONF" == "" ]; then
			NVIDIA="$(lspci -nn | grep 0300 | grep 10de)"
			if [ "$NVIDIA" == "" ]; then
				AMD="$(lspci -nn | grep 0300 | grep 1002)"
				if [ "$AMD" != "" ]; then
					# run aticonfig
					echo "Generating xorg.conf for ATI..."
					/usr/bin/aticonfig --initial --sync-vsync=on -f
				fi
			else
				# run nvidia-xconfig
				echo "Generating xorg.conf for NVIDIA..."
				/usr/bin/nvidia-xconfig -s --no-logo --force-generate
			fi
		fi

		RUNX="$(grep "splash" /proc/cmdline)"
		if [ "$RUNX" == "" ]; then
		        echo "Not starting X."

			if [ -f /home/xbmc/.xsession ]; then
				rm /home/xbmc/.xsession
			fi
		else
			NOMOUNT="$( echo $XBMC_PARAMS | grep "nodiskmount" )"
			if [ "$NOMOUNT" == "" ]; then
				/usr/bin/diskmounter &
			fi

			# Redirect XBMC home folder and logfile to usb flash
			if [ "$SRCMEDIA" == "usb" ]; then
				NOREDIR="$( echo $XBMC_PARAMS | grep "noredir" )"
				if [ "$NOREDIR" == "" ]; then
					echo "Redirect XBMC home folder and logfile to usb flash..."

					# Relies on init scripts to mount boot device on a specified directory
					BOOTMEDIAMOUNTPOINT=`mount | grep bootMedia | cut -f 3 -d " "`

					if [ ! -d $BOOTMEDIAMOUNTPOINT/dotXBMC ]; then
						mkdir $BOOTMEDIAMOUNTPOINT/dotXBMC
					fi

					if [ ! -L /home/xbmc/.xbmc ]; then
						mv /home/xbmc/.xbmc /home/xbmc/.xbmc.previous
						ln -s $BOOTMEDIAMOUNTPOINT/dotXBMC /home/xbmc/.xbmc
					fi
				fi
			fi

			XBMC_SETVOLUME="$( echo $XBMC_PARAMS | grep "setvolume" )"
			if [ "$XBMC_SETVOLUME" != "" ]; then
				/usr/bin/setAlsaVolumes.py
			fi

			# if usplash is running, make sure to stop it now, yes "start" kills it.
			if pidof usplash > /dev/null; then
				DO_NOT_SWITCH_VT=yes /etc/init.d/usplash start
			fi
			/usr/bin/runXBMC.sh &
		fi
	fi
	log_action_end_msg 0
}

do_stop() {
	killall Xorg xbmc
}

case "$1" in
start)
	do_start
	;;
stop)
	do_stop
	;;
restart|force-reload)
	do_stop
	do_start
	;;
*)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0
