#!/bin/sh

# --remove-home
in-target deluser --quiet xbmc
in-target sed -i -e "/XBMC/d" /etc/sudoers

cat > /target/tmp/editPolkit.sh << 'EOF'
xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
sed -i -e "s/xbmc/$xbmcUser/" /etc/PolicyKit/PolicyKit.conf
EOF

# Modify /etc/PolicyKit/PolicyKit.conf
in-target sh /tmp/editPolkit.sh

rm /target/tmp/editPolkit.sh
