set(PLATFORM_REQUIRED_DEPS D3DX11Effects)
set(PLATFORM_OPTIONAL_DEPS_EXCLUDE CEC)
# Needed for date library on Windows
list(APPEND PLATFORM_REQUIRED_DEPS UnicodeCLDR)
set(APP_RENDER_SYSTEM dx11)

set(${CORE_PLATFORM_NAME_LC}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
