set(PLATFORM_REQUIRED_DEPS Effects11)
set(PLATFORM_REQUIRED_TOOLS EffectsCompiler)

list(APPEND PLATFORM_OPTIONAL_PACKAGES LibAACS LibBDPlus)

set(PLATFORM_OPTIONAL_DEPS_EXCLUDE CEC)
set(APP_RENDER_SYSTEM dx11)

set(${CORE_PLATFORM_NAME_LC}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
