set(PLATFORM_REQUIRED_DEPS Effects11)
set(PLATFORM_REQUIRED_TOOLS EffectsCompiler Msys)

list(APPEND PLATFORM_OPTIONAL_PACKAGES LibAACS LibBDPlus)

set(PLATFORM_OPTIONAL_DEPS_EXCLUDE CEC)
set(APP_RENDER_SYSTEM dx11)

set(${CORE_SYSTEM_NAME}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
