\input texinfo  @c -*-texinfo-*-
@finalout
@setfilename microhttpd-tutorial.info
@settitle A tutorial for GNU libmicrohttpd
@afourpaper

@set VERSION 0.4.0

@dircategory GNU Libraries
@direntry
* libmicrohttpdtutorial: (microhttpd).  A tutorial for GNU libmicrohttpd.
@end direntry

@titlepage
@title A Tutorial for GNU libmicrohttpd
@subtitle written for version @value{VERSION}
@author Sebastian Gerhardt (@email{sebgerhardt@@gmx.net})
@page
@vskip 0pt plus 1filll
@end titlepage

@verbatim
Copyright (c)  2008  Sebastian Gerhardt.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
Texts.  A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end verbatim

@contents

@ifnottex
@node Top
@top Top
@end ifnottex     

@menu
* Introduction::
* Hello browser example::
* Exploring requests::
* Response headers::
* Supporting basic authentication::
* Processing POST data::
* Improved processing of POST data::
* Adding a layer of security::
* Bibliography::
* License text::
* Example programs::
@end menu

@node Introduction
@chapter Introduction
@include chapters/introduction.inc

@node Hello browser example
@chapter Hello browser example
@include chapters/hellobrowser.inc

@node Exploring requests
@chapter Exploring requests
@include chapters/exploringrequests.inc

@node Response headers
@chapter Response headers
@include chapters/responseheaders.inc

@node Supporting basic authentication
@chapter Supporting basic authentication
@include chapters/basicauthentication.inc

@node Processing POST data
@chapter Processing POST data
@include chapters/processingpost.inc

@node Improved processing of POST data 
@chapter Improved processing of POST data 
@include chapters/largerpost.inc

@node Adding a layer of security
@chapter Adding a layer of security
@include chapters/tlsauthentication.inc

@node Bibliography
@appendix Bibliography
@include chapters/bibliography.inc

@node License text
@appendix GNU Free Documentation License
@include fdl-1.3.texi

@node Example programs
@appendix Example programs
@menu
* hellobrowser.c::
* logging.c::
* responseheaders.c::
* basicauthentication.c::
* simplepost.c::
* largepost.c::
* tlsauthentication.c::
@end menu

@node hellobrowser.c
@section hellobrowser.c
@smalldisplay
@verbatiminclude examples/hellobrowser.c
@end smalldisplay

@node logging.c
@section logging.c
@smalldisplay
@verbatiminclude examples/logging.c
@end smalldisplay

@node responseheaders.c
@section responseheaders.c
@smalldisplay
@verbatiminclude examples/responseheaders.c
@end smalldisplay

@node basicauthentication.c
@section basicauthentication.c
@smalldisplay
@verbatiminclude examples/basicauthentication.c
@end smalldisplay

@node simplepost.c
@section simplepost.c
@smalldisplay
@verbatiminclude examples/simplepost.c
@end smalldisplay

@node largepost.c
@section largepost.c
@smalldisplay
@verbatiminclude examples/largepost.c
@end smalldisplay

@node tlsauthentication.c
@section tlsauthentication.c
@smalldisplay
@verbatiminclude examples/tlsauthentication.c
@end smalldisplay

@bye
