SRCS=GUIViewStatePrograms.cpp \
     GUIWindowPrograms.cpp \
     ProgramDatabase.cpp \
     Shortcut.cpp \
     
LIB=programs.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
