INCLUDES=-I. -I../../ -I../../linux -I../../../guilib -I.
SRCS=XBPython.cpp XBPythonDll.cpp XBPyThread.cpp XBPythonDllFuncs.S

LIB=python.a

include ../../../Makefile.include
-include Makefile.depend

