INCLUDES=-I. -I../ -Iffmpeg -I../linux -I../../guilib -I../utils

SRCS=DummyVideoPlayer.cpp PlayerCoreFactory.cpp ssrc.cpp dlgcache.cpp

LIB=cores.a

include ../../Makefile.include
-include Makefile.depend
