#!/bin/bash
# Live USB filesystem mounting			-*- shell-script -*-

mountroot ()
{
	CFG_FILE=/etc/moblin-initramfs.cfg
	QUIET="$(grep "quiet" /proc/cmdline)"

	if [ -f ${CFG_FILE} ]
	then
		. ${CFG_FILE}
	else
		echo "Did not find config file: ${CFG_FILE}"
		sleep 5
	fi

	mkdir -p /container
	mkdir -p /squashmnt1
	mkdir -p /squashmnt2
	mkdir -p /squashmnt3
	mkdir -p /persistmnt

	# Find the USB flash drive	
	if [ "$ROOT" != "" ]; then
		if [ "$QUIET_KPARAM" == "" ]; then
			echo "will mount root from ${ROOT}"
		fi

		mount -o rw ${ROOT} /container 2> /dev/null
		while [ ! -e "/container/rootfs.img" ]; do
			/bin/sleep 0.5
			mount -o rw ${ROOT} /container 2> /dev/null
		done
	else
		while true
		do
			for device in 'sda' 'sdb' 'sdc' 'sdd'; do
				if [ "$QUIET_KPARAM" == "" ]; then
					echo "checking device /dev/${device} for installation source..."
				fi
				if [ -e /sys/block/${device}/removable ]; then
					if [ "$(cat /sys/block/${device}/removable)" = "1" ]; then
						if [ "$QUIET_KPARAM" == "" ]; then
							echo "Found Removable drive at /dev/${device}"
						fi

						mount /dev/${device}1  /mnt
						if [ -f /mnt/rootfs.img ] ; then
							if [ "$QUIET_KPARAM" == "" ]; then
								echo "Found Boot drive at /dev/${device}1"
							fi
							found="yes"
						fi
						umount /dev/${device}1
						if [ "$found" = "yes" ]; then
							break;
						fi
						if [ "$QUIET_KPARAM" == "" ]; then
							echo "/dev/${device}1 does not contain a rootfs"
						fi
					fi
				fi
			done
			if [ "$found" = "yes" ]; then
				break;
			fi
			if [ "$QUIET_KPARAM" == "" ]; then
				echo "Sleeping for 5 seconds"
			fi
			/bin/sleep 5
		done
		if [ "$QUIET_KPARAM" == "" ]; then
			echo "will mount root from /dev/${device}1"
		fi

		mount -o rw /dev/${device}1 /container 2> /dev/null
		while [ ! -e "/container/rootfs.img" ]; do
			/bin/sleep 0.5
			mount -o rw /dev/${device}1 /container 2> /dev/null
		done
	fi

	mount -o ro,loop -t squashfs /container/rootfs.img /squashmnt1

	if [ -f /container/xbmc.img ]; then
		mount -o ro,loop,noatime,nodiratime /container/xbmc.img /squashmnt2
	fi

	if [ -f /container/restrictedDrivers.img ]; then
		mount -o ro,loop,noatime,nodiratime /container/restrictedDrivers.img /squashmnt3
	fi

	if [ -f /container/ext3fs.img ]; then
		mount -o rw,loop,noatime,nodiratime /container/ext3fs.img /persistmnt
	else
		mount -t tmpfs -o noatime,nodiratime none /persistmnt
	fi

	mount -t unionfs -o dirs=/persistmnt=rw:/squashmnt3=ro:/squashmnt2=ro:/squashmnt1=ro none ${rootmnt}

	if [ -f /container/config/xorg.conf ]; then
		cp /container/config/xorg.conf ${rootmnt}/etc/X11
	fi

	if [ -f /container/config/lircd.conf ]; then
		cp /container/config/lircd.conf ${rootmnt}/etc/lirc
	fi

	if [ -f /container/config/hardware.conf ]; then
		cp /container/config/hardware.conf ${rootmnt}/etc/lirc
	fi

	if [ -f /container/config/lircrc ]; then
		cp /container/config/lircrc ${rootmnt}/etc/lirc
	fi

	if [ -f /container/install.sh ]; then
		log_begin_msg "Install Process will begin shortly..."
		maybe_break preinstall

		mkdir -p ${rootmnt}/tmp/install
		mount --bind /dev ${rootmnt}/dev
		mount --bind /sys ${rootmnt}/sys
		mount --bind /container ${rootmnt}/tmp/install
		cp /container/install.sh ${rootmnt}
		cp /container/install.cfg ${rootmnt}

		maybe_break install
		chroot ${rootmnt} /install.sh
	fi
}
