SRCS=GUIWindowMusicBase.cpp \
     GUIWindowMusicNav.cpp \
     GUIWindowMusicPlaylist.cpp \
     GUIWindowMusicPlaylistEditor.cpp \
     GUIWindowMusicSongs.cpp \
     GUIWindowVisualisation.cpp \

LIB=musicwindows.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
