SRCS=Addon.cpp \
     AddonCallbacks.cpp \
     AddonCallbacksAddon.cpp \
     AddonCallbacksAudioDSP.cpp \
     AddonCallbacksAudioEngine.cpp \
     AddonCallbacksCodec.cpp \
     AddonCallbacksGUI.cpp \
     AddonCallbacksPVR.cpp \
     AddonDatabase.cpp \
     AddonInstaller.cpp \
     AddonManager.cpp \
     AddonStatusHandler.cpp \
     AddonVersion.cpp \
     AudioEncoder.cpp \
     ContextMenuAddon.cpp \
     AudioDecoder.cpp \
     GUIDialogAddonInfo.cpp \
     GUIDialogAddonSettings.cpp \
     GUIViewStateAddonBrowser.cpp \
     GUIWindowAddonBrowser.cpp \
     ImageResource.cpp \
     LanguageResource.cpp \
     PluginSource.cpp \
     Repository.cpp \
     RepositoryUpdater.cpp \
     Scraper.cpp \
     ScreenSaver.cpp \
     Service.cpp \
     Skin.cpp \
     UISoundsResource.cpp \
     Visualisation.cpp \
     Webinterface.cpp \

LIB=addons.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

