SRCS=Addon.cpp \
     AddonDatabase.cpp \
     AddonManager.cpp \
     AddonStatusHandler.cpp \
     GUIDialogAddonInfo.cpp \
     GUIDialogAddonSettings.cpp \
     GUIViewStateAddonBrowser.cpp \
     GUIWindowAddonBrowser.cpp \
     PluginSource.cpp \
     Repository.cpp \
     Scraper.cpp \
     ScreenSaver.cpp \
     Service.cpp \
     Skin.cpp \
     Visualisation.cpp \

LIB=addons.a

include ../../Makefile.include

