INCLUDES=-I. -I../ -I../../xbmc -I../../xbmc/linux -I../../xbmc/utils

SRCS=SDLMouse.cpp SDLKeyboard.cpp LIRC.cpp SDLJoystick.cpp

LIB=gui_common.a

include ../../Makefile.include
-include Makefile.depend
