#ifdef HAS_CWIID

#ifndef WII_REMOTE_KEY_H
#define WII_REMOTE_KEY_H

#define WIIREMOTE_MIN_ID 435
#define WIIREMOTE_LEFT   WIIREMOTE_MIN_ID
#define WIIREMOTE_RIGHT  WIIREMOTE_MIN_ID + 1
#define WIIREMOTE_UP     WIIREMOTE_MIN_ID + 2
#define WIIREMOTE_DOWN   WIIREMOTE_MIN_ID + 3

#define WIIREMOTE_A      WIIREMOTE_MIN_ID + 4
#define WIIREMOTE_B      WIIREMOTE_MIN_ID + 5
#define WIIREMOTE_1      WIIREMOTE_MIN_ID + 6
#define WIIREMOTE_2      WIIREMOTE_MIN_ID + 7
#define WIIREMOTE_MINUS  WIIREMOTE_MIN_ID + 8
#define WIIREMOTE_PLUS   WIIREMOTE_MIN_ID + 9
#define WIIREMOTE_HOME   WIIREMOTE_MIN_ID + 10

#define WIIREMOTE_MAX_ID WIIREMOTE_HOME

#endif //WII_REMOTE_KEY_H

#endif
