# call MinGW32 Makefile with the dependencies libcurl is build.

all:
	$(MAKE) -f Makefile.m32 SSL=1 SSH2=1 ZLIB=1 IDN=1 SSPI=1

clean:
	$(MAKE) -f Makefile.m32 clean

distrib:
	$(MAKE) -f Makefile.m32 distrib


