TOP = ..\..\..
!INCLUDE ..\..\build\win32\make.msc

INCLUDES = -I ..\.. -I ..
DEFINES = -DHAVE_CONFIG_H -DHAVE_LONG_LONG_FORMAT

OBJECTS = \
	asnprintf.obj \
	printf.obj \
	printf-args.obj \
	printf-parse.obj \
	vasnprintf.obj

all : gnulib.lib

gnulib.lib : $(OBJECTS)
	lib -out:gnulib.lib $(OBJECTS)

