# C-Pluff examples build system for MSVC
# Copyright 2007 Johannes Lehtinen
# This file is free software; Johannes Lehtinen gives unlimited permission
# to copy, distribute and modify it.

SUBDIRS = plugins
TOP = ..

include ..\common.nmake

install-local: all-local
	if not exist $(bindir) mkdir $(bindir)
	copy /y cpfile.bat $(bindir)
