INCLUDES=-I. -I/opt/include/SDL -I.. -I../../guilib -I../linux -I../utils -I../FileSystem -I../lib/libportaudio
CFLAGS+=-fPIC

SRCS = \
	XBMCMain.m \
	XBMCHelper.m \
	CocoaUtils.m \
	
LIB=osx.a

include ../../Makefile.include
