#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -z "${HOOK}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Executing custom hook script"

# live-initramfs script

cd /root

if [ $(echo "${HOOK}" | grep file:\/\/) ]
then
       LOCALFILE=$(echo ${HOOK} | sed "s/file\:\/\///")
       cp ${LOCALFILE} /root
else
       chroot /root wget "${HOOK}"
fi

FILE="$(basename ${HOOK})"

chmod 0755 "${FILE}"
./"${FILE}"
rm -f "${FILE}"

log_end_msg
