SRCS=AddonEvent.cpp \
     AddonManagementEvent.cpp \
     BaseEvent.cpp \
     EventLog.cpp \
     MediaLibraryEvent.cpp \

LIB=events.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

