INCLUDES=-I. -I../ -I../linux -I../../guilib
SRCS=CDDARipper.cpp CDDAReader.cpp Encoder.cpp EncoderLame.cpp EncoderVorbis.cpp EncoderWav.cpp
OBJS=CDDARipper.o CDDAReader.o Encoder.o EncoderLame.o EncoderVorbis.o EncoderWav.o

LIB=cdrip.a

include ../../Makefile.include
-include Makefile.depend
