SRCS=DirectoryNode.cpp \
     DirectoryNodeOverview.cpp \
     DirectoryNodeYear.cpp \
     QueryParams.cpp \

LIB=picturedatabasedirectory.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
