/*
 *  Copyright (C) 2013-2018 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

// needed for CNetworkInterfaceLinux::GetHostMacAddress and taken from osx sdk
// net/if_types.h net/route.h netinet/if_ether.h
#include <netinet/in.h>

struct sockaddr_inarp
{
  u_char sin_len;
  u_char sin_family;
  u_short sin_port;
  struct in_addr sin_addr;
  struct in_addr sin_srcaddr;
  u_short sin_tos;
  u_short sin_other;
#define SIN_PROXY 1
};
#define RTF_LLINFO 0x400 /* generated by link layer (e.g. ARP) */
// --- END
