OBJS=crypt.o guideclient.o GuideParser.o httpclient.o httpfsclient.o interface.o md5.o netclient.o rtv.o sleep.o

%.o : %.c
	gcc -c $< -D_LINUX -D__unix__ -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4
%.o : %.cpp
	g++ -c $< -D_LINUX -D__unix__ -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4

librtv-osx.a : $(OBJS)
	ar rs $@  $(OBJS)

clean:
	$(RM) $(OBJS) librtv-osx.a
