// Automatically generated by the bundler tool from credits.rdf

#ifndef CREDITS_RES_H_
#define CREDITS_RES_H_

/*
 *      Copyright (C) 2005-2008 Team XBMC
 *      http://www.xbmc.org
 *
 *  This Program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *
 *  This Program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with XBMC; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */

#define credits_NUM_RESOURCES 7UL

#define credits_VShader_OFFSET 0UL
#define credits_PShader_OFFSET 364UL
#define credits_MeshInfo_OFFSET 616UL
#define credits_XBMCVBuffer_OFFSET 632UL
#define credits_XBMCIBuffer_OFFSET 644UL
#define credits_NormMap_OFFSET 656UL
#define credits_SpecEnvMap_OFFSET 676UL

#endif
