# C-Pluff examples build system for MSVC
# Copyright 2007 Johannes Lehtinen
# This file is free software; Johannes Lehtinen gives unlimited permission
# to copy, distribute and modify it.

TOP = ..\..\..

include ..\..\..\common.nmake

pluginsdir = $(bindir)\cpfile\plugins
plugindir = $(pluginsdir)\cext

install-local: all-local
	if not exist $(plugindir) mkdir $(plugindir)
	for %f in (plugin.xml) do copy /y %f $(plugindir)
