#!/bin/sh

#      Copyright (C) 2005-2008 Team XBMC
#      http://www.xbmc.org
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with XBMC; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html

# --remove-home
in-target deluser --quiet xbmc
in-target sed -i -e "/XBMC/d" /etc/sudoers

cat > /target/tmp/editPolkit.sh << 'EOF'
xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')
sed -i -e "s/xbmc/$xbmcUser/" /etc/PolicyKit/PolicyKit.conf
EOF

# Modify /etc/PolicyKit/PolicyKit.conf
in-target sh /tmp/editPolkit.sh

rm /target/tmp/editPolkit.sh
