macro(enable_arc)
  if(CMAKE_GENERATOR STREQUAL Xcode)
    set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC YES)
  else()
    add_options(OBJC ALL_BUILDS "-fobjc-arc")
    add_options(OBJCXX ALL_BUILDS "-fobjc-arc")
  endif()
endmacro()
