SRCS=AdvancedSettings.cpp \
     DisplaySettings.cpp \
     ISetting.cpp \
     MediaSettings.cpp \
     MediaSourceSettings.cpp \
     Setting.cpp \
     SettingAddon.cpp \
     SettingCategoryAccess.cpp \
     SettingConditions.cpp \
     SettingControl.cpp \
     SettingDependency.cpp \
     SettingLevel.cpp \
     SettingPath.cpp \
     SettingSection.cpp \
     Settings.cpp \
     SettingsManager.cpp \
     SettingUpdate.cpp \
     SettingVisibility.cpp \
     SkinSettings.cpp \
     VideoSettings.cpp \

LIB=settings.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
