# German messages for international release of SWAT.
# Copyright (C) 2001 Andreas Moroder
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat\n"
"POT-Creation-Date: 2003-10-06 05:30+0900\n"
"PO-Revision-Date: 2000-02-08 14:45+0100\n"
"Last-Translator: Andreas Moroder\n"
"Language-Team: (Samba Team) <samba-technical@samba.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../web/swat.c:117
#, c-format
msgid "ERROR: Can't open %s"
msgstr "ERROR: Kann %s nicht öffnen"

#: ../web/swat.c:200
msgid "Help"
msgstr "Hilfe"

#: ../web/swat.c:206 ../web/swat.c:220 ../web/swat.c:235 ../web/swat.c:243 ../web/swat.c:252 ../web/swat.c:261 ../web/swat.c:267 ../web/swat.c:273 ../web/swat.c:286
msgid "Set Default"
msgstr "Standardwert"

#: ../web/swat.c:408
#, c-format
msgid "failed to open %s for writing"
msgstr "konnte %s nicht schreiben"

#: ../web/swat.c:431
#, c-format
msgid "Can't reload %s"
msgstr ""

#: ../web/swat.c:501
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Verbunden als <b>%s</b>"

#: ../web/swat.c:505
msgid "Home"
msgstr "Home"

#: ../web/swat.c:507
msgid "Globals"
msgstr "Globals"

#: ../web/swat.c:508
msgid "Shares"
msgstr "Freigaben"

#: ../web/swat.c:509
msgid "Printers"
msgstr "Drucker"

#: ../web/swat.c:510
msgid "Wizard"
msgstr "Assistent"

#: ../web/swat.c:513
msgid "Status"
msgstr "Status"

#: ../web/swat.c:514
msgid "View Config"
msgstr "Zeige Konfiguration"

#: ../web/swat.c:516
msgid "Password Management"
msgstr "Passwortverwaltung"

#: ../web/swat.c:526
msgid "Current View Is"
msgstr "Aktuelle Konfiguration"

#: ../web/swat.c:527 ../web/swat.c:530
msgid "Basic"
msgstr "Einfache Ansicht"

#: ../web/swat.c:528 ../web/swat.c:531
msgid "Advanced"
msgstr "Erweiterte Ansicht"

#: ../web/swat.c:529
msgid "Change View To"
msgstr "Ansicht anpassen"

#: ../web/swat.c:554
msgid "Current Config"
msgstr "Aktuelle Konfiguration"

#: ../web/swat.c:558
msgid "Normal View"
msgstr "Normale Ansicht"

#: ../web/swat.c:560
msgid "Full View"
msgstr "Komplette Ansicht"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:579
msgid "Wizard Parameter Edit Page"
msgstr ""

#: ../web/swat.c:608
msgid "Note: smb.conf file has been read and rewritten"
msgstr "Hinweis: smb.conf wurde gelesen und überschrieben"

#. Here we go ...
#: ../web/swat.c:716
msgid "Samba Configuration Wizard"
msgstr "Samba Konfigurations-Assistent"

#: ../web/swat.c:720
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr "Der Button \"Passe smb.conf an\" wird alle Kommentare und Standardwerte aus der smb.conf löschen."

#: ../web/swat.c:721
msgid "The same will happen if you press the commit button."
msgstr "Das gleiche passiert bei \"übernehmen\"."

#: ../web/swat.c:724
msgid "Rewrite smb.conf file"
msgstr "Schreibe smb.conf neu"

#: ../web/swat.c:725
msgid "Commit"
msgstr "übernehmen"

#: ../web/swat.c:726
msgid "Edit Parameter Values"
msgstr "Bearbeite Parameter"

#: ../web/swat.c:732
msgid "Server Type"
msgstr "Server-Typ"

#: ../web/swat.c:733
msgid "Stand Alone"
msgstr "Einzelserver"

#: ../web/swat.c:734
msgid "Domain Member"
msgstr "Domänen-Mitglied"

#: ../web/swat.c:735
msgid "Domain Controller"
msgstr "Domänen-Controller"

#: ../web/swat.c:738
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr ""

#: ../web/swat.c:740
msgid "Configure WINS As"
msgstr "Konfiguriere WINS"

#: ../web/swat.c:741
msgid "Not Used"
msgstr "nicht benutzt"

#: ../web/swat.c:742
msgid "Server for client use"
msgstr "WINS-Server"

#: ../web/swat.c:743
msgid "Client of another WINS server"
msgstr "WINS-Client an anderem Server"

#: ../web/swat.c:745
msgid "Remote WINS Server"
msgstr "Zuständiger WINS-Server:"

#: ../web/swat.c:756
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr "Fehler: WINS-Server und WINS-Client zugleich in smb.conf gesetzt"

#: ../web/swat.c:757
msgid "Please Select desired WINS mode above."
msgstr "Bitte wählen Sie den WINS-Modus."

#: ../web/swat.c:759
msgid "Expose Home Directories"
msgstr "Home-Verzeichnisse freigeben"

#: ../web/swat.c:774
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr "Diese Konfigurationsoptionen bearbeiten mehrere Parameter und dienen als Hilfe zur schnellen Samba-Einrichtung."

#: ../web/swat.c:787
msgid "Global Parameters"
msgstr "Globale Parameter"

#: ../web/swat.c:815 ../web/swat.c:916 ../web/swat.c:1265
msgid "Commit Changes"
msgstr "Änderungen speichern"

#: ../web/swat.c:819 ../web/swat.c:919 ../web/swat.c:1267
msgid "Reset Values"
msgstr "Werte zurücksetzen"

#: ../web/swat.c:844
msgid "Share Parameters"
msgstr "Parameter der Freigabe"

#: ../web/swat.c:887
msgid "Choose Share"
msgstr "Wähle Freigabe"

#: ../web/swat.c:901
msgid "Delete Share"
msgstr "Lösche Freigabe"

#: ../web/swat.c:908
msgid "Create Share"
msgstr "Erstelle Freigabe"

#: ../web/swat.c:944
msgid "password change in demo mode rejected"
msgstr "Änderung des Passworts im Demo modus nicht aktiv"

#: ../web/swat.c:957
msgid "Can't setup password database vectors."
msgstr ""

#: ../web/swat.c:983
msgid " Must specify \"User Name\" "
msgstr " \"Benutzername\" muss angegeben werden "

#: ../web/swat.c:999
msgid " Must specify \"Old Password\" "
msgstr " \"Altes Passwort\" muss angegeben werden "

#: ../web/swat.c:1005
msgid " Must specify \"Remote Machine\" "
msgstr " \"Remote-Server\" muss angegeben werden "

#: ../web/swat.c:1012
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr " \"Neues/wiederholtes Passwort\" müssen angegeben werden "

#: ../web/swat.c:1018
msgid " Re-typed password didn't match new password "
msgstr " Das wiederholte Passwort stimmt nicht mit dem neuen Passwort überein"

#: ../web/swat.c:1048
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Das Passwort für '%s' wurde geändert."

#: ../web/swat.c:1051
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Das Passwort für '%s' wurde NICHT geändert."

#: ../web/swat.c:1076
msgid "Server Password Management"
msgstr "Verwaltung des Server Passwortes"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1085 ../web/swat.c:1132
msgid "User Name"
msgstr "Benutzername"

#: ../web/swat.c:1088 ../web/swat.c:1134
msgid "Old Password"
msgstr "Altes Passwort"

#: ../web/swat.c:1091 ../web/swat.c:1136
msgid "New Password"
msgstr "Neues Passwort"

#: ../web/swat.c:1093 ../web/swat.c:1138
msgid "Re-type New Password"
msgstr "Wiederhole neues Passwort"

#: ../web/swat.c:1101 ../web/swat.c:1149
msgid "Change Password"
msgstr "Ändere Passwort"

#: ../web/swat.c:1104
msgid "Add New User"
msgstr "Füge Benutzer hinzu"

#: ../web/swat.c:1106
msgid "Delete User"
msgstr "Lösche Benutzer"

#: ../web/swat.c:1108
msgid "Disable User"
msgstr "Deaktiviere Benutzer"

#: ../web/swat.c:1110
msgid "Enable User"
msgstr "Aktiviere Benutzer"

#: ../web/swat.c:1123
msgid "Client/Server Password Management"
msgstr "Client/Server Passwort Verwaltung"

#: ../web/swat.c:1140
msgid "Remote Machine"
msgstr "Remote-Server"

#: ../web/swat.c:1179
msgid "Printer Parameters"
msgstr "Drucker Parameter"

#: ../web/swat.c:1181
msgid "Important Note:"
msgstr "Wichtiger Hinweis:"

#: ../web/swat.c:1182
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Mit [*] gekennzeichnete Drucker in der Druckerauswahlliste"

#: ../web/swat.c:1183
msgid "are autoloaded printers from "
msgstr "wurden automatisch geladen von :"

#: ../web/swat.c:1184
msgid "Printcap Name"
msgstr "Printcap Name"

#: ../web/swat.c:1185
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr "Der Versuch diese Drucker von SWAT aus zu löschen wird keine Auswirkung haben."

#: ../web/swat.c:1231
msgid "Choose Printer"
msgstr "Wähle Drucker"

#: ../web/swat.c:1250
msgid "Delete Printer"
msgstr "Lösche Drucker"

#: ../web/swat.c:1257
msgid "Create Printer"
msgstr "Ersteller Drucker"

#: ../web/statuspage.c:123
msgid "RDONLY     "
msgstr ""

#: ../web/statuspage.c:124
msgid "WRONLY     "
msgstr ""

#: ../web/statuspage.c:125
msgid "RDWR       "
msgstr ""

#: ../web/statuspage.c:309
msgid "Server Status"
msgstr "Server-Status"

#: ../web/statuspage.c:314
msgid "Auto Refresh"
msgstr "Automatische Aktualisierung"

#: ../web/statuspage.c:315 ../web/statuspage.c:320
msgid "Refresh Interval: "
msgstr "Aktualisierungsintervall: "

#: ../web/statuspage.c:319
msgid "Stop Refreshing"
msgstr "Stoppe Aktualisierung"

#: ../web/statuspage.c:334
msgid "version:"
msgstr "Version:"

#: ../web/statuspage.c:337
msgid "smbd:"
msgstr ""

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "running"
msgstr "aktiv"

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "not running"
msgstr "inaktiv"

#: ../web/statuspage.c:341
msgid "Stop smbd"
msgstr "Stoppe smbd"

#: ../web/statuspage.c:343
msgid "Start smbd"
msgstr "Starte smbd"

#: ../web/statuspage.c:345
msgid "Restart smbd"
msgstr "Neustart smbd"

#: ../web/statuspage.c:350
msgid "nmbd:"
msgstr ""

#: ../web/statuspage.c:354
msgid "Stop nmbd"
msgstr "Stoppe nmbd"

#: ../web/statuspage.c:356
msgid "Start nmbd"
msgstr "Starte nmbd"

#: ../web/statuspage.c:358
msgid "Restart nmbd"
msgstr "Neustart nmbd"

#: ../web/statuspage.c:364
msgid "winbindd:"
msgstr ""

#: ../web/statuspage.c:368
msgid "Stop winbindd"
msgstr "Stoppe winbindd"

#: ../web/statuspage.c:370
msgid "Start winbindd"
msgstr "Starte winbindd"

#: ../web/statuspage.c:372
msgid "Restart winbindd"
msgstr "Neustart winbindd"

#. stop, restart all
#: ../web/statuspage.c:381
msgid "Stop All"
msgstr "Alle Stoppen"

#: ../web/statuspage.c:382
msgid "Restart All"
msgstr "Alle neu starten"

#. start all
#: ../web/statuspage.c:386
msgid "Start All"
msgstr "Alle Starten"

#: ../web/statuspage.c:393
msgid "Active Connections"
msgstr "Aktive Verbindungen"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "PID"
msgstr ""

#: ../web/statuspage.c:395 ../web/statuspage.c:408
msgid "Client"
msgstr ""

#: ../web/statuspage.c:395
msgid "IP address"
msgstr "IP-Adresse"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "Date"
msgstr "Datum"

#: ../web/statuspage.c:397
msgid "Kill"
msgstr "Killen"

#: ../web/statuspage.c:405
msgid "Active Shares"
msgstr "Aktive Freigaben"

#: ../web/statuspage.c:408
msgid "Share"
msgstr "Freigabe"

#: ../web/statuspage.c:408
msgid "User"
msgstr "Benutzer"

#: ../web/statuspage.c:408
msgid "Group"
msgstr "Gruppe"

#: ../web/statuspage.c:414
msgid "Open Files"
msgstr "Offene Dateien"

#: ../web/statuspage.c:416
msgid "Sharing"
msgstr ""

#: ../web/statuspage.c:416
msgid "R/W"
msgstr ""

#: ../web/statuspage.c:416
msgid "Oplock"
msgstr ""

#: ../web/statuspage.c:416
msgid "File"
msgstr "Datei"

#: ../web/statuspage.c:425
msgid "Show Client in col 1"
msgstr ""

#: ../web/statuspage.c:426
msgid "Show PID in col 1"
msgstr ""

#: ../param/loadparm.c:755
msgid "Base Options"
msgstr "Basisoptionen"

#: ../param/loadparm.c:775
msgid "Security Options"
msgstr "Sicherheitsoptionen"

#: ../param/loadparm.c:859
msgid "Logging Options"
msgstr "Log Optionen"

#: ../param/loadparm.c:874
msgid "Protocol Options"
msgstr "Protokoll Optionen"

#: ../param/loadparm.c:911
msgid "Tuning Options"
msgstr "Optimierungsoptionen"

#: ../param/loadparm.c:940
msgid "Printing Options"
msgstr "Druckoptionen"

#: ../param/loadparm.c:970
msgid "Filename Handling"
msgstr "Verwaltung Dateinamen"

#: ../param/loadparm.c:996
msgid "Domain Options"
msgstr "Domänen Optionen"

#: ../param/loadparm.c:1000
msgid "Logon Options"
msgstr "Login optionen"

#: ../param/loadparm.c:1019
msgid "Browse Options"
msgstr "Browsing Optionen"

#: ../param/loadparm.c:1033
msgid "WINS Options"
msgstr "WINS Optionen"

#: ../param/loadparm.c:1043
msgid "Locking Options"
msgstr "Locking Optionen"

#: ../param/loadparm.c:1061
msgid "Ldap Options"
msgstr "LDAP Optionen"

#: ../param/loadparm.c:1078
msgid "Miscellaneous Options"
msgstr "Verschiedene Optionen"

#: ../param/loadparm.c:1138
msgid "VFS module options"
msgstr "VFS Optionen"

#: ../param/loadparm.c:1148
msgid "Winbind options"
msgstr "Winbind Optionen"
