# Dutch messages for international release of SWAT.
# Copyright (C) 2003 Jelmer Vernooij <jelmer@samba.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"POT-Creation-Date: 2003-10-06 05:30+0900\n"
"PO-Revision-Date: 2000-02-08 12:48+09:00\n"
"Last-Translator: Jelmer Vernooij <jelmer@samba.org>\n"
"Language-Team: (Samba Team) <samba-technical@samba.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"

#: ../web/swat.c:117
#, c-format
msgid "ERROR: Can't open %s"
msgstr "FOUT: Kan %s niet openen"

#: ../web/swat.c:200
msgid "Help"
msgstr "Help"

#: ../web/swat.c:206 ../web/swat.c:220 ../web/swat.c:235 ../web/swat.c:243 ../web/swat.c:252 ../web/swat.c:261 ../web/swat.c:267 ../web/swat.c:273 ../web/swat.c:286
msgid "Set Default"
msgstr "Stel Standaard In"

#: ../web/swat.c:408
#, c-format
msgid "failed to open %s for writing"
msgstr "kon %s niet openen voor schrijven"

#: ../web/swat.c:431
#, c-format
msgid "Can't reload %s"
msgstr "Kan %s niet herladen"

#: ../web/swat.c:501
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Ingelogd als <b>%s</b>"

#: ../web/swat.c:505
msgid "Home"
msgstr "Home"

#: ../web/swat.c:507
msgid "Globals"
msgstr "Algemene Instellingen"

#: ../web/swat.c:508
msgid "Shares"
msgstr "Gedeelde Bronnen"

#: ../web/swat.c:509
msgid "Printers"
msgstr "Printers"

#: ../web/swat.c:510
msgid "Wizard"
msgstr "Wizard"

#: ../web/swat.c:513
msgid "Status"
msgstr "Status"

#: ../web/swat.c:514
msgid "View Config"
msgstr "Bekijk Configuratie"

#: ../web/swat.c:516
msgid "Password Management"
msgstr "Wachtwoord Beheer"

#: ../web/swat.c:526
msgid "Current View Is"
msgstr "Huidige weergave is"

#: ../web/swat.c:527 ../web/swat.c:530
msgid "Basic"
msgstr "Basis"

#: ../web/swat.c:528 ../web/swat.c:531
msgid "Advanced"
msgstr "Geadvanceerd"

#: ../web/swat.c:529
msgid "Change View To"
msgstr "Verander Weergave In"

#: ../web/swat.c:554
msgid "Current Config"
msgstr "Huidige Configuratie"

#: ../web/swat.c:558
msgid "Normal View"
msgstr "Normale Weergave"

#: ../web/swat.c:560
msgid "Full View"
msgstr "Volledige Weergave"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:579
msgid "Wizard Parameter Edit Page"
msgstr "Wizard Instellingen Veranderen Pagina"

#: ../web/swat.c:608
msgid "Note: smb.conf file has been read and rewritten"
msgstr "N.B.: het smb.conf bestand is gelezen en herschreven"

#. Here we go ...
#: ../web/swat.c:716
msgid "Samba Configuration Wizard"
msgstr "Samba Configuratie Wizard"

#: ../web/swat.c:720
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr "De \"Herschrijf smb.conf bestand\" knop zal alle standaardwaardes en alle commentaar verwijderen."

#: ../web/swat.c:721
msgid "The same will happen if you press the commit button."
msgstr "Hetzelfde zal gebeuren als u de \"toepassen\" knop gebruikt."

#: ../web/swat.c:724
msgid "Rewrite smb.conf file"
msgstr "Herschrijf smb.conf bestand"

#: ../web/swat.c:725
msgid "Commit"
msgstr "Toepassen"

#: ../web/swat.c:726
msgid "Edit Parameter Values"
msgstr "Bewerk Configuratie Waardes"

#: ../web/swat.c:732
msgid "Server Type"
msgstr "Server Type"

#: ../web/swat.c:733
msgid "Stand Alone"
msgstr "Stand Alone"

#: ../web/swat.c:734
msgid "Domain Member"
msgstr "Domein Lid"

#: ../web/swat.c:735
msgid "Domain Controller"
msgstr "Domein Controller"

#: ../web/swat.c:738
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr "Ongebruikelijk Type in smb.conf - Selecteer een nieuwe modus"

#: ../web/swat.c:740
msgid "Configure WINS As"
msgstr "Configureer WINS Als"

#: ../web/swat.c:741
msgid "Not Used"
msgstr "Niet gebruikt"

#: ../web/swat.c:742
msgid "Server for client use"
msgstr "Server voor client gebruik"

#: ../web/swat.c:743
msgid "Client of another WINS server"
msgstr "Client van een andere WINS server"

#: ../web/swat.c:745
msgid "Remote WINS Server"
msgstr "Naam of IP-adres WINS Server"

#: ../web/swat.c:756
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr "Fout: WINS Server Modus en WINS Ondersteuning beiden ingesteld in smb.conf"

#: ../web/swat.c:757
msgid "Please Select desired WINS mode above."
msgstr "Selecteer hierboven de gewenste WINS modus."

#: ../web/swat.c:759
msgid "Expose Home Directories"
msgstr "Stel Home Directories Open"

#: ../web/swat.c:774
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr "The configuratie hierboven zal meerdere variabelen veranderen en zal over het algemeen zorgen voor snelle installatie van Samba."

#: ../web/swat.c:787
msgid "Global Parameters"
msgstr "Algemene Instellingen"

#: ../web/swat.c:815 ../web/swat.c:916 ../web/swat.c:1265
msgid "Commit Changes"
msgstr "Pas Veranderingen Toe"

#: ../web/swat.c:819 ../web/swat.c:919 ../web/swat.c:1267
msgid "Reset Values"
msgstr "Beginwaarden"

#: ../web/swat.c:844
msgid "Share Parameters"
msgstr "Instellingen Gedeelde Bronnen"

#: ../web/swat.c:887
msgid "Choose Share"
msgstr "Kies Bron"

#: ../web/swat.c:901
msgid "Delete Share"
msgstr "Verwijder Bron"

#: ../web/swat.c:908
msgid "Create Share"
msgstr "Maak Bron"

#: ../web/swat.c:944
msgid "password change in demo mode rejected"
msgstr "wachtwoord veranderen in demo modus geweigerd"

#: ../web/swat.c:957
msgid "Can't setup password database vectors."
msgstr "Kan wachtwoord database vectors niet opzetten."

#: ../web/swat.c:983
msgid " Must specify \"User Name\" "
msgstr " \"Gebruikersnaam\" moet opgegeven worden "

#: ../web/swat.c:999
msgid " Must specify \"Old Password\" "
msgstr " \"Oude wachtwoord\" moet opgegeven worden "

#: ../web/swat.c:1005
msgid " Must specify \"Remote Machine\" "
msgstr " \"Server Naam of IP\" moet opgegeven worden "

#: ../web/swat.c:1012
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr " \"Nieuw, en bevestiging Wachtwoorden\" moeten opgegeven worden "

#: ../web/swat.c:1018
msgid " Re-typed password didn't match new password "
msgstr " Bevestigingswachtwoord was anders dan nieuwe wachtwoord "

#: ../web/swat.c:1048
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Het wachtwoord voor '%s' is veranderd."

#: ../web/swat.c:1051
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Het wachtwoord voor '%s' is niet veranderd."

#: ../web/swat.c:1076
msgid "Server Password Management"
msgstr "Server Wachtwoord Beheer"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1085 ../web/swat.c:1132
msgid "User Name"
msgstr "Gebuikersnaam"

#: ../web/swat.c:1088 ../web/swat.c:1134
msgid "Old Password"
msgstr "Oud Wachtwoord"

#: ../web/swat.c:1091 ../web/swat.c:1136
msgid "New Password"
msgstr "Nieuw Wachtwoord"

#: ../web/swat.c:1093 ../web/swat.c:1138
msgid "Re-type New Password"
msgstr "Bevestiging Nieuw Wachtwoord"

#: ../web/swat.c:1101 ../web/swat.c:1149
msgid "Change Password"
msgstr "Verander Wachtwoord"

#: ../web/swat.c:1104
msgid "Add New User"
msgstr "Voeg Gebruiker Toe"

#: ../web/swat.c:1106
msgid "Delete User"
msgstr "Verwijder Gebruiker"

#: ../web/swat.c:1108
msgid "Disable User"
msgstr "Maak gebruiker inactief"

#: ../web/swat.c:1110
msgid "Enable User"
msgstr "Maak gebruiker actief"

#: ../web/swat.c:1123
msgid "Client/Server Password Management"
msgstr "Client/Server Wachtwoord Beheer"

#: ../web/swat.c:1140
msgid "Remote Machine"
msgstr "Naam of IP Server"

#: ../web/swat.c:1179
msgid "Printer Parameters"
msgstr "Printer Instellingen"

#: ../web/swat.c:1181
msgid "Important Note:"
msgstr "Belangrijk:"

#: ../web/swat.c:1182
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Printer namen gemarkeerd met [*] in het Kies Printer veld "

#: ../web/swat.c:1183
msgid "are autoloaded printers from "
msgstr "zijn automatisch geladen uit "

#: ../web/swat.c:1184
msgid "Printcap Name"
msgstr "Printcap Naam"

#: ../web/swat.c:1185
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr "Proberen deze printers te verwijderen vanuit SWAT zal geen effect hebben."

#: ../web/swat.c:1231
msgid "Choose Printer"
msgstr "Kies Printer"

#: ../web/swat.c:1250
msgid "Delete Printer"
msgstr "Verwijder Printer"

#: ../web/swat.c:1257
msgid "Create Printer"
msgstr "Maak Printer"

#: ../web/statuspage.c:123
msgid "RDONLY     "
msgstr "RDONLY"

#: ../web/statuspage.c:124
msgid "WRONLY     "
msgstr "WRONLY"

#: ../web/statuspage.c:125
msgid "RDWR       "
msgstr "RDWR"

#: ../web/statuspage.c:309
msgid "Server Status"
msgstr "Server Status"

#: ../web/statuspage.c:314
msgid "Auto Refresh"
msgstr "Automatisch Verversen"

#: ../web/statuspage.c:315 ../web/statuspage.c:320
msgid "Refresh Interval: "
msgstr "Ververs Interval:"

#: ../web/statuspage.c:319
msgid "Stop Refreshing"
msgstr "Stop met Verversen"

#: ../web/statuspage.c:334
msgid "version:"
msgstr "versie:"

#: ../web/statuspage.c:337
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "running"
msgstr "draaiend"

#: ../web/statuspage.c:337 ../web/statuspage.c:350 ../web/statuspage.c:364
msgid "not running"
msgstr "niet draaiend"

#: ../web/statuspage.c:341
msgid "Stop smbd"
msgstr "Stop smbd"

#: ../web/statuspage.c:343
msgid "Start smbd"
msgstr "Start smbd"

#: ../web/statuspage.c:345
msgid "Restart smbd"
msgstr "Herstart smbd"

#: ../web/statuspage.c:350
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:354
msgid "Stop nmbd"
msgstr "Stop nmbd"

#: ../web/statuspage.c:356
msgid "Start nmbd"
msgstr "Start nmbd"

#: ../web/statuspage.c:358
msgid "Restart nmbd"
msgstr "Herstart nmbd"

#: ../web/statuspage.c:364
msgid "winbindd:"
msgstr "winbindd:"

#: ../web/statuspage.c:368
msgid "Stop winbindd"
msgstr "Stop winbindd"

#: ../web/statuspage.c:370
msgid "Start winbindd"
msgstr "Start winbindd"

#: ../web/statuspage.c:372
msgid "Restart winbindd"
msgstr "Herstart winbindd"

#. stop, restart all
#: ../web/statuspage.c:381
msgid "Stop All"
msgstr "Stop Alles"

#: ../web/statuspage.c:382
msgid "Restart All"
msgstr "Herstart Alles"

#. start all
#: ../web/statuspage.c:386
msgid "Start All"
msgstr "Start Alles"

#: ../web/statuspage.c:393
msgid "Active Connections"
msgstr "Actieve Verbindingen"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:395 ../web/statuspage.c:408
msgid "Client"
msgstr "Client"

#: ../web/statuspage.c:395
msgid "IP address"
msgstr "IP adres"

#: ../web/statuspage.c:395 ../web/statuspage.c:408 ../web/statuspage.c:416
msgid "Date"
msgstr "Datum"

#: ../web/statuspage.c:397
msgid "Kill"
msgstr "Kill"

#: ../web/statuspage.c:405
msgid "Active Shares"
msgstr "Actieve Bronnen"

#: ../web/statuspage.c:408
msgid "Share"
msgstr "Bron"

#: ../web/statuspage.c:408
msgid "User"
msgstr "Gebruiker"

#: ../web/statuspage.c:408
msgid "Group"
msgstr "Groep"

#: ../web/statuspage.c:414
msgid "Open Files"
msgstr "Geopende Bestanden"

#: ../web/statuspage.c:416
msgid "Sharing"
msgstr "Gedeeld"

#: ../web/statuspage.c:416
msgid "R/W"
msgstr "Lees/Schrijf"

#: ../web/statuspage.c:416
msgid "Oplock"
msgstr "Oplock"

#: ../web/statuspage.c:416
msgid "File"
msgstr "Bestand"

#: ../web/statuspage.c:425
msgid "Show Client in col 1"
msgstr "Toon Client in kolom 1"

#: ../web/statuspage.c:426
msgid "Show PID in col 1"
msgstr "Toon PID in kolom 1"

#: ../param/loadparm.c:755
msgid "Base Options"
msgstr "Basis Opties"

#: ../param/loadparm.c:775
msgid "Security Options"
msgstr "Veiligheidsopties"

#: ../param/loadparm.c:859
msgid "Logging Options"
msgstr "Log Opties"

#: ../param/loadparm.c:874
msgid "Protocol Options"
msgstr "Protocol Opties"

#: ../param/loadparm.c:911
msgid "Tuning Options"
msgstr "Fijntune Opties"

#: ../param/loadparm.c:940
msgid "Printing Options"
msgstr "Printer Opties"

#: ../param/loadparm.c:970
msgid "Filename Handling"
msgstr "Bestandsnaam Afhandeling"

#: ../param/loadparm.c:996
msgid "Domain Options"
msgstr "Domein Opties"

#: ../param/loadparm.c:1000
msgid "Logon Options"
msgstr "Logon Opties"

#: ../param/loadparm.c:1019
msgid "Browse Options"
msgstr "Verken Opties"

#: ../param/loadparm.c:1033
msgid "WINS Options"
msgstr "WINS Opties"

#: ../param/loadparm.c:1043
msgid "Locking Options"
msgstr "Locking Opties"

#: ../param/loadparm.c:1061
msgid "Ldap Options"
msgstr "LDAP Opties"

#: ../param/loadparm.c:1078
msgid "Miscellaneous Options"
msgstr "Verscheidene Opties"

#: ../param/loadparm.c:1138
msgid "VFS module options"
msgstr "VFS module opties"

#: ../param/loadparm.c:1148
msgid "Winbind options"
msgstr "Winbind opties"
