mkdir %1\include
mkdir %1\include\openssl

copy /D /V .\.\e_os.h %1\include\e_os.h
copy /D /V .\crypto\cryptlib.h %1\include\cryptlib.h
copy /D /V .\crypto\buildinf.h %1\include\buildinf.h
copy /D /V .\crypto\md32_common.h %1\include\md32_common.h
copy /D /V .\crypto\o_time.h %1\include\o_time.h
copy /D /V .\crypto\md4\md4_locl.h %1\include\md4_locl.h
copy /D /V .\crypto\md5\md5_locl.h %1\include\md5_locl.h
copy /D /V .\crypto\sha\sha_locl.h %1\include\sha_locl.h
copy /D /V .\crypto\ripemd\rmd_locl.h %1\include\rmd_locl.h
copy /D /V .\crypto\ripemd\rmdconst.h %1\include\rmdconst.h
copy /D /V .\crypto\des\des_locl.h %1\include\des_locl.h
copy /D /V .\crypto\des\rpc_des.h %1\include\rpc_des.h
copy /D /V .\crypto\des\spr.h %1\include\spr.h
copy /D /V .\crypto\des\des_ver.h %1\include\des_ver.h
copy /D /V .\crypto\rc2\rc2_locl.h %1\include\rc2_locl.h
copy /D /V .\crypto\rc4\rc4_locl.h %1\include\rc4_locl.h
copy /D /V .\crypto\rc5\rc5_locl.h %1\include\rc5_locl.h
copy /D /V .\crypto\idea\idea_lcl.h %1\include\idea_lcl.h
copy /D /V .\crypto\bf\bf_pi.h %1\include\bf_pi.h
copy /D /V .\crypto\bf\bf_locl.h %1\include\bf_locl.h
copy /D /V .\crypto\cast\cast_s.h %1\include\cast_s.h
copy /D /V .\crypto\cast\cast_lcl.h %1\include\cast_lcl.h
copy /D /V .\crypto\aes\aes_locl.h %1\include\aes_locl.h
copy /D /V .\crypto\bn\bn_lcl.h %1\include\bn_lcl.h
copy /D /V .\crypto\bn\bn_prime.h %1\include\bn_prime.h
copy /D /V .\crypto\ec\ec_lcl.h %1\include\ec_lcl.h
copy /D /V .\crypto\bio\bss_file.c %1\include\bss_file.c
copy /D /V .\crypto\objects\obj_dat.h %1\include\obj_dat.h
copy /D /V .\crypto\conf\conf_def.h %1\include\conf_def.h
copy /D /V .\crypto\ui\ui_locl.h %1\include\ui_locl.h
copy /D /V .\ssl\ssl_locl.h %1\include\ssl_locl.h
copy /D /V .\ssl\kssl_lcl.h %1\include\kssl_lcl.h

copy /D /V .\.\e_os2.h %1\include\openssl\e_os2.h
copy /D /V .\crypto\crypto.h %1\include\openssl\crypto.h
copy /D /V .\crypto\tmdiff.h %1\include\openssl\tmdiff.h
copy /D /V .\crypto\opensslv.h %1\include\openssl\opensslv.h
copy /D /V .\crypto\opensslconf.h %1\include\openssl\opensslconf.h
copy /D /V .\crypto\ebcdic.h %1\include\openssl\ebcdic.h
copy /D /V .\crypto\symhacks.h %1\include\openssl\symhacks.h
copy /D /V .\crypto\ossl_typ.h %1\include\openssl\ossl_typ.h
copy /D /V .\crypto\md2\md2.h %1\include\openssl\md2.h
copy /D /V .\crypto\md4\md4.h %1\include\openssl\md4.h
copy /D /V .\crypto\md5\md5.h %1\include\openssl\md5.h
copy /D /V .\crypto\sha\sha.h %1\include\openssl\sha.h
copy /D /V .\crypto\mdc2\mdc2.h %1\include\openssl\mdc2.h
copy /D /V .\crypto\hmac\hmac.h %1\include\openssl\hmac.h
copy /D /V .\crypto\ripemd\ripemd.h %1\include\openssl\ripemd.h
copy /D /V .\crypto\des\des.h %1\include\openssl\des.h
copy /D /V .\crypto\des\des_old.h %1\include\openssl\des_old.h
copy /D /V .\crypto\rc2\rc2.h %1\include\openssl\rc2.h
copy /D /V .\crypto\rc4\rc4.h %1\include\openssl\rc4.h
copy /D /V .\crypto\rc5\rc5.h %1\include\openssl\rc5.h
copy /D /V .\crypto\idea\idea.h %1\include\openssl\idea.h
copy /D /V .\crypto\bf\blowfish.h %1\include\openssl\blowfish.h
copy /D /V .\crypto\cast\cast.h %1\include\openssl\cast.h
copy /D /V .\crypto\aes\aes.h %1\include\openssl\aes.h
copy /D /V .\crypto\bn\bn.h %1\include\openssl\bn.h
copy /D /V .\crypto\rsa\rsa.h %1\include\openssl\rsa.h
copy /D /V .\crypto\dsa\dsa.h %1\include\openssl\dsa.h
copy /D /V .\crypto\dso\dso.h %1\include\openssl\dso.h
copy /D /V .\crypto\dh\dh.h %1\include\openssl\dh.h
copy /D /V .\crypto\ec\ec.h %1\include\openssl\ec.h
copy /D /V .\crypto\buffer\buffer.h %1\include\openssl\buffer.h
copy /D /V .\crypto\bio\bio.h %1\include\openssl\bio.h
copy /D /V .\crypto\stack\stack.h %1\include\openssl\stack.h
copy /D /V .\crypto\stack\safestack.h %1\include\openssl\safestack.h
copy /D /V .\crypto\lhash\lhash.h %1\include\openssl\lhash.h
copy /D /V .\crypto\rand\rand.h %1\include\openssl\rand.h
copy /D /V .\crypto\err\err.h %1\include\openssl\err.h
copy /D /V .\crypto\objects\objects.h %1\include\openssl\objects.h
copy /D /V .\crypto\objects\obj_mac.h %1\include\openssl\obj_mac.h
copy /D /V .\crypto\evp\evp.h %1\include\openssl\evp.h
copy /D /V .\crypto\asn1\asn1.h %1\include\openssl\asn1.h
copy /D /V .\crypto\asn1\asn1_mac.h %1\include\openssl\asn1_mac.h
copy /D /V .\crypto\asn1\asn1t.h %1\include\openssl\asn1t.h
copy /D /V .\crypto\pem\pem.h %1\include\openssl\pem.h
copy /D /V .\crypto\pem\pem2.h %1\include\openssl\pem2.h
copy /D /V .\crypto\x509\x509.h %1\include\openssl\x509.h
copy /D /V .\crypto\x509\x509_vfy.h %1\include\openssl\x509_vfy.h
copy /D /V .\crypto\x509v3\x509v3.h %1\include\openssl\x509v3.h
copy /D /V .\crypto\conf\conf.h %1\include\openssl\conf.h
copy /D /V .\crypto\conf\conf_api.h %1\include\openssl\conf_api.h
copy /D /V .\crypto\txt_db\txt_db.h %1\include\openssl\txt_db.h
copy /D /V .\crypto\pkcs7\pkcs7.h %1\include\openssl\pkcs7.h
copy /D /V .\crypto\pkcs12\pkcs12.h %1\include\openssl\pkcs12.h
copy /D /V .\crypto\comp\comp.h %1\include\openssl\comp.h
copy /D /V .\crypto\engine\engine.h %1\include\openssl\engine.h
copy /D /V .\crypto\ocsp\ocsp.h %1\include\openssl\ocsp.h
copy /D /V .\crypto\ui\ui.h %1\include\openssl\ui.h
copy /D /V .\crypto\ui\ui_compat.h %1\include\openssl\ui_compat.h
copy /D /V .\crypto\krb5\krb5_asn.h %1\include\openssl\krb5_asn.h
copy /D /V .\ssl\ssl.h %1\include\openssl\ssl.h
copy /D /V .\ssl\ssl2.h %1\include\openssl\ssl2.h
copy /D /V .\ssl\ssl3.h %1\include\openssl\ssl3.h
copy /D /V .\ssl\ssl23.h %1\include\openssl\ssl23.h
copy /D /V .\ssl\tls1.h %1\include\openssl\tls1.h
copy /D /V .\ssl\kssl.h %1\include\openssl\kssl.h


