INCLUDES=-I. -I../../../ -I../../ffmpeg -I../../../linux -I../../../../guilib 
CFLAGS+=-D__STDC_CONSTANT_MACROS

SRCS=DVDDemux.cpp DVDDemuxFFmpeg.cpp DVDDemuxShoutcast.cpp DVDDemuxUtils.cpp DVDFactoryDemuxer.cpp DVDDemuxVobsub.cpp

LIB=dvddemuxers.a

include ../../../../Makefile.include
-include Makefile.depend
