set QT_SRC_DIR="c:\work\qt\lindenqt"
set OPENSSL_SRC_DIR="c:\work\qt\openssl-0.9.8l"
set LLQTWEBKIT_SRC_DIR="c:\work\llqtwebkit-4.6"
set SL_DEST_DIR=".\"

if not exist %SL_DEST_DIR%\release\QtCore4.dll           (xcopy %QT_SRC_DIR%\lib\QtCore4.dll         %SL_DEST_DIR%\release\ /y)      
if not exist %SL_DEST_DIR%\qt\release\QtCore4.lib        (xcopy %QT_SRC_DIR%\lib\QtCore4.lib         %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\debug\QtCored4.dll            (xcopy %QT_SRC_DIR%\lib\QtCored4.dll        %SL_DEST_DIR%\debug\ /y)        
if not exist %SL_DEST_DIR%\qt\debug\QtCored4.lib         (xcopy %QT_SRC_DIR%\lib\QtCored4.lib        %SL_DEST_DIR%\qt\debug\ /y)     
if not exist %SL_DEST_DIR%\release\QtGui4.dll            (xcopy %QT_SRC_DIR%\lib\QtGui4.dll          %SL_DEST_DIR%\release\ /y)      
if not exist %SL_DEST_DIR%\qt\release\QtGui4.lib         (xcopy %QT_SRC_DIR%\lib\QtGui4.lib          %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\debug\QtGuid4.dll             (xcopy %QT_SRC_DIR%\lib\QtGuid4.dll         %SL_DEST_DIR%\debug\ /y)        
if not exist %SL_DEST_DIR%\qt\debug\QtGuid4.lib          (xcopy %QT_SRC_DIR%\lib\QtGuid4.lib         %SL_DEST_DIR%\qt\debug\ /y)     
if not exist %SL_DEST_DIR%\release\QtNetwork4.dll        (xcopy %QT_SRC_DIR%\lib\QtNetwork4.dll      %SL_DEST_DIR%\release\ /y)      
if not exist %SL_DEST_DIR%\qt\release\QtNetwork4.lib     (xcopy %QT_SRC_DIR%\lib\QtNetwork4.lib      %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\debug\QtNetworkd4.dll         (xcopy %QT_SRC_DIR%\lib\QtNetworkd4.dll     %SL_DEST_DIR%\debug\ /y)        
if not exist %SL_DEST_DIR%\qt\debug\QtNetworkd4.lib      (xcopy %QT_SRC_DIR%\lib\QtNetworkd4.lib     %SL_DEST_DIR%\qt\debug\ /y)     
if not exist %SL_DEST_DIR%\release\QtOpenGL4.dll         (xcopy %QT_SRC_DIR%\lib\QtOpenGL4.dll       %SL_DEST_DIR%\release\ /y)      
if not exist %SL_DEST_DIR%\qt\release\QtOpenGL4.lib      (xcopy %QT_SRC_DIR%\lib\QtOpenGL4.lib       %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\debug\QtOpenGLd4.dll          (xcopy %QT_SRC_DIR%\lib\QtOpenGLd4.dll      %SL_DEST_DIR%\debug\ /y)        
if not exist %SL_DEST_DIR%\qt\debug\QtOpenGLd4.lib       (xcopy %QT_SRC_DIR%\lib\QtOpenGLd4.lib      %SL_DEST_DIR%\qt\debug\ /y)     
if not exist %SL_DEST_DIR%\release\QtWebKit4.dll         (xcopy %QT_SRC_DIR%\lib\QtWebKit4.dll       %SL_DEST_DIR%\release\ /y)      
if not exist %SL_DEST_DIR%\qt\release\QtWebKit4.lib      (xcopy %QT_SRC_DIR%\lib\QtWebKit4.lib       %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\debug\QtWebKitd4.dll          (xcopy %QT_SRC_DIR%\lib\QtWebKitd4.dll      %SL_DEST_DIR%\debug\ /y)     	 
if not exist %SL_DEST_DIR%\qt\debug\QtWebKitd4.lib       (xcopy %QT_SRC_DIR%\lib\QtWebKitd4.lib      %SL_DEST_DIR%\qt\debug\ /y)     
if not exist %SL_DEST_DIR%\release\QtXmlPatterns4.dll    (xcopy %QT_SRC_DIR%\lib\QtXmlPatterns4.dll  %SL_DEST_DIR%\release\ /y)      
if not exist %SL_DEST_DIR%\qt\release\QtXmlPatterns4.lib (xcopy %QT_SRC_DIR%\lib\QtXmlPatterns4.lib  %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\debug\QtXmlPatternsd4.dll     (xcopy %QT_SRC_DIR%\lib\QtXmlPatternsd4.dll %SL_DEST_DIR%\debug\ /y)     	 
if not exist %SL_DEST_DIR%\qt\debug\QtXmlPatternsd4.lib  (xcopy %QT_SRC_DIR%\lib\QtXmlPatternsd4.lib %SL_DEST_DIR%\qt\debug\ /y)     
if not exist %SL_DEST_DIR%\qt\release\qtmain.lib         (xcopy %QT_SRC_DIR%\lib\qtmain.lib          %SL_DEST_DIR%\qt\release\ /y)   
if not exist %SL_DEST_DIR%\qt\debug\qtmaind.lib          (xcopy %QT_SRC_DIR%\lib\qtmaind.lib         %SL_DEST_DIR%\qt\debug\ /y)     

if not exist %SL_DEST_DIR%\debug\imageformats\qgifd4.dll   (xcopy %QT_SRC_DIR%\plugins\imageformats\qgifd4.dll  %SL_DEST_DIR%\debug\imageformats\ /y)   
if not exist %SL_DEST_DIR%\debug\imageformats\qicod4.dll   (xcopy %QT_SRC_DIR%\plugins\imageformats\qicod4.dll  %SL_DEST_DIR%\debug\imageformats\ /y)   
if not exist %SL_DEST_DIR%\debug\imageformats\qjpegd4.dll  (xcopy %QT_SRC_DIR%\plugins\imageformats\qjpegd4.dll %SL_DEST_DIR%\debug\imageformats\ /y)   
if not exist %SL_DEST_DIR%\debug\imageformats\qmngd4.dll   (xcopy %QT_SRC_DIR%\plugins\imageformats\qmngd4.dll  %SL_DEST_DIR%\debug\imageformats\ /y)   
if not exist %SL_DEST_DIR%\debug\imageformats\qsvgd4.dll   (xcopy %QT_SRC_DIR%\plugins\imageformats\qsvgd4.dll  %SL_DEST_DIR%\debug\imageformats\ /y)   
if not exist %SL_DEST_DIR%\debug\imageformats\qtiffd4.dll  (xcopy %QT_SRC_DIR%\plugins\imageformats\qtiffd4.dll %SL_DEST_DIR%\debug\imageformats\ /y)   
if not exist %SL_DEST_DIR%\release\imageformats\qgif4.dll  (xcopy %QT_SRC_DIR%\plugins\imageformats\qgif4.dll   %SL_DEST_DIR%\release\imageformats\ /y) 
if not exist %SL_DEST_DIR%\release\imageformats\qico4.dll  (xcopy %QT_SRC_DIR%\plugins\imageformats\qico4.dll   %SL_DEST_DIR%\release\imageformats\ /y) 
if not exist %SL_DEST_DIR%\release\imageformats\qjpeg4.dll (xcopy %QT_SRC_DIR%\plugins\imageformats\qjpeg4.dll  %SL_DEST_DIR%\release\imageformats\ /y) 
if not exist %SL_DEST_DIR%\release\imageformats\qmng4.dll  (xcopy %QT_SRC_DIR%\plugins\imageformats\qmng4.dll   %SL_DEST_DIR%\release\imageformats\ /y) 
if not exist %SL_DEST_DIR%\release\imageformats\qsvg4.dll  (xcopy %QT_SRC_DIR%\plugins\imageformats\qsvg4.dll   %SL_DEST_DIR%\release\imageformats\ /y) 
if not exist %SL_DEST_DIR%\release\imageformats\qtiff4.dll (xcopy %QT_SRC_DIR%\plugins\imageformats\qtiff4.dll  %SL_DEST_DIR%\release\imageformats\ /y) 

if not exist %SL_DEST_DIR%\release\codecs\qcncodecs4.dll (xcopy %QT_SRC_DIR%\plugins\codecs\qcncodecs4.dll  %SL_DEST_DIR%\release\codecs\ /y) 
if not exist %SL_DEST_DIR%\debug\codecs\qcncodecsd4.dll  (xcopy %QT_SRC_DIR%\plugins\codecs\qcncodecsd4.dll %SL_DEST_DIR%\debug\codecs\ /y) 
if not exist %SL_DEST_DIR%\release\codecs\qjpcodecs4.dll (xcopy %QT_SRC_DIR%\plugins\codecs\qjpcodecs4.dll  %SL_DEST_DIR%\release\codecs\ /y) 
if not exist %SL_DEST_DIR%\debug\codecs\qjpcodecsd4.dll  (xcopy %QT_SRC_DIR%\plugins\codecs\qjpcodecsd4.dll %SL_DEST_DIR%\debug\codecs\ /y) 
if not exist %SL_DEST_DIR%\release\codecs\qkrcodecs4.dll (xcopy %QT_SRC_DIR%\plugins\codecs\qkrcodecs4.dll  %SL_DEST_DIR%\release\codecs\ /y) 
if not exist %SL_DEST_DIR%\debug\codecs\qkrcodecsd4.dll  (xcopy %QT_SRC_DIR%\plugins\codecs\qkrcodecsd4.dll %SL_DEST_DIR%\debug\codecs\ /y) 
if not exist %SL_DEST_DIR%\release\codecs\qtwcodecs4.dll (xcopy %QT_SRC_DIR%\plugins\codecs\qtwcodecs4.dll  %SL_DEST_DIR%\release\codecs\ /y) 
if not exist %SL_DEST_DIR%\debug\codecs\qtwcodecsd4.dll  (xcopy %QT_SRC_DIR%\plugins\codecs\qtwcodecsd4.dll %SL_DEST_DIR%\debug\codecs\ /y) 

if not exist %SL_DEST_DIR%\debug\ssleay32.dll   (xcopy %OPENSSL_SRC_DIR%\out32dll\ssleay32.dll %SL_DEST_DIR%\debug\ /y)   
if not exist %SL_DEST_DIR%\debug\libeay32.dll   (xcopy %OPENSSL_SRC_DIR%\out32dll\libeay32.dll %SL_DEST_DIR%\debug\ /y)   
if not exist %SL_DEST_DIR%\release\ssleay32.dll (xcopy %OPENSSL_SRC_DIR%\out32dll\ssleay32.dll %SL_DEST_DIR%\release\ /y) 
if not exist %SL_DEST_DIR%\release\libeay32.dll (xcopy %OPENSSL_SRC_DIR%\out32dll\libeay32.dll %SL_DEST_DIR%\release\ /y) 

if not exist %SL_DEST_DIR%\llqtwebkit\llqtwebkit.h           (xcopy %LLQTWEBKIT_SRC_DIR%\llqtwebkit.h           %SL_DEST_DIR%\llqtwebkit\ /y)
if not exist %SL_DEST_DIR%\llqtwebkit\debug\llqtwebkitd.lib  (xcopy %LLQTWEBKIT_SRC_DIR%\debug\llqtwebkitd.lib  %SL_DEST_DIR%\llqtwebkit\debug\ /y)
if not exist %SL_DEST_DIR%\llqtwebkit\release\llqtwebkit.lib (xcopy %LLQTWEBKIT_SRC_DIR%\release\llqtwebkit.lib %SL_DEST_DIR%\llqtwebkit\release\ /y)
