.TH LIBMICROHTTPD "3" "28 Oct 2009 "libmicrohttpd"
.SH "NAME"
GNU libmicrohttpd \- library for embedding HTTP servers
.SH "SYNOPSIS"

\fB#include <sys/types.h>
\fB#include <sys/select.h>
\fB#include <sys/socket.h>
\fB#include <microhttpd.h>

.SH "DESCRIPTION"
.P
GNU libmicrohttpd (short MHD) allows applications to easily integrate the functionality of a simple HTTP server.  MHD is a GNU package.
.P
The details of the API are described in comments in the header file, a detailed reference documentation and in brief on the MHD webpage.
.P
.SH "SEE ALSO"
\fBcurl\fP(1), \fBlibcurl\fP(3)

.SH "LEGAL NOTICE"
libmicrohttpd is released under both the LGPL Version 2 or higher and
the GNU GPL with eCos extension.  For details on both licenses please
read the respective appendix in the manual.

.SH "FILES"
.TP
microhttpd.h
libmicrohttpd include file
.TP
libmicrohttpd.so
libmicrohttpd library

.SH "REPORTING BUGS"
Report bugs by using mantis <https://gnunet.org/mantis/>.

.SH "AUTHORS"
GNU libmicrohttpd was originally designed by Christian Grothoff <christian@grothoff.org> and Chris GauthierDickey <chrisg@cs.du.edu>.  The original implementation was done by Daniel Pittman <depittman@gmail.com> and Christian Grothoff.  SSL/TLS support was added by Sagie Amir using code from gnutls.  See the AUTHORS file in the distribution for a more detailed list of contributors.

.SH "AVAILABILITY"
You can obtain the latest version from http://www.gnu.org/software/libmicrohttpd/.
