SRCS=DirectoryNode.cpp \
     DirectoryNodeEpisodes.cpp \
     DirectoryNodeGrouped.cpp \
     DirectoryNodeMoviesOverview.cpp \
     DirectoryNodeMusicVideosOverview.cpp \
     DirectoryNodeOverview.cpp \
     DirectoryNodeRecentlyAddedEpisodes.cpp \
     DirectoryNodeRecentlyAddedMovies.cpp \
     DirectoryNodeRecentlyAddedMusicVideos.cpp \
     DirectoryNodeRoot.cpp \
     DirectoryNodeSeasons.cpp \
     DirectoryNodeTitleMovies.cpp \
     DirectoryNodeTitleMusicVideos.cpp \
     DirectoryNodeTitleTvShows.cpp \
     DirectoryNodeTvShowsOverview.cpp \
     QueryParams.cpp \

LIB=videodatabasedirectory.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
