#! /bin/sh

# Copyright 2007 Johannes Lehtinen
# This shell script is free software; Johannes Lehtinen gives unlimited
# permission to copy, distribute and modify it.

set -e

tmpdir="tmp/test-loadminimal"
mkdir -p "$tmpdir"
LC_ALL=C libtool --mode=execute $TEST_WRAPPER ../console/cpluff-console <<EOI > "$tmpdir"/console-out.txt
set-log-level error
load-plugin $srcdir/plugins/minimal
show-plugin-info minimal
EOI
sed -n -e '/^{$/,/^}$/{/^  plugin_path =/!p}' < "$tmpdir"/console-out.txt > "$tmpdir"/filtered.txt
diff -u "$srcdir"/expected/output-loadminimal.txt "$tmpdir"/filtered.txt
