#! /bin/sh

# Copyright 2007 Johannes Lehtinen
# This shell script is free software; Johannes Lehtinen gives unlimited
# permission to copy, distribute and modify it.

set -e

trap '' 6
! ./testsuite fatalerrordefault 2> /dev/null
