#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOHOSTS}" ]
then
        exit 0
fi

. /scripts/live-functions

log_begin_msg "Setting hostname"

# live-initramfs script

# Change hostname only if it is not set
if [ ! -f /root/etc/hostname ] || grep -qs localhost\.localdomain /root/etc/hostname
then
	echo "${HOSTNAME}" > /root/etc/hostname
else
	HOSTNAME="$(cat /root/etc/hostname)"
	really_export HOSTNAME
fi

# Create /etc/hosts only if it is not present or empty
if [ ! -s /root/etc/hosts ]
then
	cat > /root/etc/hosts << EOF
127.0.0.1 localhost
127.0.1.1 ${HOSTNAME}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF
fi

hostname "${HOSTNAME}"

log_end_msg
