//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FileZilla server.rc
//
#define IDR_MAINFRAME                   1
#define IDB_LEDS                        100
#define IDD_ABOUTBOX                    101
#define IDD_CONNECT_DIALOG              102
#define IDD_ENTERSOMETHING              103
#define IDD_GROUPS                      104
#define IDD_GROUPS2                     105
#define IDD_GROUPS_GENERAL              106
#define IDD_GROUPS_SPEEDLIMIT           107
#define IDD_NEWUSER                     108
#define IDD_OFFLINEASK                  109
#define IDD_OPTIONS_ADMININTERFACE      110
#define IDD_OPTIONS_ADMININTERFACE_LOCAL 111
#define IDD_OPTIONS_GENERAL             112
#define IDD_OPTIONS_GENERAL_WELCOMEMESSAGE 113
#define IDD_OPTIONS_GSS                 114
#define IDD_OPTIONS_LOGGING             115
#define IDD_OPTIONS_MISC                116
#define IDD_OPTIONS_SECURITY            117
#define IDD_OPTIONS_SPEEDLIMIT          118
#define IDD_SAPREFS                     119
#define IDD_SPEEDLIMIT_RULE_DIALOG      120
#define IDD_USERS                       121
#define IDD_USERS_GENERAL               122
#define IDD_USERS_SPEEDLIMIT            123
#define IDI_EMPTY                       124
#define IDD_OPTIONS_PASV                124
#define IDI_GREEN                       125
#define IDI_YELLOW                      126
#define IDI_RED                         127
#define IDI_UNKNOWN                     128
#define IDI_HOME                        129
#define IDP_SOCKETS_INIT_FAILED         130
#define IDR_DIRCONTEXT                  131
#define IDR_GROUPCONTEXT                132
#define IDR_OUTPUTCONTEXT               133
#define IDR_SYSTRAY_MENU                134
#define IDR_USERCONTEXT                 135
#define IDR_USERVIEWCONTEXT             136
#define IDS_ADDGROUPDIALOG              137
#define IDS_ADDUSERDIALOG               138
#define IDS_BROWSEFORFOLDER             139
#define IDS_BROWSEFORFOLDER2            140
#define IDS_COPYGROUPDIALOG             141
#define IDS_COPYUSERDIALOG              142
#define IDS_ERRORMSG_ENTERSTRING        143
#define IDS_ERRORMSG_GROUPALREADYEXISTS 144
#define IDS_ERRORMSG_USERALREADYEXISTS  145
#define IDS_INPUTDIALOGTEXT_RENAME      146
#define IDS_OPTIONSPAGE_ADMININTERFACE  147
#define IDS_OPTIONSPAGE_GENERAL         148
#define IDS_OPTIONSPAGE_GENERAL_WELCOMEMESSAGE 149
#define IDS_OPTIONSPAGE_GSS             150
#define IDS_OPTIONSPAGE_LOGGING         151
#define IDS_OPTIONSPAGE_MISC            152
#define IDS_OPTIONSPAGE_SECURITY        153
#define IDS_OPTIONSPAGE_SPEEDLIMIT      154
#define IDS_OPTIONSPAGE_PASV            155
#define IDB_DONATE                      156
#define IDC_CAPTION_BAR                 1000
#define IDC_CHECK_DAY1                  1001
#define IDC_CHECK_DAY2                  1002
#define IDC_CHECK_DAY3                  1003
#define IDC_CHECK_DAY4                  1004
#define IDC_CHECK_DAY5                  1005
#define IDC_CHECK_DAY6                  1006
#define IDC_CHECK_DAY7                  1007
#define IDC_CONNECTDIALOG_ADDRESS       1008
#define IDC_CONNECTDIALOG_ALWAYS        1009
#define IDC_CONNECTDIALOG_PASSWORD      1010
#define IDC_CONNECTDIALOG_PORT          1011
#define IDC_DATE_CHECK                  1012
#define IDC_DATE_VALUE                  1013
#define IDC_DIRADD                      1014
#define IDC_DIRREMOVE                   1015
#define IDC_DIRRENAME                   1016
#define IDC_DIRS                        1017
#define IDC_DIRS_CREATE                 1018
#define IDC_DIRS_DELETE                 1019
#define IDC_DIRS_LIST                   1020
#define IDC_DIRS_SUBDIRS                1021
#define IDC_DIRSETASHOME                1022
#define IDC_DLG_FRAME                   1023
#define IDC_EDIT1                       1024
#define IDC_FILES_APPEND                1025
#define IDC_FILES_DELETE                1026
#define IDC_FILES_READ                  1027
#define IDC_FILES_WRITE                 1028
#define IDC_FROM_CHECK                  1029
#define IDC_FROM_TIME                   1030
#define IDC_GROUP                       1031
#define IDC_GROUPS_ADDGROUP             1032
#define IDC_GROUPS_AUTOCREATE           1033
#define IDC_GROUPS_COPYGROUP            1034
#define IDC_GROUPS_DIRS_AUTOCREATE      1035
#define IDC_GROUPS_GROUPLIST            1036
#define IDC_GROUPS_IPLIMIT              1037
#define IDC_GROUPS_MAXCONNCOUNT         1038
#define IDC_GROUPS_MAXUSERBYPASS        1039
#define IDC_GROUPS_REMOVEGROUP          1040
#define IDC_GROUPS_RENAMEGROUP          1041
#define IDC_GROUPS_SPEEDLIMIT_SERVERBYPASS_DOWNLOAD 1042
#define IDC_GROUPS_SPEEDLIMIT_SERVERBYPASS_UPLOAD 1043
#define IDC_HOMEPAGE                    1044
#define IDC_INFXP                       1045
#define IDC_INFXPSTRICT                 1046
#define IDC_IPLIMIT                     1047
#define IDC_LNK                         1048
#define IDC_LOCALCREDENTIALS            1049
#define IDC_LOGINTIMEOUT                1050
#define IDC_MAIL                        1051
#define IDC_MAXCONNCOUNT                1052
#define IDC_MAXUSERBYPASS               1053
#define IDC_MAXUSERS                    1054
#define IDC_NEEDPASS                    1055
#define IDC_NEWUSER_GROUP               1056
#define IDC_NEWUSER_NAME                1057
#define IDC_OPTIONS_ADMININTERFACE_CHANGEPASS 1058
#define IDC_OPTIONS_ADMININTERFACE_IPADDRESSES 1059
#define IDC_OPTIONS_ADMININTERFACE_IPBINDINGS 1060
#define IDC_OPTIONS_ADMININTERFACE_NEWPASS 1061
#define IDC_OPTIONS_ADMININTERFACE_NEWPASS2 1062
#define IDC_OPTIONS_ADMININTERFACE_PORT 1063
#define IDC_OPTIONS_GENERAL_WELCOMEMESSAGE_WELCOMEMESSAGE 1064
#define IDC_OPTIONS_LOGGING_DELETE      1065
#define IDC_OPTIONS_LOGGING_DELETETIME  1066
#define IDC_OPTIONS_LOGGING_ENABLE      1067
#define IDC_OPTIONS_LOGGING_LIMIT       1068
#define IDC_OPTIONS_LOGGING_LIMITSIZE   1069
#define IDC_OPTIONS_LOGGING_LOGTYPE     1070
#define IDC_OPTIONS_LOGGING_LOGTYPE2    1071
#define IDC_OPTIONS_MISC_CUSTOM_PASV    1072
#define IDC_OPTIONS_MISC_CUSTOM_PASV_IP 1073
#define IDC_OPTIONS_MISC_CUSTOM_PASV_MAX_PORT 1074
#define IDC_OPTIONS_MISC_CUSTOM_PASV_MIN_PORT 1075
#define IDC_OPTIONS_MISC_CUSTOM_PASV_TEXT 1076
#define IDC_OPTIONS_MISC_DONTSHOWPASS   1077
#define IDC_OPTIONS_MISC_STARTMINIMIZED 1078
#define IDC_OPTIONS_TRANSFERBUFFERSIZE  1079
#define IDC_OUTFXP                      1080
#define IDC_OUTFXPSTRICT                1081
#define IDC_PAGE_TREE                   1082
#define IDC_PASS                        1083
#define IDC_PHELP                       1084
#define IDC_PORT                        1085
#define IDC_PROMPTPASSWORD              1086
#define IDC_RADIO1                      1087
#define IDC_RADIO2                      1088
#define IDC_RADIO3                      1089
#define IDC_RELATIVE                    1090
#define IDC_SPEED                       1091
#define IDC_SPEEDLIMIT_DOWNLOAD1        1092
#define IDC_SPEEDLIMIT_DOWNLOAD2        1093
#define IDC_SPEEDLIMIT_DOWNLOAD3        1094
#define IDC_SPEEDLIMIT_DOWNLOAD4        1095
#define IDC_SPEEDLIMIT_DOWNLOAD_ADD     1096
#define IDC_SPEEDLIMIT_DOWNLOAD_DOWN    1097
#define IDC_SPEEDLIMIT_DOWNLOAD_REMOVE  1098
#define IDC_SPEEDLIMIT_DOWNLOAD_RULES_LIST 1099
#define IDC_SPEEDLIMIT_DOWNLOAD_UP      1100
#define IDC_SPEEDLIMIT_DOWNLOAD_VALUE   1101
#define IDC_SPEEDLIMIT_UPLOAD1          1102
#define IDC_SPEEDLIMIT_UPLOAD2          1103
#define IDC_SPEEDLIMIT_UPLOAD3          1104
#define IDC_SPEEDLIMIT_UPLOAD4          1105
#define IDC_SPEEDLIMIT_UPLOAD_ADD       1106
#define IDC_SPEEDLIMIT_UPLOAD_DOWN      1107
#define IDC_SPEEDLIMIT_UPLOAD_REMOVE    1108
#define IDC_SPEEDLIMIT_UPLOAD_RULES_LIST 1109
#define IDC_SPEEDLIMIT_UPLOAD_UP        1110
#define IDC_SPEEDLIMIT_UPLOAD_VALUE     1111
#define IDC_TEXT                        1112
#define IDC_THREADNUM                   1113
#define IDC_TIMEOUT                     1114
#define IDC_TO_CHECK                    1115
#define IDC_TO_TIME                     1116
#define IDC_TRANSFERTIMEOUT             1117
#define IDC_USEGSS                      1118
#define IDC_USERADD                     1119
#define IDC_USERCOPY                    1120
#define IDC_USERLIST                    1121
#define IDC_USERREMOVE                  1122
#define IDC_USERRENAME                  1123
#define IDC_USERS_SPEEDLIMIT_SERVERBYPASS_DOWNLOAD 1124
#define IDC_USERS_SPEEDLIMIT_SERVERBYPASS_UPLOAD 1125
#define IDC_VERSION                     1126
#define IDC_DONATE                      1127
#define IDD_OPTIONS_PASV_USEPORTRANGE   1134
#define IDC_OPTIONS_PASV_PORTMIN        1135
#define IDC_OPTIONS_PASV_PORTMAX        1136
#define IDC_OPTIONS_PASV_NOLOCAL        1137
#define IDC_OPTIONS_PASV_IPTYPE1        1138
#define IDC_OPTIONS_PASV_IPTYPE2        1139
#define IDC_OPTIONS_PASV_IPTYPE3        1140
#define IDC_OPTIONS_PASV_IP             1141
#define IDC_OPTIONS_PASV_URL            1142
#define IDC_OPTIONS_PASV_TEXT           1143
#define ID_ACTIVE                       32768
#define ID_DIRMENU_ADD                  32769
#define ID_DIRMENU_REMOVE               32770
#define ID_DIRMENU_RENAME               32771
#define ID_DIRMENU_SETASHOMEDIR         32772
#define ID_EDIT_SETTINGS                32773
#define ID_FILE_CONNECT                 32774
#define ID_FILE_DISCONNECT              32775
#define ID_GROUPMENU_ADD                32776
#define ID_GROUPMENU_COPY               32777
#define ID_GROUPMENU_REMOVE             32778
#define ID_GROUPMENU_RENAME             32779
#define ID_GROUPS                       32780
#define ID_INDICATOR_RECVCOUNT          32781
#define ID_INDICATOR_RECVLED            32782
#define ID_INDICATOR_RECVRATE           32783
#define ID_INDICATOR_SENDCOUNT          32784
#define ID_INDICATOR_SENDLED            32785
#define ID_INDICATOR_SENDRATE           32786
#define ID_LOCK                         32787
#define ID_MENU_EDIT_GROUPS             32788
#define ID_MENU_EDIT_USERS              32789
#define ID_OUTPUTCONTEXT_CLEARALL       32790
#define ID_OUTPUTCONTEXT_COPYTOCLIPBOARD 32791
#define ID_TRAY_EXIT                    32792
#define ID_TRAY_RESTORE                 32793
#define ID_USERMENU_ADD                 32794
#define ID_USERMENU_COPY                32795
#define ID_USERMENU_REMOVE              32796
#define ID_USERMENU_RENAME              32797
#define ID_USERS                        32798
#define ID_USERVIEWCONTEXT_KICK         32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           1227
#endif
#endif
